### ISSUE TITLE
[1.11.2-4.3.1.257] crashes dedicated server Forge 1.11.2 build 2264

### ISSUE THREAD

**Issue by kreezxil** [mezz/JustEnoughItems#798] opened 2017-04-06 22:29 UTC
Notes:
     looks like some client side classes escaped to the server

crash report:
https://gist.github.com/2cbbce002145ca85122b4a84c2dfed96

fml server latest:
https://gist.github.com/7b2c22833762d0390381852a9ed23f65

**Comment by mezz** [comment] 2017-04-06 22:55
Thanks for the report!
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/795
Fixed in the latest version.

**Closed as completed by mezz** 2017-04-06 22:55 UTC
Labels: duplicate
