### ISSUE TITLE
crash upon loading multiplayer connection. jei unable to start

### ISSUE THREAD

**Issue by kain184** [mezz/JustEnoughItems#465] opened 2016-09-28 17:21 UTC
https://gist.github.com/mezz/54b2054167f1a0d20e4918b8f5e60e77

**Comment by mezz** [comment] 2016-09-29 04:02
Thanks for the report!
This is a TSON Craft issue and has already been reported to the mod author: https://minecraft.curseforge.com/projects/tson-craft/issues/8
Duplicate of https://github.com/mezz/JustEnoughItems/issues/455

I will add a check here to try to keep JEI from crashing from the issue.

**Closed as completed** 2016-09-29 04:03 UTC
Labels: duplicate
