### ISSUE TITLE
[Bug]: JEI Tooltip Error

### ISSUE THREAD

**Issue by MarlonElv** [mezz/JustEnoughItems#3524] opened 2024-06-01 18:24 UTC
### Steps to Reproduce the Bug

JEI Tooltip shows a message that reads "Tooltip Error, Check Logs" whenever we hover over any item on JEI 

### Expected Behavior

JEI should show most of the recipes that are within the Custom Modpack 

### Actual Behavior

Tooltips don't show correctly
![image_2024-06-01_111114660](https://github.com/mezz/JustEnoughItems/assets/143577938/4b5693b3-857d-4d7a-ae2b-56461542cd90)

### Mod Pack Version (Optional)

1.20.1

### Extra Notes (Optional)

Custom Modpack Mods:
Advancement Plaques [Forge]
Appleskin
Architectury API
AstikorCarts Redux
Backpacked
BedBenefits
Better Combat
Better Third Person
Biomes O' Plenty
Bookshelf
Bountiful
Canary
Carry On
Catalogue
Cloth Config API
Clumps
Cobblemon
Collective
CoroUtil
Corpse
Create
Create Stuff & Additions 
Create: Interiors
CreativeCore 
Cristel Lib
Curios API
Dimensional Dungeons
Easier Sleeping
Easy Magic
Eating Animation
Embeddium
Embeddium Extra
Farmers Delight
Fast Load
First-Person Model
Game Menu Mod Option
GeckoLib
Goblin Traders
GroovyModLoader
Hand Over Your Items
Handcrafted
Healing Campfire
Hopo Better Mineshaft
HT's  Treechop
Iceberg 
Immersive Aircraft
Incendium
ItemPhysic Lite
Jade
JEI
Kambrik
Kotlin for Forge
Legendary Tooltips [Client only] 
Lootr
Moonlight Lib
multi
Nether's Exoticism
Not Enough Animations
Oculus
Overflowing Bars
Perfect Plushies
Pick up Notifier
PKGBadges
playerAnimator 
Prism
project-961439
Puzzles Lib
Quark
Quark Delight
Resourceful Lib
Saturn 
Seamless Loading Screen
Serene Seasons 
Shield Expansion 
Simple Voice Chat
Simply Swords
Skin Layers 3D
Sky Villages 
Supplemetaries
TerraBlender
Terralith
tetra
Tomtarus Cobblemon & Farmers Delight Tweaks 
Towns and Towers
Traveler's Titles 
Visuality: Reforged 
What are they up to 
Xaero's Minimap
Xaero's World Map
YDM's Weapon Master
YUNG's API 
Zeta

### latest.log

https://gist.github.com/MarlonElv/03b4ad275a205fb7f8681711a1f1687b

**Comment by Veynam** [comment] 2024-06-09 21:09
Shield Expansion is causing your issue. Had the exact same problem. Im assuming something is just broken with that mod

**Comment by mezz** [comment] 2024-06-11 05:24
Thanks for the report! This happens when a modded item crashes. In previous versions of JEI it would just crash the game.
Here, JEI tried to stop the whole game from crashing but something in the system might still be really broken.
Try the latest release of JEI from today, I updated it to try to contain the damage a bit better.

Duplicate of #3473

**Closed as not planned by mezz** 2024-06-11 05:24 UTC
