### ISSUE TITLE
Suggestion:subsets

### ISSUE THREAD

**Issue by blockbreaker1361** [mezz/JustEnoughItems#198] opened 2016-03-03 12:10 UTC
It would be nice if your mod had an addon or subset like NEI with a bar at the top center to access to see what all mods are in the game. You can then shift-click on the entry to bring all the mods contents up.

**Comment by TehNut** [comment] 2016-03-03 17:04
Dupe of #163

**Closed as completed** 2016-03-04 00:36 UTC
Labels: duplicate
