### ISSUE TITLE
JEI text rendering does not provide the stack for enchanted books

### ISSUE THREAD

**Issue by yrsegal** [mezz/JustEnoughItems#1621] opened 2019-07-02 14:46 UTC
RenderTooltipEvent.PostText is passed an empty stack, causing features like Quark's EnchantedBooksShowItems to fail to function.

In JEI (expanded)
<img width="250" alt="Screen Shot 2019-07-02 at 5 42 42 PM" src="https://user-images.githubusercontent.com/6596492/60522067-010a1480-9cf1-11e9-86ad-2b26774fc728.png">
In Inventory (expanded)
<img width="250" alt="Screen Shot 2019-07-02 at 5 43 16 PM" src="https://user-images.githubusercontent.com/6596492/60522078-036c6e80-9cf1-11e9-96d9-815614c36470.png">

In JEI (quark visual stat display)
<img width="250" alt="Screen Shot 2019-07-02 at 5 43 33 PM" src="https://user-images.githubusercontent.com/6596492/60522080-04050500-9cf1-11e9-9488-60876734ec03.png">
In Inventory (quark visual stat display)
<img width="250" alt="Screen Shot 2019-07-02 at 5 43 52 PM" src="https://user-images.githubusercontent.com/6596492/60522087-049d9b80-9cf1-11e9-9f6b-c58f144a7350.png">

In JEI (quark enchanted books show tools)
<img width="250" alt="Screen Shot 2019-07-02 at 5 43 40 PM" src="https://user-images.githubusercontent.com/6596492/60522082-04050500-9cf1-11e9-9a29-e86e595f51d5.png">
In Inventory (quark enchanted books show tools)
<img width="250" alt="Screen Shot 2019-07-02 at 5 43 46 PM" src="https://user-images.githubusercontent.com/6596492/60522085-04050500-9cf1-11e9-8e28-d7df5aeaebac.png">

**Comment by mezz** [comment] 2019-07-05 03:24
Thanks for the report!
Which Minecraft versions does this bug exist in?

**Comment by yrsegal** [comment] 2019-07-07 02:47
1.12, is where i'm testing this. I don't know about the others.

**Comment by mezz** [comment] 2019-07-08 03:13
I tested this out and JEI is passing the stack to the `RenderTooltipEvent.PostText` event.
I checked tooltips in the ingredient list, the bookmarks, and the recipes.

Can you see if there is some other mod involved that is messing with the event?
The stack might be set to empty by a handler for `RenderTooltipEvent.Pre`, `RenderTooltipEvent.Color`, or an earlier handler for `RenderTooltipEvent.PostText`.

**Comment by yrsegal** [comment] 2019-07-08 11:29
This is in an environment with only Quark and JEI. I'll check further...

**Comment by yrsegal** [comment] 2019-07-08 11:40
... I feel stupid. This was an older version bug. Sorry about the inconvenience, mezz :P

**Comment by mezz** [comment] 2019-07-09 19:05
Cool, good to know!

**Comment by yrsegal** [comment] 2019-07-11 11:45
Actually, this appears to still be true *with enchanted books only.*

**Comment by mezz** [comment] 2019-07-11 19:42
Ah ok. This is caused by an enchanted book hack in JEI added to fix this issue: https://github.com/mezz/JustEnoughItems/issues/1202
The hack is no longer required in 1.13+, but I can submit a simple fix for this issue in 1.12.

**Comment by mezz** [comment] 2019-07-11 19:58
One thing I found while debugging: the Ancient Tomes from Quark do not have this EnchantedBooksShowItems feature on the tooltip.

**Comment by mezz** [comment] 2019-07-11 20:02
![2019-07-11_12 57 02](https://user-images.githubusercontent.com/916092/61081468-275c3e00-a3dc-11e9-87ea-4f643a0dcb20.png)
![2019-07-11_12 56 16](https://user-images.githubusercontent.com/916092/61081469-275c3e00-a3dc-11e9-8ec6-ed111d1bbb53.png)

looks good now

**Closed as completed by mezz** 2019-07-11 20:02 UTC
Labels: bug

**Comment by yrsegal** [comment] 2019-07-12 02:01
the ancient tomes actually got it a while ago, the update just came out. :P

**Comment by mezz** [comment] 2019-07-12 02:01
Nice, ok. Everything good then :)
