### ISSUE TITLE
Game crash when opening inventory

### ISSUE THREAD

**Issue by Rikzster** [mezz/JustEnoughItems#1681] opened 2019-08-16 12:31 UTC
Hi! Every time I open the inventory the game freezes for a few seconds and then just crashes completely back to the launcher. Here's the crash report. I have other mods installed but since I don't understand anything about this crash report I was hoping someone could help me find out if the crash is related to JEI or some mod I have installed with it.
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 8/16/19 3:26 PM
Description: Rendering ingredient

java.lang.IllegalAccessError: tried to access method net.minecraft.client.renderer.ItemRenderer.func_191961_a(Lnet/minecraft/client/renderer/model/IBakedModel;Lnet/minecraft/item/ItemStack;)V from class mezz.jei.render.ItemStackFastRenderer
	at mezz.jei.render.ItemStackFastRenderer.uncheckedRenderItemAndEffectIntoGUI(ItemStackFastRenderer.java:70) ~[?:6.0.0.10] {}
	at mezz.jei.render.ItemStackFastRenderer.renderItemAndEffectIntoGUI(ItemStackFastRenderer.java:35) ~[?:6.0.0.10] {}
	at mezz.jei.render.IngredientListBatchRenderer.render(IngredientListBatchRenderer.java:169) ~[?:6.0.0.10] {}
	at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:106) ~[?:6.0.0.10] {}
	at mezz.jei.gui.overlay.IngredientGridWithNavigation.draw(IngredientGridWithNavigation.java:113) ~[?:6.0.0.10] {}
	at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:177) ~[?:6.0.0.10] {}
	at mezz.jei.gui.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:79) ~[?:6.0.0.10] {}
	at net.minecraftforge.eventbus.ASMEventHandler_78_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-0.10.6-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-0.10.6-service.jar:?] {}
	at net.minecraft.client.gui.screen.Screen.renderBackground(Screen.java:362) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.Screen.renderBackground(Screen.java:356) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.InventoryScreen.render(SourceFile:79) ~[?:?] {}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:360) ~[?:?] {}
	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:691) ~[?:?] {}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:898) ~[?:?] {pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:886) [?:?] {pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.0.49.jar:28.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$349/639690519.call(Unknown Source) [forge-1.14.4-28.0.49.jar:28.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-3.2.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50) [modlauncher-3.2.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:68) [modlauncher-3.2.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:80) [modlauncher-3.2.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-3.2.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at mezz.jei.util.ErrorUtil.createRenderIngredientException(ErrorUtil.java:244)

-- Ingredient being rendered --
Details:
	Ingredient Mod: Minecraft
	Ingredient Info: 1 stone minecraft:stone
Stacktrace:
	at mezz.jei.util.ErrorUtil.createRenderIngredientException(ErrorUtil.java:244)
	at mezz.jei.render.ItemStackFastRenderer.renderItemAndEffectIntoGUI(ItemStackFastRenderer.java:37)
	at mezz.jei.render.IngredientListBatchRenderer.render(IngredientListBatchRenderer.java:169)
	at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:106)
	at mezz.jei.gui.overlay.IngredientGridWithNavigation.draw(IngredientGridWithNavigation.java:113)
	at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:177)
	at mezz.jei.gui.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:79)
	at net.minecraftforge.eventbus.ASMEventHandler_78_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraft.client.gui.screen.Screen.renderBackground(Screen.java:362)
	at net.minecraft.client.gui.screen.Screen.renderBackground(Screen.java:356)
	at net.minecraft.client.gui.screen.inventory.InventoryScreen.render(SourceFile:79)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:360)
	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:691)
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:898)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:886)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$349/639690519.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:68)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:80)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.screen.inventory.InventoryScreen
	Mouse location: Scaled: (480, 300). Absolute: (960.000000, 600.000000)
	Screen size: Scaled: (960, 600). Absolute: (1920, 1200). Scale factor of 2.000000

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Rikzster'/263, l='MpServer', x=-231.95, y=74.00, z=-236.30]]
	Chunk stats: Client Chunk Cache: 1225, 841
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-224,70,-240), Chunk: (at 0,4,0 in -14,-15; contains blocks -224,0,-240 to -209,255,-225), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 1196 game time, 1196 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3694740456 bytes (3523 MB) / 6274678784 bytes (5984 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 3.2.0+60+b86c1d4
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-0.10.6-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.0.49.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.0.49.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-0.16.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.0.49.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.0.49.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.14.4_HD_U_F4_pre2.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.14.4-28.0.49.jar fml TRANSFORMATIONSERVICE 
	FML: 28.0
	Forge: net.minecraftforge:28.0.49
	FML Language Providers: 
		javafml@28.0
		minecraft@1
	Mod List: 
		AppleSkin-mc1.14.4-forge-1.0.12.jar AppleSkin {appleskin@1.0.12 DONE}
		Cucumber-1.14.4-2.0.2.jar Cucumber Library {cucumber@2.0.2 DONE}
		ElevatorMod-1.14.4-1.3.11.jar Elevator Mod {elevatorid@1.14.4-1.3.11 DONE}
		FastLeafDecay-v17.jar FastLeafDecay {fastleafdecay@v17 DONE}
		furniture-7.0.0-pre5-1.14.4.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre5 DONE}
		Hwyla-forge-1.10.5-B66_1.14.4.jar Waila {waila@version DONE}
		inventorysorter-1.14.4-15.2.0.jar Simple Inventory Sorter {inventorysorter@15.2.0 DONE}
		ironchest-1.14.3-9.0.DEV.55a7af2.jar Iron Chests {ironchest@1.14.3-9.0.DEV.55a7af2 DONE}
		jei-1.14.4-6.0.0.10.jar Just Enough Items {jei@6.0.0.10 DONE}
		Neat+1.5-19.jar Neat {neat@1.5-19 DONE}
		PickleTweaks-1.14.4-3.0.4.jar Pickle Tweaks {pickletweaks@3.0.4 DONE}
		randompatches-1.14.4-1.18.1.1.jar RandomPatches {randompatches@1.14.4-1.18.1.1 DONE}
		swingthroughgrass-1.14.4-1.3.2.jar SwingThroughGrass {swingthroughgrass@1.14.4-1.3.2 DONE}
		forge-1.14.4-28.0.49-universal.jar Forge {forge@28.0.49 DONE}
		forge-1.14.4-28.0.49-client.jar Minecraft {minecraft@1.14.4 DONE}
	Launched Version: 1.14.4-forge-28.0.49
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce GTX 980/PCIe/SSE2 GL version 4.6.0 NVIDIA 431.60, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/1.14-r1.zip
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz

**Comment by ghost** [comment] 2019-08-16 17:11
you using optifine? if yes this is a duplicate issue that Mezz knows about, temporary fix is to remove Optifine

optifine needs to update

**Comment by PseudoResonance** [comment] 2019-08-16 21:55
Yes, this is a duplicate of #1668 and related to sp614x/optifine#2737

**Closed as completed** 2019-08-18 19:05 UTC
Labels: duplicate
