### ISSUE TITLE
Crash while navigating JEI

### ISSUE THREAD

**Issue by zepheris** [mezz/JustEnoughItems#113] opened 2016-01-14 05:01 UTC
I'm not sure if the crash is a JEI issue or related to another mod. I'm running 1.8.9 with forge 1.8.9-11.15.0.1697.

I updated JEI today  along with a couple of other mods and noticed that when browsing through the pages (I was pressing the right button), I got to page 67 and Crashed. The page before I crashed had a bunch of facades from Tinker's construct. I tried to go the opposite direction and ended up going back maybe 4 or 5 pages before I crashed again. I've attached my crash report as well as the log file. I've also included a screenshot of the mods I'm currently running.

I think I've also narrwoed down the crash. I ended up downgrading JEI to 1.8.9-2.16.2.78 and still had the crash. I then removed Chisel-MC1.8.9-0.0.2.3 and PortableCrafting-1.8.9-1.0. I'm not having the crash any more.

Do the logs indicate anything that can be fixed in JEI or should I contact the mod authors about the crash?

Thanks!

[crash-2016-01-13_21.31.31-client.txt](https://github.com/mezz/JustEnoughItems/files/89872/crash-2016-01-13_21.31.31-client.txt)

[fml-client-latest.log.txt](https://github.com/mezz/JustEnoughItems/files/89873/fml-client-latest.log.txt)
![image](https://cloud.githubusercontent.com/assets/4251071/12315955/3deee4f0-ba3e-11e5-8c91-3922958f1f21.png)

**Comment by mezz** [comment] 2016-01-14 05:26
Thanks for the report!
This is a dupe of https://github.com/mezz/JustEnoughItems/issues/109
Most likely a bad interaction between buildcraft facades and chisel blocks.

**Closed as completed by mezz** 2016-01-14 05:26 UTC
Labels: duplicate
