### ISSUE TITLE
JEI overload log durring Minecraft loading

### ISSUE THREAD

**Issue by 0Navis0** [mezz/JustEnoughItems#553] opened 2016-10-30 21:53 UTC
JEI totally overload the log durring Minecraft loading by repeating this part of log so many times. http://pastebin.com/Q8diG1se
It has for consequence than Minecraft use until 4Gb of memory only for the log and the log files weigh until 1Gb. Minecraft slow down and lag a lot because of that.

**Comment by mezz** [comment] 2016-10-30 22:06
Thanks for the report!
Can you give me a link to the pack you are using so I can test?

**Comment by 0Navis0** [comment] 2016-10-30 22:14
It's my own pack, it's still in alpha and not published in Curse.

**Comment by 0Navis0** [comment] 2016-10-30 22:18
I link this issue here too because it seems that it comes from JEI too https://github.com/stanhebben/MineTweaker3/issues/388#issuecomment-257183609

**Comment by jaredlll08** [comment] 2016-10-30 22:19
Hey @mezz I ran into this issue with someone else yesterday, it may not be our mods
fml just logs it as our mods for some reason, solution:
https://github.com/stanhebben/MineTweaker3/issues/388#issuecomment-257183780

**Comment by mezz** [comment] 2016-10-30 22:20
Yeah it's the same issue, it just shows MineTweaker because it  is reloading JEI at world load.

**Comment by jaredlll08** [comment] 2016-10-30 22:20
well it can be reproduced without minetweaker, Darkosto tested that for me

**Comment by 0Navis0** [comment] 2016-10-30 22:21
It doesn't come from the mods since this bug doesn't happen when JEI isn't here.

**Comment by mezz** [comment] 2016-10-30 22:29
Try leaving JEI in and removing other mods.
I tested and this does not happen on a big pack like AllTheMods.

**Comment by 0Navis0** [comment] 2016-10-30 22:30
Here is the mod list I play with http://www.modlister.com/user/Hypsellis

**Comment by mezz** [comment] 2016-10-30 22:35
Sorry but I do not have the time to go download all of those.

**Comment by 0Navis0** [comment] 2016-10-30 22:35
Yeah I understand, I will try something.

**Comment by 0Navis0** [comment] 2016-10-30 23:00
Ok I really don't know where it comes, anyway it happens when JEI load the itemstack durring the phase 6 of Minecraft loading, and there is the same when it loads a world too.

**Comment by mezz** [comment] 2016-10-30 23:02
Some mod's tooltip handler is crashing when JEI calls it during Minecraft loading.
Try leaving JEI in and removing other mods. When you find the mod that is causing the crash, I can take a look and fix it.

**Comment by 0Navis0** [comment] 2016-10-30 23:14
It doesn't cause any crash, only log overloading.

**Comment by mezz** [comment] 2016-10-30 23:14
What you're seeing is the event system catching and logging a crash.

**Comment by 0Navis0** [comment] 2016-10-30 23:15
Yeah but Minecraft doesn't crash, it still works fine, it just lags a lot.

**Comment by 0Navis0** [comment] 2016-10-30 23:15
I will try to test all the mods, but it will take me a lot of time so much my modpack is big. I'm clearly not in the mood for doing it today, so I will do it when I will have time and be in the mood.

**Comment by mezz** [comment] 2016-10-30 23:16
This will go much more smoothly if you believe me, but I can continue to explain more if you like.
Let me know whenever you're up for it, I'll leave this issue open in the meantime.

**Comment by 0Navis0** [comment] 2016-10-30 23:22
I believe you don't worry. I will try to find the bug cause, but I can't promise I will find it.

**Comment by mezz** [comment] 2016-10-30 23:23
The easiest strategy is probably to make a new instance with just JEI, and add 10 mods to see if you get the error log. If no, try the next 10 and so on. You can narrow things down quicker that way since Minecraft will not take forever to start when you only have a few mods.

**Comment by 0Navis0** [comment] 2016-10-30 23:36
Yeah I know how to do, I already did it many times with other bugs.

**Comment by 0Navis0** [comment] 2016-10-31 00:05
Oh wait I finded something interesting looking in the log, I had forgotten to send you this part which happens just before what I sent you http://pastebin.com/6KEwnjma. It seems that cause of the bug is V-Tweaks, I will check it.

**Comment by 0Navis0** [comment] 2016-10-31 00:17
And I confirm you that the problem comes from V-Tweaks. ;)

**Comment by mezz** [comment] 2016-10-31 00:28
Thanks, I'll take a look.

**Comment by mezz** [comment] 2016-10-31 02:03
Looks like this is a JEI issue, V-Tweaks is not doing anything wrong.

**Comment by mezz** [comment] 2016-10-31 02:07
Fixed in JEI 3.13.0.338

**Closed as completed** 2016-10-31 02:06 UTC
Labels: bug

**Comment by oitsjustjose** [comment] 2016-10-31 03:31
Oh good, I was about to say "I have no idea what I've done wrong", but I see that Mezz has it all under control ;)

I was curious how HyperMending was causing a _tooltip_ crash, considering it doesn't do anything other than fancy colors via the .lang file.

**Comment by mezz** [comment] 2016-10-31 03:33
I am loading tooltips before the world exists, so handlers that expect there to be a world or a player could crash. I fixed the issue by creating a fake world and player to keep tooltip handlers happy.
