### ISSUE TITLE
Crash when Right Clicking Garlic

### ISSUE THREAD

**Issue by Fresh-Mutton** [mezz/JustEnoughItems#256] opened 2016-04-21 16:10 UTC
https://gist.github.com/Fresh-Mutton/f4f5feced1db6b10c2efc2af0efe8ba7

This happened when I right-clicked on Garlic from Pam's HarvestCraft. I know it is not all HarvestCraft items because I can right-click and see Gooseberry items just fine. The bug seems to be persistent, as every time I have tried doing this with the Garlic it crashed. It doesn't matter if the item is in my inventory or if I search for it on the side.

http://imgur.com/Aern4je

Chickencodecore wasn't supposed to be in there, but removing it didn't make a difference.

That being said, I am loving this mod so far! Can't wait for all of the kinks to be worked out.

**Comment by mezz** [comment] 2016-04-21 20:32
Thanks for the report! I was able to reproduce the crash, looking into it now.

**Comment by mezz** [comment] 2016-04-21 20:38
Very interesting! This is the recipe that's crashing JEI: http://ftb.gamepedia.com/Paneer_Tikka_Masala
It's a vanilla crafting recipe with 10 ingredients.
I will add a check for this kind of thing so that JEI logs about it and doesn't crash.

**Comment by UndeadZeratul** [comment] 2016-04-21 20:41
Actually, looks like @Xbony2 already has a [PR](https://github.com/MatrexsVigil/harvestcraft/pull/80) in place to fix that recipe, I _literally_ just closed that tab when I saw this.

**Comment by mezz** [comment] 2016-04-21 20:56
I added some better error checking, JEI will log about more recipe issues and avoid using them and crashing. I'll push the changes soon.
Here are the issues found for HarvestCraft:
https://gist.github.com/mezz/2b65c0bef5c8a6193405f909772e40d9

**Comment by mezz** [comment] 2016-04-21 21:20
Fixed by this commit https://github.com/mezz/JustEnoughItems/commit/8492f40440cd572adba520d7fce702444b953b3c

**Closed as completed by mezz** 2016-04-21 21:20 UTC
Labels: bug, other mod

**Comment by xbony2** [comment] 2016-04-22 11:16
@UndeadZeratul documenting mods [~=](https://en.wiktionary.org/wiki/~%3D) debugging mods....

**Comment by UndeadZeratul** [comment] 2016-04-22 14:31
Yeah, solving it here the way Mezz did covers other unknowns and bad recipes in the future, which is the better solution, I was just pointing out that this particular recipe was hopefully getting fixed.
