### ISSUE TITLE
Cannot search or scroll through pages (1.10.2)

### ISSUE THREAD

**Issue by iTyphlosion** [mezz/JustEnoughItems#786] opened 2017-03-28 20:29 UTC
I am using the latest released version of JEI for Minecraft 1.10.2, jei_1.10.2-3.14.7.416.jar.
I cannot search for items, or scroll through the pages of items when using this mod. I can look at recipes for the first page, but trying to scroll to pages 2, 3 or 4 are impossible, and I cannot search for a specific item because the search bar does not work.

List of mods installed:
Aetherll-1.10.2-r1-build3.jar
animania-1.10-1.0.4.1.jar
CustomMobSpawner 3.10.1.jar
DrZharks MoCreatures Mod-10.0.6.jar
MCA-1.10.2_HD_U_D7.jar
RadsixCore-1.10.2-2.1.3-universal.jar
RogelikeDungeons-1.10.2-1.5.8.jar
TreeChopper-1.10.2-1.1.2.jar
Xaeros_Minimap>1.12.4_Forge_1.10.2.jar

**Comment by mezz** [comment] 2017-03-28 23:19
Thanks for the report!
This seems to be caused by another mod, try removing mods until you no longer had this bug. From there I can help report to the mod author.

**Comment by Ommina** [comment] 2017-03-28 23:30
Aether2 has an [open git issue](https://git.gildedgames.com/GildedGames/Aether-II/issues/403) that sounds pretty much like what you're describing.  (And a subsequent comment that no, everything is fine.)

Still, that mod might be a good place to start.

**Comment by mezz** [comment] 2017-03-28 23:32
Sounds good. Considering how short this mod list is, I think it would be valuable to narrow down exactly which mods are involved here. Once you've done that, I can investigate the bug and make a stronger case if necessary.

**Comment by pau101** [comment] 2017-03-30 04:13
This was an [issue](https://git.gildedgames.com/GildedGames/Aether-II/issues/201) in Aether II that was fixed in November of last year and the latest build [AetherII-1.10.2-r1-build7.signed](https://files.gildedgames.com/minecraft/aether/downloads/indev/1.10.2-12.18.2.2098/AetherII-1.10.2-r1-build7.signed.jar) contains the fix.

**Comment by mezz** [comment] 2017-03-30 05:36
Thanks, looks like this can be closed then.

**Closed as completed** 2017-03-30 05:36 UTC
Labels: other mod

**Comment by iTyphlosion** [comment] 2017-03-31 13:22
How would I go about getting the build7.signed jar to work with my server? I've tried using that version and other signed versions to no avail.

**Comment by mezz** [comment] 2017-03-31 17:45
If there's something wrong, report it to Aether II so they can help you.
