### ISSUE TITLE
[Crash]: MixinTransformerError: An unexpected critical error was encountered

### ISSUE THREAD

**Issue by evhub** [mezz/JustEnoughItems#3599] opened 2024-07-15 08:52 UTC
### Steps to Reproduce the Crash

After updating JEI from 15.3.0.8 to 15.8.0.11, when the client joins the server, it causes a client crash.

### Mod Pack Version (Optional)

Minecraft 1.20.1
Forge 47.3.0

### Crash Report

https://gist.github.com/evhub/3587343d0f2957f89836c644517a7904

**Comment by Mysticpasta1** [comment] 2024-07-16 02:34
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Invalid descriptor on ldlib-common.mixins.json:jei.JeiRecipeLayoutMixin from mod ldlib->@Inject::injectCreate(Lmezz/jei/api/recipe/category/IRecipeCategory;Ljava/util/Collection;Ljava/lang/Object;Lmezz/jei/api/recipe/IFocusGroup;Lmezz/jei/api/runtime/IIngredientManager;Lmezz/jei/api/runtime/IIngredientVisibility;Lmezz/jei/api/helpers/IModIdHelper;Lmezz/jei/common/gui/textures/Textures;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V! Expected (Lmezz/jei/api/recipe/category/IRecipeCategory;Ljava/util/Collection;Ljava/lang/Object;Lmezz/jei/api/recipe/IFocusGroup;Lmezz/jei/api/runtime/IIngredientManager;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V but found (Lmezz/jei/api/recipe/category/IRecipeCategory;Ljava/util/Collection;Ljava/lang/Object;Lmezz/jei/api/recipe/IFocusGroup;Lmezz/jei/api/runtime/IIngredientManager;Lmezz/jei/api/runtime/IIngredientVisibility;Lmezz/jei/api/helpers/IModIdHelper;Lmezz/jei/common/gui/textures/Textures;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V [INJECT Applicator Phase -> ldlib-common.mixins.json:jei.JeiRecipeLayoutMixin from mod ldlib -> Apply Injections ->  -> Inject -> ldlib-common.mixins.json:jei.JeiRecipeLayoutMixin from mod ldlib->@Inject::injectCreate(Lmezz/jei/api/recipe/category/IRecipeCategory;Ljava/util/Collection;Ljava/lang/Object;Lmezz/jei/api/recipe/IFocusGroup;Lmezz/jei/api/runtime/IIngredientManager;Lmezz/jei/api/runtime/IIngredientVisibility;Lmezz/jei/api/helpers/IModIdHelper;Lmezz/jei/common/gui/textures/Textures;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V]

**Comment by mezz** [comment] 2024-07-16 03:31
Thanks for the report!
This is caused by LDLib, which uses mixins to change JEI's code but fails on the new version.
I opened a bug with them here: https://github.com/Low-Drag-MC/LDLib-Architectury/issues/29
LDLib is included in [GregTech CEU for 1.20.1](https://github.com/GregTechCEu/GregTech-Modern), which is a common source of the error here.

**Comment by Yefancy** [comment] 2024-07-17 03:25
As we known taht the scroll wheel would switch recpe pages, but the multiblock preview in gregtech uses the wheel to scale the scene, so ldlib injects code into jei in a very hacky way. 

Therefore, LDLib expects to have APIs that provide all the events as vanilla widgets (click drag move scroll keytype, etc). To keep original jei behaviors, you can trigger such events while mouse is staying in the layout box.

**Comment by mezz** [comment] 2024-07-17 05:37
I am looking into how JEI might support that better, I think it's worthwhile.

**Comment by mezz** [comment] 2024-07-21 11:20
This has been fixed in the latest version of LDLib. 
We will have to wait for mods like gtceu-1.20.1 to update their version of it.

**Closed as not planned** 2024-07-31 10:23 UTC
Labels: other mod
