### ISSUE TITLE
JEI Crash while rendering.

### ISSUE THREAD

**Issue by GeniusMe707** [mezz/JustEnoughItems#1566] opened 2019-04-28 21:01 UTC
Just Enough Items has been crashing for me. Luckily, I had VanillaFix which identified the issue. I had installed All The Items 3, and added VanillaFix to the modpack. Then, when I was looking for the recipe for an item, the game crashed. Here is the VanillaFix report on it as I am not very educated with these kinds of problems. https://paste.dimdev.org/ujiqehujoz.mccrash

**Comment by mezz** [comment] 2019-04-28 21:23
Thanks for the report!

This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/1462 please make any replies there.

Please make a copy of your pack and remove mods to try to narrow down which mods are causing an issue. It works fine with just JEI and Forestry, so something else must be involved. So far, nobody has tried narrowing down the issue.

**Closed as completed by mezz** 2019-04-28 21:23 UTC
Labels: duplicate
