### ISSUE TITLE
[Bug]: JEI Tool Tip Error on all items

### ISSUE THREAD

**Issue by alinlaphel** [mezz/JustEnoughItems#3473] opened 2024-03-31 06:29 UTC
### Steps to Reproduce the Bug

Simply logging into the server and checking JEI. 

### Expected Behavior

In singleplayer, the JEI seems to be working. It only stops working when hosted on a server or through the essentials mod.

### Actual Behavior

There is not crash, it just hides all the item names both in crafting recipes and item search.

### latest.log

https://github.com/alinlaphel/latest_log/blob/abdb2309a4e64ce5f88b2cf3ac3dbd244937c1df/latest.log

**Comment by katybrokenhearts** [comment] 2024-04-21 05:45
had the same  problem, only started after I changed some mods in them. version 1.20.1

**Comment by eepykate** [comment] 2024-06-09 19:09
can attest, i get this in atm9. if i search "wr" (for wrench) it seems to crash consistently (or at least twice in a row)

**Comment by eepykate** [comment] 2024-06-10 06:09
PRETTY sure i found the cause if it wasnt guessed by the above one, its not about a buggy item being shown - pressing JEI keybinds (eg a[fav],r[recipe],u[usages]) during the search seems to cause a soft-crash ala the big red error behaviour. i can copy-paste the text into the JEI search just fine!

edit: nvm that worked for like 2-3 hours (vs crashing immediately upon searching) but it still ended up crashing :<

**Comment by mezz** [comment] 2024-06-11 05:18
Thanks for the report! This happens when a modded item crashes. In previous versions of JEI it would just crash the game.
Here, JEI tried to stop the whole game from crashing but something in the system might still be really broken.
Try the latest release of JEI from today, I updated it to try to contain the damage a bit better.

**Comment by mezz** [comment] 2024-06-11 05:34
Duplicate of https://github.com/mezz/JustEnoughItems/issues/3432

**Closed as not planned by mezz** 2024-06-11 05:34 UTC
