### ISSUE TITLE
Mouse-over hotkeys take precedent over typing in search 

### ISSUE THREAD

**Issue by Rosethorns** [mezz/JustEnoughItems#2082] opened 2020-09-05 19:23 UTC
**Issue:** 
When typing in a search request if the player moves the mouse over an item in the item list JEI will not lock the mouse-over hotkeys. This results in the A key adding to bookmarks, the R key looking for recipes to make the item with, and U looking for uses for the item.

**Expected Result:**
With the search bar focused, mouse-over hotkeys should lock and become unusable until the search bar becomes unfocused.

**Steps to reproduce:**
1. Click the search bar to focus it
2. Move the mouse over an item in the item list
3. Start typing anything that uses a JEI mouse over hot-key (ex: A, R, U)

**Versions:**
Minecraft: 1.16.1
Forge: 32.0.108
JEI: 7.0.1.9

**Comment by mezz** [comment] 2020-09-27 00:18
Thanks for the report!
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/1897 and has been fixed 👍

**Closed as completed by mezz** 2020-09-27 00:18 UTC
Labels: duplicate
