### ISSUE TITLE
Minecraft crashes after entering world, jei is problem in crash log JEI ver 6.0.0.8(1.14.3) on 1.14.4

### ISSUE THREAD

**Issue by Shadder-1-5** [mezz/JustEnoughItems#1662] opened 2019-08-08 05:14 UTC
I am trying to use jei in 1.14.4 and when i join a world or gen one it gets to saving world than MC crashes, the crash logs suspect JEI

heres crash log

[crash-2019-08-07_22.13.27-client.txt](https://github.com/mezz/JustEnoughItems/files/3479941/crash-2019-08-07_22.13.27-client.txt)

**Comment by mezz** [comment] 2019-08-08 05:22
Thanks for the report!
This is fixed in the latest version.
Duplicate of #1641

**Closed as completed by mezz** 2019-08-08 05:22 UTC
Labels: duplicate
