### ISSUE TITLE
jei_1.11-4.0.1.190 : cannot start  game : Error from Technic Launcher Console

### ISSUE THREAD

**Issue by Trounk** [mezz/JustEnoughItems#637] opened 2016-11-23 12:07 UTC
Hello,
I hope this will help to improve the last mod file : here is what we can read in the Technic Launcher Console when trying to use the jast JEI .jar : 

[B#347]  [12:59:43] [Server thread/ERROR] [FML]: The following problems were captured during this phase
[B#347]  [12:59:43] [Server thread/ERROR] [FML]: Caught exception from Just Enough Items (jei)
[B#347]  java.lang.NoSuchMethodError: net.minecraftforge.oredict.ShapelessOreRecipe.getInput()Ljava/util/ArrayList;
[B#347]  	at mezz.jei.plugins.vanilla.crafting.ShapelessOreRecipeHandler.isRecipeValid(ShapelessOreRecipeHandler.java:43) ~[ShapelessOreRecipeHandler.class:?]
[B#347]  	at mezz.jei.plugins.vanilla.crafting.ShapelessOreRecipeHandler.isRecipeValid(ShapelessOreRecipeHandler.java:13) ~[ShapelessOreRecipeHandler.class:?]
[B#347]  	at mezz.jei.RecipeRegistry.addRecipe(RecipeRegistry.java:206) ~[RecipeRegistry.class:?]
[B#347]  	at mezz.jei.RecipeRegistry.addRecipe(RecipeRegistry.java:183) ~[RecipeRegistry.class:?]
[B#347]  	at mezz.jei.RecipeRegistry.addRecipes(RecipeRegistry.java:160) ~[RecipeRegistry.class:?]
[B#347]  	at mezz.jei.RecipeRegistry.<init>(RecipeRegistry.java:86) ~[RecipeRegistry.class:?]
[B#347]  	at mezz.jei.util.ModRegistry.createRecipeRegistry(ModRegistry.java:195) ~[ModRegistry.class:?]
[B#347]  	at mezz.jei.JeiStarter.start(JeiStarter.java:48) ~[JeiStarter.class:?]
[B#347]  	at mezz.jei.ProxyCommonClient.loadComplete(ProxyCommonClient.java:111) ~[ProxyCommonClient.class:?]
[B#347]  	at mezz.jei.JustEnoughItems.loadComplete(JustEnoughItems.java:53) ~[JustEnoughItems.class:?]
[B#347]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
[B#347]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
[B#347]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
[B#347]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
[B#347]  	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600) ~[modpack.jar:?]
[B#347]  	at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source) ~[?:?]
[B#347]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
[B#347]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
[B#347]  	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
[B#347]  	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
[B#347]  	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
[B#347]  	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
[B#347]  	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
[B#347]  	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243) ~[LoadController.class:?]
[B#347]  	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221) ~[LoadController.class:?]
[B#347]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
[B#347]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
[B#347]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
[B#347]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
[B#347]  	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
[B#347]  	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
[B#347]  	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
[B#347]  	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
[B#347]  	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
[B#347]  	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145) ~[LoadController.class:?]
[B#347]  	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:803) ~[Loader.class:?]
[B#347]  	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:330) ~[FMLClientHandler.class:?]
[B#347]  	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:519) ~[beq.class:?]
[B#347]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:350) ~[beq.class:?]
[B#347]  	at net.minecraft.client.main.Main.main(SourceFile:124) ~[minecraft.jar:?]
[B#347]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
[B#347]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
[B#347]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
[B#347]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
[B#347]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) ~[launchwrapper-1.12.jar:?]
[B#347]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) ~[launchwrapper-1.12.jar:?]
[B#347]  [12:59:43] [Server thread/ERROR] [FML]: A fatal exception occurred during the server about to start event
[B#347]  net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)
[B#347]  
[B#347]  Caused by: java.lang.NoSuchMethodError: net.minecraftforge.oredict.ShapelessOreRecipe.getInput()Ljava/util/ArrayList;
[B#347]  	at mezz.jei.plugins.vanilla.crafting.ShapelessOreRecipeHandler.isRecipeValid(ShapelessOreRecipeHandler.java:43) ~[ShapelessOreRecipeHandler.class:?]
[B#347]  	at mezz.jei.plugins.vanilla.crafting.ShapelessOreRecipeHandler.isRecipeValid(ShapelessOreRecipeHandler.java:13) ~[ShapelessOreRecipeHandler.class:?]
[B#347]  	at mezz.jei.RecipeRegistry.addRecipe(RecipeRegistry.java:206) ~[RecipeRegistry.class:?]
[B#347]  	at mezz.jei.RecipeRegistry.addRecipe(RecipeRegistry.java:183) ~[RecipeRegistry.class:?]
[B#347]  	at mezz.jei.RecipeRegistry.addRecipes(RecipeRegistry.java:160) ~[RecipeRegistry.class:?]
[B#347]  	at mezz.jei.RecipeRegistry.<init>(RecipeRegistry.java:86) ~[RecipeRegistry.class:?]
[B#347]  	at mezz.jei.util.ModRegistry.createRecipeRegistry(ModRegistry.java:195) ~[ModRegistry.class:?]
[B#347]  	at mezz.jei.JeiStarter.start(JeiStarter.java:48) ~[JeiStarter.class:?]
[B#347]  	at mezz.jei.ProxyCommonClient.loadComplete(ProxyCommonClient.java:111) ~[ProxyCommonClient.class:?]
[B#347]  	at mezz.jei.JustEnoughItems.loadComplete(JustEnoughItems.java:53) ~[JustEnoughItems.class:?]
[B#347]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
[B#347]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
[B#347]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
[B#347]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
[B#347]  	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600) ~[modpack.jar:?]
[B#347]  	at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source) ~[?:?]
[B#347]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
[B#347]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
[B#347]  	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
[B#347]  	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
[B#347]  	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
[B#347]  	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
[B#347]  	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
[B#347]  	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243) ~[LoadController.class:?]
[B#347]  	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221) ~[LoadController.class:?]
[B#347]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
[B#347]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
[B#347]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
[B#347]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
[B#347]  	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
[B#347]  	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
[B#347]  	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
[B#347]  	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
[B#347]  	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
[B#347]  	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145) ~[LoadController.class:?]
[B#347]  	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:803) ~[Loader.class:?]
[B#347]  	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:330) ~[FMLClientHandler.class:?]
[B#347]  	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:519) ~[beq.class:?]
[B#347]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:350) ~[beq.class:?]
[B#347]  	at net.minecraft.client.main.Main.main(SourceFile:124) ~[minecraft.jar:?]
[B#347]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
[B#347]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
[B#347]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
[B#347]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
[B#347]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) ~[launchwrapper-1.12.jar:?]
[B#347]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) ~[launchwrapper-1.12.jar:?]
[B#347]  [12:59:43] [Server thread/INFO]: Stopping server
[B#347]  [12:59:43] [Server thread/INFO]: Saving players
[B#347]  [12:59:43] [Server thread/INFO]: Saving worlds
[B#347]  [12:59:43] [Server thread/INFO] [FML]: Applying holder lookups
[B#347]  [12:59:43] [Server thread/INFO] [FML]: Holder lookups applied
[B#347]  [12:59:43] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded.
[B#347]  [12:59:43] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded.

**Comment by mezz** [comment] 2016-11-23 17:17
Thanks for the report!
This is a duplicate of #626, update to the latest version.

**Closed as completed by mezz** 2016-11-23 17:17 UTC
Labels: duplicate
