### ISSUE TITLE
Weird crash with Useful Backpacks

### ISSUE THREAD

**Issue by clonetrooper277** [mezz/JustEnoughItems#1680] opened 2019-08-16 07:34 UTC
I get a weird crash when I open my inventory while I use Useful Backpacks and JEI together. I recently updated Forge to 1.14.4 28.0.49 and now the two won't work together. I remove JEI and no crashes happen.
JEI version 1.14.4-6.0.0.10 is used

Crash log: https://gist.github.com/clonetrooper277/189041d7a6be029a158a90c5d8e63af9

**Comment by HyCraftHD** [comment] 2019-08-16 07:36
Seems like this method was made private and jei tries to call it:
Class: net.minecraft.client.renderer.ItemRenderer
``` java
   private void renderModel(IBakedModel model, ItemStack stack) {
      this.renderModel(model, -1, stack);
   }
```

**Comment by mezz** [comment] 2019-08-19 01:38
Thanks for the report!

I use an access transformer here to make that method public:
https://github.com/mezz/JustEnoughItems/blob/dc300405b6a4ba0d9f4493933961766b4adcf5c5/src/main/resources/META-INF/accesstransformer.cfg#L3

@HyCraftHD Does Useful Backpacks change that method using ASM or anything else? I am not sure why this would be affected by your mod.

**Comment by HyCraftHD** [comment] 2019-08-19 08:10
Thanks for the reply!
Definitely not. The library mod is using an [access transformer](https://github.com/MC-U-Team/U-Team-Core/blob/1.14.4/src/main/resources/META-INF/accesstransformer.cfg) but neither usefulbackpacks nor uteamcore is accessing anything related to rendering.

**Comment by mezz** [comment] 2019-08-21 04:22
Ah I didn't realize before, but this is actually a duplicate of https://github.com/mezz/JustEnoughItems/issues/1668
This is not caused by Useful Backpacks at all, it is caused by Optifine.
Please follow the Optifine issue here: sp614x/optifine#2748

**Closed as completed by mezz** 2019-08-21 04:22 UTC
Labels: duplicate

**Comment by HyCraftHD** [comment] 2019-08-22 08:22
Perfect, thank you alot!
