### ISSUE TITLE
No recipe for Firework Rocket

### ISSUE THREAD

**Issue by CKTheUltimate** [mezz/JustEnoughItems#490] opened 2016-10-03 16:01 UTC
As the title says,there is no recipe for Firework Rocket.It can be crafted in vanilla Minecraft with paper and gun powder,it is not listed in the creative inventory as it has too many possible combinations.But please add the basic one without any effects to the recipes,some mods requires Firework Rocket but not a lot players know how to craft it.

**Comment by GirafiStudios** [comment] 2016-10-03 17:43
Kinda duplicate of https://github.com/mezz/JustEnoughItems/issues/91?
I'm sure Mezz will get around to it eventually, there is just more important issues to resolve currently :)

**Comment by mezz** [comment] 2016-10-03 22:57
Thanks for the report!
Yeah, this is a duplicate. I will add them eventually, but it has not been a high priority compared to bugs and big API features recently.

**Closed as completed by mezz** 2016-10-03 22:57 UTC
Labels: duplicate
