### ISSUE TITLE
Items not showing in inventory

### ISSUE THREAD

**Issue by auboli77** [mezz/JustEnoughItems#287] opened 2016-05-24 22:10 UTC
If hotbar is full and you try to cheat in another item it will not show in your inventory immediately.

https://youtu.be/kMm2jJTXM-Q

Using:
Forge 1.9.4-12.17.0.1917
JEI 1.9.4-3.4.0.204

**Comment by Prospector** [comment] 2016-05-24 22:13
Dupe of #186

**Closed as completed** 2016-05-24 22:16 UTC
Labels: duplicate

**Comment by mezz** [comment] 2016-05-24 22:18
Thanks for the report!
JEI uses vanilla minecraft's `/give` command, so unfortunately this is a minecraft bug.
I may make my own command to use instead, but the issues seen so far are pretty minor.

**Comment by Prospector** [comment] 2016-05-24 22:26
Kinda funny how the original issue was 101 issues ago. So close to 100 issues ago lol
