### ISSUE TITLE
crash on load

### ISSUE THREAD

**Issue by bdudek** [mezz/JustEnoughItems#495] opened 2016-10-03 23:39 UTC
Crashiong on load, loads fine with out JEI

crash report: http://pastebin.com/4Ym0tAWa

forge 12.18.1.2088
JEI: 3.12.4.294

**Comment by TehNut** [comment] 2016-10-04 00:00
Caused by More Overlays.

**Comment by mezz** [comment] 2016-10-04 00:06
Thanks for the report!
This is a duplicate of #456
Update More Overlays to fix the issue.

**Closed as completed** 2016-10-04 00:07 UTC
Labels: duplicate

**Comment by bdudek** [comment] 2016-10-04 00:09
thank you removing it fixed it

**Comment by Gengi0927** [comment] 2016-10-13 08:10
Hi, i'm having problems with JEI, if i attempt to load Minecraft, my game crashes before i get to the title screen, if there is any way you could help it would be much appreciated, thanks!

**Comment by mezz** [comment] 2016-10-13 08:11
Please make a new issue @Gengi0927, don't reply here on an unrelated issue.
