### ISSUE TITLE
[Bug]: JEI doesn't show liquid amount nor drop chance for recipes in all 15.10.* versions

### ISSUE THREAD

**Issue by Callisto95** [mezz/JustEnoughItems#3670] opened 2024-08-07 08:43 UTC
### Steps to Reproduce the Bug

1. Check any recipe with a chanced drop or which creates a liquid

### Expected Behavior

The liquid amount / drop chance is shown (just like in 15.8.2.26)

### Actual Behavior

Nothing (except the other item information) is shown.

### Extra Notes (Optional)

I'm using Create (Fabric) 0.5.1-f.
The version numbers are from Modrinth.
This is for Minecraft 1.20.1

### latest.log

https://gist.github.com/UnknownUser95/498c7815b3c0d01f989b344b834d3f56

**Comment by Doming3000** [comment] 2024-08-11 04:10
Same problem with Create, also fabric.

**Comment by EvlCreeperReaper** [comment] 2024-08-11 15:45
May be unrelated, but I had this issue in the Forge version as well until I updated to 15.12.2.47 today, and it _seems_ to be mostly fixed. It might still not be on Fabric, but I'm on the same game version (Minecraft 1.20.1, Fabric 0.5.1-f).

That being said, liquid amounts (and potion level) seem to still not show on any potions with Create recipes (automated brewing, filling by spout, etc.). For example: the recipe to spout potion of strength on top of cinder flour to make redstone displays as "Potion of Strength\nPotion of Strength":
![image_no_amount](https://github.com/user-attachments/assets/d54dbe22-d97d-4223-b994-cf4c4d05b3a9)

**Comment by Luningor** [comment] 2024-08-11 16:28
Same problem with Create and Immersiveengineering, Forge

**Comment by Blackalf** [comment] 2024-08-12 14:51
Same issue with Masterful Machinery for Forge 1.20.1
Would work on 15.8.2.26 and lower as well

**Comment by mezz** [comment] 2024-08-14 00:52
Thanks for the report!
I broke something with tooltips, and it is fixed in the latest version.
Please try out the latest version of JEI and let me know if the issue is resolved for you.

**Comment by Callisto95** [comment] 2024-08-14 08:04
No problem for the report.

Version 15.12.2.51 (the latest available) doesn't solve it.

![image](https://github.com/user-attachments/assets/38d315d4-c506-43b2-a653-2c1c4014bce3)

It shows more in case of the potion, but the liquid amount is still missing.

![image](https://github.com/user-attachments/assets/c98c973b-d12f-42f4-9920-d125804da308)

Crushing also still has no chance.

**Comment by mezz** [comment] 2024-08-14 08:30
Thanks for checking!

This is the same underlying issue as https://github.com/mezz/JustEnoughItems/issues/3683

This bug has been resolved in JEI `15.12.2.52`

**Closed as completed by mezz** 2024-08-14 08:30 UTC
Labels: bug

**Comment by Callisto95** [comment] 2024-08-14 08:33
Yep, that fixes this.
Thanks for your efforts!
