### ISSUE TITLE
[1.16.1][forge] missing jei, not loaded until multiple relogs

### ISSUE THREAD

**Issue by Prophious** [mezz/JustEnoughItems#2104] opened 2020-09-30 22:48 UTC
i have an issue on a forge server with 140+ mods where jei does not load for clients at first but after a few relogs in to the server the issue is no longer there i can use jei just fine 

i assume is that it is client side that the mod errors (if that's what it is) when you have booted up a fresh minecraft game and join in to a server, but like i said it kinda corrects its self after like 3-7 relogs, and will continue to work until you close out minecraft all the way, then you would have to do the same thing again

i have nothing more then words right now, i can get you the who list of mods in there

optifne is used and the compat optiforge is there too, does not appear to be any sort of rendering issue

**Comment by mezz** [comment] 2020-10-03 21:40
Thanks for the report!
I think this is a duplicate of https://github.com/mezz/JustEnoughItems/issues/2101
Can you help with the investigation there? We need to narrow down the list of mods to find out which ones are conflicting.
I'll close this issue so we can keep everything together in the other one.

**Closed as completed by mezz** 2020-10-03 21:40 UTC
Labels: duplicate
