### ISSUE TITLE
JEI Crashing with latest version.

### ISSUE THREAD

**Issue by MagmaSlime123** [mezz/JustEnoughItems#1693] opened 2019-08-21 13:59 UTC
JEI crashes upon opening your inventory. Only occurs in Fullscreen.

Using the latest version of Forge for 1.14.4.

Mods:
![image](https://user-images.githubusercontent.com/51277766/63438245-d67b3480-c3e0-11e9-81c9-0b88ac786247.png)

Attempting to use on a 1.14.4 Forge server.

![image](https://user-images.githubusercontent.com/51277766/63438767-bbf58b00-c3e1-11e9-802c-cbc94c64109b.png)

[crash-2019-08-21_07.02.39-client.txt](https://github.com/mezz/JustEnoughItems/files/3525701/crash-2019-08-21_07.02.39-client.txt)

**Comment by mezz** [comment] 2019-08-26 00:39
Thanks for the report!
This is a duplicate of #1668
Please follow the Optifine issue here: sp614x/optifine#2748

**Closed as completed by mezz** 2019-08-26 00:39 UTC
Labels: duplicate
