### ISSUE TITLE
[1.9.4] jei_1.9.4-3.6.0.210 "+" button broke for servers

### ISSUE THREAD

**Issue by Xiaminou** [mezz/JustEnoughItems#308] opened 2016-06-08 22:06 UTC
The "+" button when looking up recipes in a crafting table is no longer working on servers.
1. Join a server
2. Try to craft stone bricks in a crafting table using "+"

**Comment by Prospector** [comment] 2016-06-08 22:07
You need it installed on the serverside for that feature.

**Comment by Xiaminou** [comment] 2016-06-08 22:14
I have... it stopped working after I updated JEI to the version mentioned above.
I then tested it in SSP, unable to reproduce, and install JEI alone on server and client and it reproduced.

**Comment by mezz** [comment] 2016-06-08 22:25
So what's step 3? What happens?

**Comment by Xiaminou** [comment] 2016-06-08 22:45
nothing, it's broken, it doesn't work.
it should place 4 stones in the crafting table but it doesn't.

**Comment by mezz** [comment] 2016-06-08 22:48
Sorry saying it doesn't work is not helpful, I don't know what you mean because it works fine for me.

Can you click the button?
Is the button there?
Does it do nothing?
Does it change the screen to the crafting table, but not put the items there?
Does an error show up in your log when you click it?
When you click it, does it throw you into lava?

"broken" can mean anything :/ please be specific so I can help.

**Comment by TehNut** [comment] 2016-06-08 22:53
Are you sure that the mod is actually being registered on the server?

**Comment by Xiaminou** [comment] 2016-06-08 22:55
I can click the button,
it puts me on the crafting table screen but doesn't put the items,
here is the log: 
Client: https://drive.google.com/open?id=0BxQWn9jKBIAJaWw0Wi05eE5ESUE
Server: https://drive.google.com/open?id=0BxQWn9jKBIAJVFBMM3JqczBOS1E
Video of what happens: https://youtu.be/to2A_u3B7iA

**Comment by mezz** [comment] 2016-06-08 22:59
Thanks!

**Comment by mezz** [comment] 2016-06-08 23:36
I think it is a bad interaction with another mod. 
Can you try without InventoryTweaks? If that is not the issue can you try with only JEI?

**Comment by Xiaminou** [comment] 2016-06-09 00:36
same bug with only JEI.

**Comment by TehNut** [comment] 2016-06-09 01:02
@mezz I can reproduce with just JEI. [Here](http://paste.ubuntu.com/17134151/) is the resulting stacktrace. (no crash)

https://gfycat.com/LinedAccomplishedKinkajou

**Comment by mezz** [comment] 2016-06-09 01:20
Thanks everyone, fixed in the latest release. Should be up in a few minutes.

**Closed as completed** 2016-06-09 01:20 UTC
Labels: bug, recipe transfer
