### ISSUE TITLE
1.13.2 JEI is loaded too many times on reload.

### ISSUE THREAD

**Issue by Darkhax** [mezz/JustEnoughItems#1558] opened 2019-04-17 22:24 UTC
JEI: 5.0.0.20
Forge: 25.0.145

When running the `/reload` command JEI seems to rebuild it's data twice. I don't think this was intended. 

```
[16:17:23.823] [Client thread/INFO] [me.je.st.ClientLifecycleHandler/]: Restarting JEI.
[16:17:23.823] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Starting JEI...
[16:17:23.920] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Building ingredient list...
[16:17:23.921] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Building ingredient list took 1.434 ms
[16:17:23.921] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Building ingredient filter...
[16:17:24.136] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Building ingredient filter took 214.9 ms
[16:17:24.136] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Building bookmarks...
[16:17:24.136] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Building bookmarks took 92.84 ?s
[16:17:24.137] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Building recipe registry...
[16:17:24.157] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Building recipe registry took 20.11 ms
[16:17:24.157] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Building runtime...
[16:17:24.159] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Building runtime took 964.0 ?s
[16:17:24.166] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Starting JEI took 343.0 ms
[16:17:24.166] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Starting JEI...
[16:17:24.233] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Building ingredient list...
[16:17:24.234] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Building ingredient list took 1.208 ms
[16:17:24.234] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Building ingredient filter...
[16:17:24.378] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Building ingredient filter took 143.6 ms
[16:17:24.379] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Building bookmarks...
[16:17:24.379] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Building bookmarks took 91.26 ?s
[16:17:24.379] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Building recipe registry...
[16:17:24.396] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Building recipe registry took 16.51 ms
[16:17:24.396] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Building runtime...
[16:17:24.396] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Building runtime took 235.5 ?s
[16:17:24.398] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Starting JEI took 231.1 ms
```

**Comment by Darkhax** [comment] 2019-04-17 22:56
Update to this issue, may be a separate issue. It looks like every time I do `F3 + T` JEI is reloaded an additional time. The number of additional reloads is cumulative, meaning that if it loads twice, on the next reload it loads three times, and then four, and so on.

**Comment by LlubNek** [comment] 2019-04-18 21:47
I think something similar may be being triggered during startup with some mods (I'm having trouble tracking down which).

Forge loading screen said it was in ProxyCommonClient$$Lambda$6195/469931469 for maybe an hour before it crashed.

Here are some crash reports from when Minecraft eventually ran out of memory and a log.
[crash-2019-04-18_16.24.43-client.txt](https://github.com/mezz/JustEnoughItems/files/3096266/crash-2019-04-18_16.24.43-client.txt)
[crash-2019-04-18_16.25.06-client.txt](https://github.com/mezz/JustEnoughItems/files/3096267/crash-2019-04-18_16.25.06-client.txt)
[latest.log](https://github.com/mezz/JustEnoughItems/files/3096271/latest.log)

**Comment by mezz** [comment] 2019-04-21 19:25
Thanks for the report!
I'm probably just adding a reload listener every time or something like that. 
I didn't test the reloading feature much yet.

**Comment by Speiger** [comment] 2019-09-16 14:38
@mezz This is because the ServerResourceReloader sends a SUpdateRecipesPacket to all clients when it reloads the Recipes.
And your JEI loader thinks that it actually is only thrown once per player.
(PlayerList.reloadResources()) That fires the RecipesUpdatedEvent.

Edit. Also the current way the JEI loader is implemented it does not allow to add custom server synced recipes, unless they use the Vanilla Recipe<?> class. Or they don't sync the recipes at all.

Edit: Also confirmed for 1.14.4 and newer mc versions

**Comment by mezz** [comment] 2021-10-12 00:47
This should be resolved in the latest versions.

**Closed as completed by mezz** 2021-10-12 00:47 UTC
Labels: bug
