### ISSUE TITLE
Cheat mode and looking at recipes

### ISSUE THREAD

**Issue by ManMan36** [mezz/JustEnoughItems#424] opened 2016-09-11 00:17 UTC
Could you guys please make it an option so that if I have cheat mode on, and I am already looking up a recipe, to, upon left/right click of an item in the panel, to look up its recipe rather than cheat it in?

**Comment by mezz** [comment] 2016-09-11 02:45
Thanks.
This is a duplicate of #301. I'll look into it soon.

**Closed as completed by mezz** 2016-09-11 02:45 UTC
Labels: duplicate
