### ISSUE TITLE
[Bug]: Search bar not centered 

### ISSUE THREAD

**Issue by emanuele246gi** [mezz/JustEnoughItems#3055] opened 2022-11-25 17:51 UTC
### Steps to Reproduce the Bug

Edit in the config the section
#Display search bar in the center
	CenterSearch = false
to 
#Display search bar in the center
	CenterSearch = true

### Expected Behavior

The search bar should appear in the center of the inventory GUI, as always intended.

### Actual Behavior

The search bar keeps the same lateral position, under the JEI.

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/civilizationpack

### Mod Pack Version (Optional)

CivilizationPack Beta v3.0.31 - Minecraft 1.18.2

### Extra Notes (Optional)

You should see the version of the mod and the edited config file in the modpack, obviously.

**Comment by mezz** [comment] 2023-01-19 02:16
Closing as a duplicate of https://github.com/mezz/JustEnoughItems/issues/3082

**Closed as not planned by mezz** 2023-01-19 02:16 UTC
