### ISSUE TITLE
[request] hiding tabs

### ISSUE THREAD

**Issue by stohun01** [mezz/JustEnoughItems#1270] opened 2018-06-20 18:38 UTC
I'd like the option to hide/disable certain tabs. Specifically for the Anvil and Brewing Stand.

**Comment by TheDeviantCrafter** [comment] 2018-08-01 04:32
I'd like this to be a feature as well. There are several machines in my pack that I removed, but the recipes still appear in JEI. The mod doesn't have a config to disable JEI tabs, so I'd have to individually remove about 200 hundred recipes.

**Comment by Freebi85** [comment] 2018-08-23 07:08
I too would benefit from a Tab Removal System. Certain tabs are actually pointless or simply confusing.
Sometimes important crafting steps are made more difficult.

**Comment by TheDeviantCrafter** [comment] 2018-09-11 05:37
@mezz Any word on this?

I've been talking in the Pack Makers Discord, and quite a few pack developers want a feature like this. There is currently no good way of mass-removing recipes, and removing the machine itself but not the recipes is still confusing to players.

**Comment by mezz** [comment] 2018-09-27 05:08
Thanks for the suggestion!
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/1164, please keep discussion in one place.
It is something I will consider, but I have not had much free time to work on new JEI features, especially with 1.13 coming.

**Closed as completed by mezz** 2018-09-27 05:08 UTC
Labels: enhancement
