### ISSUE TITLE
[Crash]: Updating screen events

### ISSUE THREAD

**Issue by Whyaremax** [mezz/JustEnoughItems#3743] opened 2024-09-06 04:13 UTC
### Steps to Reproduce the Crash

Load a texture pack in game (1.12.2) with ic2, it would cost the crash and return java.lang.ClassCastException: ic2.jeiIntegration.recipe.crafting.AdvShapelessRecipeWrapper cannot be cast to mezz.jei.api.recipe.wrapper.ICraftingRecipeWrapper

### Mod Pack Version (Optional)

1.12.2

### Crash Report

https://gist.github.com/Whyaremax/28f8da5e4db6dd9a1eb5d3dcdd9411b6

**Comment by Whyaremax** [comment] 2024-09-06 04:15
Should I report this to IC2 or something?

**Comment by mezz** [comment] 2024-09-09 03:01
Thanks for the report!
This issue is caused by `vfyjxf.jeiutilities`, please report to them here: https://github.com/vfyjxf/JEI-Utilities/issues
and link back to this issue in case they would like assistance with resolving the problem.

**Closed as not planned by mezz** 2024-09-09 03:01 UTC
Labels: other mod
