### ISSUE TITLE
1.10.2 Missing Inventory and Console Spam

### ISSUE THREAD

**Issue by MokahTGS** [mezz/JustEnoughItems#397] opened 2016-08-17 00:24 UTC
JEI 3.9.0.244
Forge .2064

No crash but when I open my inventory it's all blank and the console spams errors until it stops logging.

**Comment by mezz** [comment] 2016-08-17 00:47
Thanks for the report!
Can you paste your log to gist.github.com and link it here?

**Comment by MokahTGS** [comment] 2016-08-17 02:14
https://dl.dropboxusercontent.com/u/9882100/Minecraft/latest.zip

Too big for pastebins...

**Comment by mezz** [comment] 2016-08-17 02:17
Thanks!
gist.github.com allows extremely large pastes.
This is a duplicate of #387, you can fix it by updating AppleCore to the latest version.

**Closed as completed by mezz** 2016-08-17 02:17 UTC
Labels: duplicate
