### ISSUE TITLE
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)

### ISSUE THREAD

**Issue by Kartoffelbrot** [mezz/JustEnoughItems#1149] opened 2018-02-22 19:11 UTC
hi,
 could you help me theres a issue when i want to start/play minecraft with your:

It seems that you are using a not supported, modified version of the game ( translated from german-what does it means?i bought mc from mojang its not cracked and i downloaded the mod right here.

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail

Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)

**Comment by mezz** [comment] 2018-02-24 05:21
This seems to be a duplicate of https://github.com/mezz/JustEnoughItems/issues/1147, let's discuss there.

**Closed as completed by mezz** 2018-02-24 05:21 UTC
Labels: duplicate
