### ISSUE TITLE
JEI is still crashing my game

### ISSUE THREAD

**Issue by djdomo888** [mezz/JustEnoughItems#1550] opened 2019-04-11 20:55 UTC
Every time I try to start up Minecraft with forge, JEI keeps crashing my game (crash report attached). How do I fix this because I would really like to take advantage of this mod.

The game crashed whilst initializing game
The game crashed whilst initializing game
Error: java.lang.IllegalAccessError: tried to access field net.minecraft.client.renderer.texture.TextureMap.field_195427_i from class mezz.jei.gui.textures.JeiTextureMap

**Comment by mezz** [comment] 2019-04-13 20:35
Thanks for the report!
To get this to work, you will need to update JEI and Forge to the latest versions. It is a known bug in older versions of Forge.

**Comment by mezz** [comment] 2019-04-13 20:35
Duplicate of https://github.com/mezz/JustEnoughItems/issues/1512

**Closed as completed by mezz** 2019-04-13 20:35 UTC
