### ISSUE TITLE
Filtering suggestion

### ISSUE THREAD

**Issue by kotasd** [mezz/JustEnoughItems#506] opened 2016-10-07 06:35 UTC
Please include ability to filter all but one of an item (hide the hundreds of slabs and stairs but retain one)
Can you please add an NEI style mod filter pull down list as well? (sometimes I want to see only 3 mods for example)

btw great job, I much prefer this to NEI though the absence of the pull down list can be frustrating sometimes.

**Comment by VT-14** [comment] 2016-10-07 16:12
The | character (capital )is an "or", and space is an "and".  If you wanted to see all slab and stair recipes, search "stair|slab" to say to show anything that includes the word stair or slab.  To search for multiple mods, use:
`@modA|@modB|@modC`

**Comment by kotasd** [comment] 2016-10-08 03:33
The stair/slab request was to hide all but one of an item that is show one stair and hide all the rest, similar to what inpurecore did.  While the | character works, the pull-down was convenient.  Since the functionality already exists adding a gui for it would be nice, albeit low priority.

**Comment by TehNut** [comment] 2016-10-08 03:37
Click the wrench at the bottom right and toggle on "Item Hiding Mode" or whatever it's called. You can then hide items from JEI by clicking on them. When you toggle out, they will not display.

**Comment by VT-14** [comment] 2016-10-08 03:56
I guess picking Stars and Slabs was a bad example. :P 

I knew your first request was to remove items, but I didn't know how to do that, so I didn't say anything about it.  However, I did know how to show multiple things at once (your second request). I explained how that work, and picked 2 common items that might be searched for at the same time not thinking 'this could be interpreted as me misreading/misunderstanding the initial request.'

I think Mezz has said in the past that he wants to keep JEI's GUI clean.  You will probably need to find an add-on to implement a dropdown menu.

**Comment by mezz** [comment] 2016-10-13 08:45
Thanks for the feedback!

I think your first request is a duplicate of this one: https://github.com/mezz/JustEnoughItems/issues/195

Second is a duplicate of this one: https://github.com/mezz/JustEnoughItems/issues/163
I haven't decided if I want to add the mod list, or how I would implement it.

**Closed as completed** 2016-10-18 01:53 UTC
Labels: duplicate
