### ISSUE TITLE
[Crash]: JEI and Crafting Station

### ISSUE THREAD

**Issue by hakanct** [mezz/JustEnoughItems#3778] opened 2024-09-26 05:47 UTC
### Steps to Reproduce the Crash

1. Open the crafting station
2. Search for an item in Jei search bar
3. Try to close gui with ESC button on your keyboard and taa-daa game crashes

The game crashed whilst keypressed event handler
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.Container.m_6643_()" because "container" is null

Text above is crash instance on minecraft launcher.

Suspected Mods: 
	Just Enough Items (jei), Version: 15.18.0.79
		Issue tracker URL: https://github.com/mezz/JustEnoughItems/issues?q=is%3Aissue
		at TRANSFORMER/jei@15.18.0.79/mezz.jei.gui.recipes.RecipesGui.m_7379_(RecipesGui.java:453)

	Crafting Station (craftingstation), Version: 1.20.1-1.2.2
		Issue tracker URL: https://github.com/Tfarcenim/crafting-station/issues
		at TRANSFORMER/craftingstation@1.20.1-1.2.2/tfar.craftingstation.client.CraftingStationScreen.m_7856_(CraftingStationScreen.java:54)

And this one is a part of crash report

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/all-the-mods-9-to-the-sky

### Mod Pack Version (Optional)

1.1.2

### Extra Notes (Optional)

This crash only happens when i am searching while crafting station gui is open.

### Crash Report

https://gist.github.com/hakancqn/aa9ee373a53788db09bc219b360ff14e

**Comment by mezz** [comment] 2024-09-26 23:01
Thanks for the report!
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/3773
This appears to be an issue from `tfar.craftingstation`, please report to them and link back to the main JEI issue in case they would like my help: [Fureniku/crafting-station](https://github.com/Fureniku/crafting-station)

**Closed as not planned by mezz** 2024-09-26 23:01 UTC
Labels: duplicate
