### ISSUE TITLE
[Other]: Error load tooltip, see logs

### ISSUE THREAD

**Issue by Chussya** [mezz/JustEnoughItems#3515] opened 2024-05-23 20:37 UTC
### Other

Hello! I can see recipes, but i can't see tooltips. Does it means, that I should deleting this mod (or, ofc, I can write developers, but we know how it works and they nothing to do with this issue=) )
[latest.log](https://github.com/mezz/JustEnoughItems/files/15422338/latest.log)
As i see, EG:

> [23:12:01] [Render thread/INFO]: Skipping loading recipe epicsamurai:dye_ars_nouveau_helmet as it's serializer returned null
[23:12:01] [Render thread/ERROR]: Parsing error loading recipe epicsamurai:mask_quartz_samurai_helmet

It means, that I should remove EpicSamurai mod from list of mods. Am I right?

**Comment by mezz** [comment] 2024-06-11 05:36
Thanks for the report! Please try the latest release of JEI from today, I updated it to try to contain the damage from broken tooltips a bit better.

The logs will show a crash with a stack trace, along with information about the mod that has crashed.
In your log, that info is here:
```
[23:12:12] [Render thread/ERROR]: Caught an error rendering an Ingredient's tooltip:

-- Ingredient --
Details:
	Name: Bedrock Sword
	Mod's Name: DivineRPG
	Registry Name: divinerpg:bedrock_sword
	Class Name: class net.minecraft.world.item.ItemStack
	toString Name: 1 bedrock_sword
	Unique Id for JEI (for JEI Blacklist): divinerpg:bedrock_sword
	Ingredient Type for JEI: class net.minecraft.world.item.ItemStack
	Error Info gathered from JEI: 1 bedrock_sword divinerpg:bedrock_sword

```

Duplicate of https://github.com/mezz/JustEnoughItems/issues/3432

**Closed as not planned by mezz** 2024-06-11 05:36 UTC
