### ISSUE TITLE
[Other]: Items showing up in random order 

### ISSUE THREAD

**Issue by NotZimon** [mezz/JustEnoughItems#3763] opened 2024-09-14 23:33 UTC
### Other

As the title says

**Comment by RoboXGamer** [comment] 2024-09-15 11:52
This happens when we reload the resourcepacks

**Comment by RoboXGamer** [comment] 2024-09-15 11:53
using f3+T shortcut or change any resourcepacks then also 
the order gets messed up

**Comment by PUrE-elF** [comment] 2024-09-16 17:50
Got This problem either. Server resource packs can not changed.

**Comment by PUrE-elF** [comment] 2024-09-17 19:43
![Uploading 1429064.jpg…]()

**Comment by PUrE-elF** [comment] 2024-09-17 19:44
![1429064](https://github.com/user-attachments/assets/0205b493-b831-45a7-9771-08d27f95ff53)

**Comment by mezz** [comment] 2024-09-20 05:28
Thanks for the report!
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/3731 and has been fixed in the latest versions.

**Closed as not planned by mezz** 2024-09-20 05:28 UTC
Labels: duplicate
