### ISSUE TITLE
Crash plus button for moving recipe items over to a crafting bench 

### ISSUE THREAD

**Issue by DatrixTHLK** [mezz/JustEnoughItems#485] opened 2016-10-02 08:35 UTC
[Crash report](https://gist.github.com/DatrixTHLK/106053068e823f482949bddfcbb7bf81).
Already at the latest version 3.12.3.292 minecraft version 1.10.2 forge 12.18.1.2094
FEI isn't installed this time

While looking at a recipe while in a crafting bench I hit the plus button to move a few items over to the crafting bench to make an item but it pretty much froze my game and crashed immediately.

**Comment by mezz** [comment] 2016-10-02 22:36
Thanks for the report!
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/477
Reported to EZ Storage here: https://github.com/zerofall/EZStorage/issues/40

**Closed as completed by mezz** 2016-10-02 22:36 UTC
Labels: duplicate

**Comment by DatrixTHLK** [comment] 2016-10-10 12:51
Thanks Mezz. I appreciate it.
