### ISSUE TITLE
[Bug]: Mod search off when you press E [1.18.2]

### ISSUE THREAD

**Issue by XionioXMaster** [mezz/JustEnoughItems#2960] opened 2022-08-19 20:16 UTC
### Steps to Reproduce the Bug

I use search through the open inventory, but as soon as I press find E, my search collapses
version jei-1.18.2-9.7.1.255

![image](https://user-images.githubusercontent.com/86433158/185700020-690b3264-c28b-4aa2-955e-fd6a69745baa.png)

![image](https://user-images.githubusercontent.com/86433158/185700042-bb2b4374-a0d5-49ce-8f80-0853528827cb.png)

### Expected Behavior

The search menu should not close

### Actual Behavior

I don't understand what you mean

### Mod Pack URL (Optional)

https://mcpaste.com/13d3cb1269fb08b5cea16c1d1c2b85d6

**Comment by mezz** [comment] 2022-08-21 06:20
Thanks for the report!
Does this happen with only JEI installed?

**Comment by mezz** [comment] 2022-08-21 18:44
This is most likely caused by an older version of the Debugify mod.
It was fixed in the latest version: https://github.com/isXander/Debugify/issues/74

**Comment by XionioXMaster** [comment] 2022-08-23 08:17
> This is most likely caused by an older version of the Debugify mod. It was fixed in the latest version: [isXander/Debugify#74](https://github.com/isXander/Debugify/issues/74)

Thanks!

**Closed** 2022-08-23 16:02 UTC
Labels: needs followup
