### ISSUE TITLE
Show unique uses of items

### ISSUE THREAD

**Issue by Reygok** [mezz/JustEnoughItems#1834] opened 2020-01-01 17:05 UTC
Hi! I don't think this feature exists, if it does, I am sorry! It would be very handy if there was a way, when checking the uses of an item, by right clicking in JEI for example, to see unique uses. So, excluding those that are enabled via the ore dictionary.
For example, I have the Natura and Tinkers Construct mods, now if I check the usages of Bloodwood Planks (from Natura) I will see pages over pages of recipes and usages for any kind of wood planks. I would love to have a way of only showing uses, where Bloodwood Planks are required, for example only bloodwood slabs, and the Tinker stats for Bloodwood.
I hope I'm explaining this clearly!

Thanks a lot in advance :)

**Comment by Reygok** [comment] 2020-02-01 08:15
Please, I would really appreciate a reaction on this!

**Comment by Reygok** [comment] 2020-06-01 18:24
Can this be reopened?

**Comment by camarril** [comment] 2020-07-14 13:28
This. I need this. I'm trying to play FTB Interactions right now and there are a lot of examples where this would be a real life saver.

**Comment by Drullkus** [comment] 2020-08-12 05:46
This'd be lovely to have!

**Comment by mezz** [comment] 2024-07-19 04:55
Thanks for the suggestion!
I think this is a duplicate of
* https://github.com/mezz/JustEnoughItems/issues/1467

**Closed as not planned by mezz** 2024-07-19 04:55 UTC
Labels: enhancement
