### ISSUE TITLE
Crash When Pressing E To Return To Creative Tab

### ISSUE THREAD

**Issue by ChloeDawn** [mezz/JustEnoughItems#882] opened 2017-06-03 16:20 UTC
Game crashed to desktop when pressing E to close a recipe GUI and return to the creative tab I was browsing after viewing the recipe of an item via. the tab.

**JEI version:** [4.4.0.283](https://minecraft.curseforge.com/projects/just-enough-items-jei/files/2428180)
**Forge version:** [1.11.2-13.20.0.2304](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.11.2-13.20.0.2304/forge-1.11.2-13.20.0.2304-changelog.txt)

**Stacktrace:** [paste.ee/uVVl0]( https://paste.ee/p/uVVl0) 
**Relevant code:** [RecipesGui.java#L349](https://github.com/mezz/JustEnoughItems/blob/1.11/src/main/java/mezz/jei/gui/recipes/RecipesGui.java#L349)
###### Sorry, I can only provide the stacktrace because I accidentally wiped the test instance I'd been working with because I'm a goof. If I am able to replicate the issue (will try after submitting this) I'll update the issue with a full crash report.

**Comment by InsomniaKitten** [comment] 2017-06-03 16:33
I was able to somehow create a similar crash by opening the search tab entering some keys, clearing the field, then trying to switch to another tab.. but this time JEI isn't in the stack trace so idk what's going on.. 

**Crash report:** [paste.ee/BiCqd](https://paste.ee/p/BiCqd)

I don't think this is JEI related anymore so feel free to close this issue if you find no problems on your end.

**Comment by mezz** [comment] 2017-06-03 18:56
Thanks for the report!
The crash log you have is bizarre. It looks like a basic java structure is dying when `.clear()` is called on it. I'm not sure why.
Please try to reproduce this so I can see a full crash log.

**Comment by AEnterprise** [comment] 2017-06-03 19:02
@mezz i've seen this before, this is what heapens if you call clear on the MC NonNullList with null as default element

**Comment by mezz** [comment] 2017-06-03 19:30
Thanks, I just reached the same conclusion. This seems to be a vanilla bug and needs a forge fix. They should probably call clear on the internal list instead of `super`.

**Comment by mezz** [comment] 2017-06-04 01:16
I wrote some unit tests to try to break `NonNullList`, but I wasn't able to.
Please let me know if you have something specific I can do to replicate this crash.

**Comment by ChloeDawn** [comment] 2017-06-04 12:01
I tried multiple times but I've been unable to replicate this issue, sorry.

**Comment by mezz** [comment] 2017-06-04 19:16
If you get a chance, please run your pack with asie's [EnvironmentChecker](https://asie.pl/Projects/Minecraft/Mods/EnvironmentChecker) mod and paste a gist of the log here.
Maybe something is using ASM on `NonNullList` and breaking it?

**Comment by mezz** [comment] 2017-06-08 02:42
We found that this was caused by BetterFps: https://github.com/Guichaguri/BetterFps/issues/58

**Closed as completed by mezz** 2017-06-08 02:42 UTC
Labels: other mod
