### ISSUE TITLE
[Bug]: 1.12.2 Broken texture in JEI recipe menus and inventory GUI for version "jei_1.12.2-4.16.1.302.jar"

### ISSUE THREAD

**Issue by SKULLCRUSHER133** [mezz/JustEnoughItems#2810] opened 2022-04-26 23:01 UTC
### Steps to Reproduce the Bug

1. Install "jei_1.12.2-4.16.1.302.jar" as well as "Pixelmon-1.12.2-8.4.0-universal.jar", or install the same version of JEI in the Pixelmon Modpack from CurseForge (Linked below).
2. Launch a singleplayer or multiplayer game and open your inventory. You will notice that the search bar and other JEI buttons are completely white.
3. Check the recipes or uses for any item. You will notice that the background for the JEI recipes/usages menu has a broken texture

### Expected Behavior

Following these steps, you should not see broken textures in either the inventory screen, or the recipes/usages screen. Attached to this are examples from the same JEI version "jei_1.12.2-4.16.1.302.jar" and an outdated version of Pixelmon "Pixelmon-1.12.2-8.3.8-universal.jar" As you can see, the GUI with this version of Pixelmon does not have a broken texture. There are no broken textures when viewing the recipies/usages of Pixelmon items either.

![2022-04-26_19 00 17](https://user-images.githubusercontent.com/23526403/165406633-fce3817f-228b-4de4-b5da-5261b58a782c.png)
![2022-04-26_18 59 57](https://user-images.githubusercontent.com/23526403/165406634-65886391-109e-4d6f-84ae-a1e425d72a04.png)
![2022-04-26_19 00 00](https://user-images.githubusercontent.com/23526403/165406637-01bdf679-3214-4549-882c-41b89e35eed4.png)
![2022-04-26_19 00 05](https://user-images.githubusercontent.com/23526403/165406638-77ea6a8c-2c7c-4e47-ae41-0f509ecc116e.png)
![2022-04-26_19 00 15](https://user-images.githubusercontent.com/23526403/165406643-1ed21565-0783-4753-80f8-146747e8b4a4.png)
![2022-04-26_19 00 16](https://user-images.githubusercontent.com/23526403/165406644-58b0c506-c132-4f0e-a9a8-12fcba2600ee.png)

### Actual Behavior

Because of the bug, the textures in the GUI for both the inventory and the recipies/usages menu are broken. The texture itself has some sections of transparent spaces where you can see the in game world through.
![2022-04-26_14 38 41](https://user-images.githubusercontent.com/23526403/165404948-9e717ba2-82a2-42d9-838e-d03a8b63c7b9.png)
![2022-04-26_14 38 47](https://user-images.githubusercontent.com/23526403/165404950-c4134546-939f-485e-af52-2c607fece034.png)
![2022-04-26_17 48 47](https://user-images.githubusercontent.com/23526403/165404952-207984f8-9f0d-4efb-868a-1ee04be74919.png)

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/the-pixelmon-modpack

### Mod Pack Version (Optional)

The Pixelmon Modpack 8.4.0.zip

### Extra Notes (Optional)

This bug seems to be entirely cosmetic, and could be ignored as JEI seems to function as normal. However, the broken textures are very unsightly. You can hide JEI using the keys ctrl+O, which hides the search bar and several buttons related to JEI. I believe this to be an issue with the interaction between JEI and Pixelmon, as the only thing that has changed within the modpack I am using has only been Pixelmon updating from 8.3.8 to 8.4.0.

I understand, and accept that, this may be a low-priority issue, as it seems to be a bug related to the interaction between JEI and a mod by another author, as well as it being from an old version of JEI. Also, I apologize if I should have made a ticket with Pixelmon instead, I wasn't sure if I should have since the issue seems to only affect JEI. If this ticket is not applicable to JEI, then I will make a ticket with the Pixelmon mod team. Thank you.

Edit 1: I'm sorry, I accidentally sent this without attaching pictures of JEI before the broken textures started happening. I am not used to using github.
Edit 2: I forgot to add my latest.log but it should be here now.

### latest.log
[latest.log](https://github.com/mezz/JustEnoughItems/files/8567426/latest.log)

_No response_

**Comment by KittyForest** [comment] 2022-04-28 05:19
i also have this problem and i would love to know how to fix it

**Comment by KittyForest** [comment] 2022-04-28 05:56
> i also have this problem and i would love to know how to fix it

it seems to just be that specific version of jei... i put an older jei version into the same pixelmon version and it doesnt break the textures

**Comment by SKULLCRUSHER133** [comment] 2022-04-28 10:50
> > i also have this problem and i would love to know how to fix it
> 
> it seems to just be that specific version of jei... i put an older jei version into the same pixelmon version and it doesnt break the textures

Oh? I'll have to give that a try later. What version of JEI did you use?

**Comment by SKULLCRUSHER133** [comment] 2022-05-03 02:03
> > i also have this problem and i would love to know how to fix it
> 
> it seems to just be that specific version of jei... i put an older jei version into the same pixelmon version and it doesnt break the textures

It turns out this exact issue is a conflict between Gameshark (a mod by pixelmon) and JEI. The helpful folks at Pixelmon mod found this out in the issue ticket I opened with them. Check it out here, [ticket](https://pixelmonmod.com/tracker.php?p=2&t=17326)

**Comment by mezz** [comment] 2022-06-17 03:14
Thank you for finding the cause of this problem. Unfortunately it looks like something to fix on their side, so I will close this issue.

**Closed as completed by mezz** 2022-06-17 03:14 UTC
Labels: other mod
