### ISSUE TITLE
[Other]: Artifact due to Pixelmon mod

### ISSUE THREAD

**Issue by Otopuss** [mezz/JustEnoughItems#2981] opened 2022-09-03 16:22 UTC
### Other

Installed the Pixelmon 8.4.2 mod, and then installed the JEI, after the artifacts were called. Please help with the problem.

![explorer_dzojkIoxEb](https://user-images.githubusercontent.com/112771850/188279472-240247ad-e14f-4d82-87c1-7624d0783ae8.png)
![javaw_3CAiqO4xw5](https://user-images.githubusercontent.com/112771850/188279473-5b04607f-a99f-4074-89d8-96d414abd05a.png)
![javaw_aDubgLilG8](https://user-images.githubusercontent.com/112771850/188279478-2e1d60ea-dc89-4b0a-98df-7a562990e8e4.png)

**Comment by mezz** [comment] 2022-09-04 23:05
Thanks for the report!
It looks like this is a duplicate of https://github.com/mezz/JustEnoughItems/issues/2878
I think this issue is coming from Pixelmon, can you report it to them and link back to the issue above?

**Closed as completed** 2022-09-04 23:06 UTC
Labels: duplicate
