### ISSUE TITLE
Instant game crash..

### ISSUE THREAD

**Issue by SliceeGamer** [mezz/JustEnoughItems#1672] opened 2019-08-12 11:40 UTC
So when I load up jei with some other mods, the game just instant crashes. This is the crash report

The game crashed whilst unexpected error
Error: java.lang.NoClassDefFoundError: net/minecraftforge/event/TickEvent$ClientTickEvent

And here's the full thing, also sorry this is my first time using GitHub so I might do mistakes :P

```
---- Minecraft Crash Report ----
// But it works on my machine.

Time: 12/08/19 12:32
Description: Unexpected error

java.lang.NoClassDefFoundError: net/minecraftforge/event/TickEvent$ClientTickEvent
	at mezz.jei.ingredients.IngredientFilterBackgroundBuilder.<init>(IngredientFilterBackgroundBuilder.java:38) ~[?:6.0.0.10] {}
	at mezz.jei.ingredients.IngredientFilter.<init>(IngredientFilter.java:85) ~[?:6.0.0.10] {}
	at mezz.jei.load.PluginLoader.getIngredientFilter(PluginLoader.java:156) ~[?:6.0.0.10] {}
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:74) ~[?:6.0.0.10] {}
	at mezz.jei.startup.ClientLifecycleHandler.onRecipesLoaded(ClientLifecycleHandler.java:125) ~[?:6.0.0.10] {}
	at mezz.jei.startup.ClientLifecycleHandler.lambda$new$2(ClientLifecycleHandler.java:103) ~[?:6.0.0.10] {}
	at mezz.jei.startup.ClientLifecycleHandler$$Lambda$2701/598023807.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-0.10.6-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-0.10.6-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2046/1419216510.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-0.10.6-service.jar:?] {}
	at net.minecraftforge.client.ForgeHooksClient.onRecipesUpdated(ForgeHooksClient.java:999) ~[?:?] {}
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_199525_a(ClientPlayNetHandler.java:1265) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148833_a(SourceFile:28) ~[?:?] {}
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148833_a(SourceFile:15) ~[?:?] {}
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {}
	at net.minecraft.network.PacketThreadUtil$$Lambda$4242/1074766210.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:857) [?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.0.40.jar:28.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$344/2113243119.call(Unknown Source) [forge-1.14.4-28.0.40.jar:28.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-3.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50) [modlauncher-3.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:68) [modlauncher-3.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:80) [modlauncher-3.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-3.1.1.jar:?] {}
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.event.TickEvent$ClientTickEvent
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:102) ~[modlauncher-3.1.1.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51] {}
	... 35 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at mezz.jei.ingredients.IngredientFilterBackgroundBuilder.<init>(IngredientFilterBackgroundBuilder.java:38)
	at mezz.jei.ingredients.IngredientFilter.<init>(IngredientFilter.java:85)
	at mezz.jei.load.PluginLoader.getIngredientFilter(PluginLoader.java:156)
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:74)
	at mezz.jei.startup.ClientLifecycleHandler.onRecipesLoaded(ClientLifecycleHandler.java:125)
	at mezz.jei.startup.ClientLifecycleHandler.lambda$new$2(ClientLifecycleHandler.java:103)
	at mezz.jei.startup.ClientLifecycleHandler$$Lambda$2701/598023807.accept(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204)
	at net.minecraftforge.eventbus.EventBus$$Lambda$2046/1419216510.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.client.ForgeHooksClient.onRecipesUpdated(ForgeHooksClient.java:999)
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_199525_a(ClientPlayNetHandler.java:1265)
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148833_a(SourceFile:28)
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148833_a(SourceFile:15)
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21)
	at net.minecraft.network.PacketThreadUtil$$Lambda$4242/1074766210.run(Unknown Source)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['SuperSlicee'/139, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Chunk stats: Client Chunk Cache: 729, 0
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:410)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1745)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:405)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$344/2113243119.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:68)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:80)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 965616032 bytes (920 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 3.1.1+59+e32e753
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-0.10.6-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.0.40.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.0.40.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-0.16.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.0.40.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.0.40.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.0.40.jar fml TRANSFORMATIONSERVICE 
	FML: 28.0
	Forge: net.minecraftforge:28.0.40
	FML Language Providers: 
		javafml@28.0
	Mod List: 
		Craftable-Saddles-Mod-1.14.4.jar Craftable Saddles {craftable_saddles@1.3 DONE}
		DoggyTalents-1.14.4-1.15.1.0-universal.jar Doggy Talents {doggytalents@1.15.1.0 DONE}
		FastLeafDecay-v16.jar FastLeafDecay {fastleafdecay@v16 DONE}
		Immersive+Recipes-1.14.4-1.2.0.jar Immersive Recipes {immersiverecipes@1.2.0 DONE}
		jei-1.14.4-6.0.0.10.jar Just Enough Items {jei@6.0.0.10 DONE}
		MinecraftCapes Forge 1.14.3.jar James090500's MinecraftCapes Mod {minecraftcapes@1.0 DONE}
		Portality-1.14.4-2.0.12.jar Portality {portality@NONE DONE}
		Reap-Mod-1.14.4.jar Reap Mod {reap@1.10.0 DONE}
		SuperTools-1.2c.jar Super Tools {supertools@1.2c DONE}
		titanium-2.1.53.jar Titanium {titanium@2.1.53 DONE}
		Xaeros_Minimap_1.17.5_Forge_1.14.4.jar Xaero's Minimap {xaerominimap@1.17.5 DONE}
		XaerosWorldMap_1.4.7_Forge_1.14.4.jar Xaero's World Map {xaeroworldmap@1.4.7 DONE}
		forge-1.14.4-28.0.40-universal.jar Forge {forge@28.0.40 DONE}
	Launched Version: 1.14.4-forge-28.0.40
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce GTX 770/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.43, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/PewDiePie Resourcepack.zip
	Current Language: English (US)
	CPU: 8x AMD FX(tm)-8320 Eight-Core Processor 
```

I hope you can come back to me soon.

**Comment by Ommina** [comment] 2019-08-12 18:59
You'll have to update forge to 28.0.45 (or later, presumably) or downgrade JEI to 6.0.0.9.  If you elect to do the former, fastleafdecay (and maybe others) will also need to be updated.

**Comment by sk2k** [comment] 2019-08-14 06:10
I have the same problem. **As soon as i hit E to open the inventory the game crashes.**

These are the mods i use:

		BiomesOPlenty-1.14.4-9.0.0.231-universal.jar Biomes O' Plenty {biomesoplenty@1.14.4-9.0.0.229 DONE}
		FastLeafDecay-v17.jar FastLeafDecay {fastleafdecay@v17 DONE}
		gravestone-1.15.0.jar Gravestone Mod {gravestone@1.15.0 DONE}
		jei-1.14.4-6.0.0.10.jar Just Enough Items {jei@6.0.0.10 DONE}
		mappy-forge-1.0.4.jar Mappy {mappy@1.0.4 DONE}
		PyramidPlunder-1.14.4-1.0.jar Pyramid Plunder {pyramidplunder@1.14.4-1.0 DONE}
		theoneprobe-1.14-1.4.33-alpha.jar The One Probe {theoneprobe@NONE DONE}
		forge-1.14.4-28.0.45-universal.jar Forge {forge@28.0.45 DONE}
		forge-1.14.4-28.0.45-client.jar Minecraft {minecraft@1.14.4 DONE}

**Comment by mezz** [comment] 2019-08-19 01:44
Thanks for the report!
Yes, please update JEI and Forge to the latest versions.
This was caused by a breaking change in Forge and has been resolved.

Duplicate of #1663

**Closed as completed by mezz** 2019-08-19 01:44 UTC
Labels: duplicate
