### ISSUE TITLE
Feature request: Elimination Search

### ISSUE THREAD

**Issue by djcosmic2** [mezz/JustEnoughItems#1221] opened 2018-05-11 00:38 UTC
Suggestion: a way to REMOVE items from a search.

Example: you want to search for the Chisel from the Chisel Mod.

@chisel brings up both Chisel plus Chisel n Bits.

@chisel chisel brings up items called chisel from both mods

!@bits @chisel chisel would return just items containing chisel from Chisel Mod ignoring items from any mods containing the word "bits" in their name

@chisel !@bits !chisel would return all items from mods containing chisel in their name but not bits, and ignoring any items with the word chisel in their name.

Etc

**Comment by mezz** [comment] 2018-05-12 00:12
Thanks for the suggestion!
You can do this already with `-` instead of `!`, try it out :)
![2018-05-11_17 11 10](https://user-images.githubusercontent.com/916092/39951399-60abc4de-553e-11e8-9da2-1a558ac0ab03.png)
![2018-05-11_17 11 21](https://user-images.githubusercontent.com/916092/39951400-60c67bf8-553e-11e8-86cb-d26f9f39d342.png)

**Comment by mezz** [comment] 2018-05-12 00:13
Duplicate of https://github.com/mezz/JustEnoughItems/issues/820

**Closed as completed by mezz** 2018-05-12 00:12 UTC
Labels: duplicate
