### ISSUE TITLE
the server must have jei installed

### ISSUE THREAD

**Issue by rothrock96** [mezz/JustEnoughItems#1631] opened 2019-07-08 07:53 UTC
it won't work for me server side, i have it both in my client and server. i am running on 1.12.2

**Comment by mezz** [comment] 2019-07-09 20:38
Thanks for the report!
I think this is a duplicate of https://github.com/mezz/JustEnoughItems/issues/1615, lets move discussion to there.

**Closed as completed by mezz** 2019-07-09 20:38 UTC
Labels: duplicate
