### ISSUE TITLE
Crash when using the OR in heavily modded private Pack

### ISSUE THREAD

**Issue by Zanges** [mezz/JustEnoughItems#1056] opened 2017-11-26 19:51 UTC
I get the following Crash(In my Private & heavily modded Pack) when using the OR Operator.

Crash Log:
https://gist.github.com/zanges/d4915afe97c455a5769e47f6795d5447

In worldSettings:
S:filterText=@ae | 
OR
S:filterText=@ae|@

**Comment by TehNut** [comment] 2017-11-26 20:07
Duplicate of #1055

**Comment by mezz** [comment] 2017-11-26 21:59
Thanks for the report!
This is fixed in the next version.

**Closed as completed by mezz** 2017-11-26 21:59 UTC
Labels: duplicate
