### ISSUE TITLE
Crashing when viewing recipes

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [mezz/JustEnoughItems#491] opened 2016-10-03 18:48 UTC
https://gist.github.com/anonymous/ae16a5b2c5d287846dd6cbb564a149b8

**Comment by way2muchnoise** [comment] 2016-10-03 18:55
Seems to be an EIO issue `at crazypants.enderio.integration.jei.TankRecipeCategory.setRecipe(TankRecipeCategory.java:181)`

You should go and report that on their repo

**Comment by mezz** [comment] 2016-10-03 21:32
Thanks for the report!
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/488
This is an EnderIO crash, reported here: SleepyTrousers/EnderIO#3741

**Closed as completed by mezz** 2016-10-03 21:32 UTC
Labels: duplicate
