### ISSUE TITLE
Item list doesn't change to screen size while viewing recipes

### ISSUE THREAD

**Issue by pauljoda** [mezz/JustEnoughItems#180] opened 2016-02-20 01:08 UTC
I resized my window while looking at some recipes and this was the result. Same things happens in reverse but renders off screen. Seems the list doesn't adapt to screen size changes while looking at recipes, even JEI added handlers 

http://i.imgur.com/DxDTyUd.png

**Comment by mezz** [comment] 2016-02-20 01:42
Thanks for the report!
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/171
Please update your JEI.

**Closed as completed by mezz** 2016-02-20 01:42 UTC
Labels: duplicate

**Comment by pauljoda** [comment] 2016-02-20 02:50
Ah didn't see that issue, good deal.
