### ISSUE TITLE
[1.14.4] Jei for 1.14.3 loads on 1.14.4 but does not show the interface on the right.

### ISSUE THREAD

**Issue by ProsperCraft** [mezz/JustEnoughItems#1646] opened 2019-07-23 22:26 UTC
Update needed.

jei-1.14.3-6.0.0.8

On forge  - 1.14.4 - 28.0.13

**Comment by ProsperCraft** [comment] 2019-07-24 16:04
Due to Fast workbench.
https://github.com/Shadows-of-Fire/FastWorkbench/issues/21

1.14.3 JEI works fine on 1.14.4

**Comment by sarifynna** [comment] 2019-07-26 19:11
I am having the same problem with JEI not showing but I am not using the fast workbench mod (I am using many others though) I can't live without JEI while using mods, help is appreciated greatly!

Sorry if I am supposed to open a new issue, but this one had a relevant topic and I didn't want to be redundant with the title I guess?

[latest.log](https://github.com/mezz/JustEnoughItems/files/3437089/latest.log)

**Comment by ProsperCraft** [comment] 2019-07-26 19:31
It isn't just Fast Workbench, it is anything that replaces default anvils, or crafting tables.

AnvilTweaks caused it as well.

Anviltweaks sets the default anvil to air I beleive.

**Comment by sarifynna** [comment] 2019-07-26 19:56
Frick yes, thank you! I haven't posted much ever and usually just lurk and I don't know the etiquette here sorry that I opened another issue, I don't know what I am doing here. >.<

**Comment by Shadows-of-Fire** [comment] 2019-07-28 21:41
MinecraftForge/MinecraftForge/issues/5984

**Comment by Shadows-of-Fire** [comment] 2019-08-05 03:41
Forge 41 should resolve this problem.

**Comment by Knito58** [comment] 2019-08-06 18:05
Have Forge 41. Does not work for me. JEI (jei-1.14.3-6.0.0.8.jar) is in the mods folder but does not appear in Forge's mod list. There is not even a warning about it. Normally non-loaded mods get pointed out from Forge in newer versions.

**Comment by ProsperCraft** [comment] 2019-08-06 18:05
https://github.com/mezz/JustEnoughItems/issues/1659

**Comment by mezz** [comment] 2019-08-08 05:23
Thanks for the report!
This is fixed in the latest version.
Duplicate of #1641

**Closed as completed by mezz** 2019-08-08 05:23 UTC
Labels: duplicate

**Comment by Knito58** [comment] 2019-08-08 08:35
JEI 1.14.4 - 6.0.0.9: Fixed and working now! Thank you for managing this great piece of software.
