### ISSUE TITLE
Game crashes when hovering any type of wood

### ISSUE THREAD

**Issue by Anmos31** [mezz/JustEnoughItems#2647] opened 2022-01-03 13:01 UTC
Not only vanilla wood. It's been happening with BoP too.

Description: Rendering screen

java.lang.IllegalArgumentException: Unknown ingredient class: class net.minecraft.client.gui.Font

**Comment by Ommina** [comment] 2022-01-03 22:22
Hi!  This is been fixed in the most recent (as of this writing) release of JEI: the Beta releases for both 1.17 and 1.18 on CurseForge.  Update your JEI and you should be fine.

**Comment by mezz** [comment] 2022-01-06 13:49
Thanks for the report!
This is a duplicate of #2638

**Closed as completed by mezz** 2022-01-06 13:49 UTC
Labels: duplicate
