### ISSUE TITLE
take your political BS out of your Mod you fuicking asshat

### ISSUE THREAD

**Issue by QuackenAudio** [mezz/JustEnoughItems#2120] opened 2020-10-15 17:57 UTC
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by JustJinxed** [comment] 2020-10-16 02:28
No.....

**Comment by kylerittenhause** [comment] 2020-10-16 04:01
who is joe

**Comment by QuackenAudio** [comment] 2020-10-16 04:15
> 
> 
> who is joe

He's a worthless politician with Horrible Ideas

**Comment by kylerittenhause** [comment] 2020-10-16 06:28
> > who is joe
> 
> He's a worthless politician with Horrible Ideas

i know i was joking, he is the kind of guy who says you can transition to transgender to gain advantage
![image](https://user-images.githubusercontent.com/70843095/96220729-e96aa400-0fa6-11eb-8151-ca44b2ed8c3e.png)

**Comment by mezz** [comment] 2020-10-16 17:12
Duplicate of https://github.com/mezz/JustEnoughItems/issues/2093

**Closed as completed by mezz** 2020-10-16 17:12 UTC
