### ISSUE TITLE
[Crash]: An unexpected critical error was encountered

### ISSUE THREAD

**Issue by gri3229** [mezz/JustEnoughItems#3613] opened 2024-07-19 18:41 UTC
### Steps to Reproduce the Crash

1. Run minecraft with the mods specified in krashreprt. 2.Try to run any of the old or newly created worlds

### Extra Notes (Optional)

According to the crash report, there are mentions of jei and mixin. If you exclude any version of jei from the mods list, everything runs fine. Experimentally I managed to find out that above version jei-1.20.1-forge-15.3.0.8 there is a problem. So far I stopped here. I hope for fast support!

### Crash Report

https://gist.github.com/gri3229/a1267c8f5973d87d281a150ff23ded99

**Comment by azaquaz** [comment] 2024-07-20 20:03
I'm having a very similar crash on world load, only when JEI is installed. I compared our modlists and installed just the mods we have in common, here's the crash:
https://gist.github.com/azaquaz/e648490c9230660ff0c514b40756d916

**Comment by mezz** [comment] 2024-07-21 11:19
Thanks for the report!
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/3599
It has been fixed in the latest version of LDLib, which is included in several mods like gtceu-1.20.1.
You can fix the issue by updating these mods or downgrading JEI to an older verison.

**Closed as not planned by mezz** 2024-07-21 11:19 UTC
