### ISSUE TITLE
[Bug]: JEI UI not showing and saying there is not enough space to display the jei ingredient list overlay

### ISSUE THREAD

**Issue by jdisnme** [mezz/JustEnoughItems#3762] opened 2024-09-14 21:06 UTC
### Steps to Reproduce the Bug

![github](https://github.com/user-attachments/assets/1bdf4b53-6500-415c-85e1-d1582298b036)

### Expected Behavior

if the bug were fixed i would be able to access the recipes and search bar for the jei mod

### Actual Behavior

the bug just explains how i cant use the jei search list and recipes because of the ingredient list overlay

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/mc-mods/jei

### Mod Pack Version (Optional)

1.20.1

### Extra Notes (Optional)

nothing else

**Comment by PUrE-elF** [comment] 2024-09-19 05:33
You can set GUI scale to smaller one and it will show.

**Comment by mezz** [comment] 2024-09-20 00:57
Thanks for the report!

This is not a bug, there just isn't enough space. Where on the screen should JEI be shown? There is no room.
Please try closing the recipe book or changing your GUI scale to make more space.

**Comment by mezz** [comment] 2024-09-20 01:21
I pushed a change to the tooltip text, hopefully it's more clear now!
"The area next to this screen is too small for JEI to display."

**Closed as completed by mezz** 2024-09-20 01:21 UTC
