### ISSUE TITLE
1.10.2 crash when attempting to look at recipe for a unbreaking III enchanting book (Ender IO Recipe)

### ISSUE THREAD

**Issue by LordHellscream** [mezz/JustEnoughItems#489] opened 2016-10-03 02:44 UTC
crash log:

http://pastebin.com/YMj6viPr

**Comment by TehNut** [comment] 2016-10-03 03:29
Caused by EnderIO

**Comment by mezz** [comment] 2016-10-03 06:19
Thanks for the report!
This should be fixed in the latest version of EnderIO.
https://minecraft.curseforge.com/projects/ender-io/files

**Closed as completed by mezz** 2016-10-03 06:19 UTC
Labels: other mod
