### ISSUE TITLE
[Bug]: Pressing E in the JEI search box exits the inventory

### ISSUE THREAD

**Issue by redkittty** [mezz/JustEnoughItems#3205] opened 2023-05-01 20:47 UTC
### Steps to Reproduce the Bug

1. Click on the JEI search box in the inventory
2. Press E when typing

### Expected Behavior

It exits the inventory

### Actual Behavior

/\
 |
 |

**Comment by redkittty** [comment] 2023-05-01 20:47
btw I was using 1.18.2

**Comment by Aceplante** [comment] 2023-06-19 05:49
Yea same, I think this is new

**Comment by Mrabetto** [comment] 2023-07-04 15:06
I have that same issue, but also cant delete by backspace

**Comment by HiWord9** [comment] 2023-07-12 00:55
Duplicate of #2801

**Comment by Aceplante** [comment] 2023-10-11 00:39
plz fix?

**Closed as not planned** 2024-01-28 20:22 UTC
Labels: duplicate
