### ISSUE TITLE
Mod Ignores changes and reverts back to recipe mode everytime Minecraft is restarted

### ISSUE THREAD

**Issue by bobbythejobby** [mezz/JustEnoughItems#266] opened 2016-05-06 23:35 UTC
Every time I change from recipe mode to give items in cheat mode when I restart minecraft Just Enough Items reverts back to recipe mode. I have tried checking the apply globaly checkbox and editing the JEI.cfg config file. But no matter what I do It always reverts back to recipe mode when Minecraft is restarted

**Comment by mezz** [comment] 2016-05-06 23:40
Thanks for the report!

JEI's config for that is saved per-world in `config/JEI/worldSettings.cfg` with a hash value to identify the world. The key is `cheatItemsEnabled`.

Are you closing the world normally or forcing the game closed?
Are you starting a new world each time?

**Comment by DingoX3** [comment] 2016-05-07 06:20
Forge: 1891
JEI: 1.9-3.3.3.197
A list of all other mods installed: https://modlister.com/user/DingoX3

Im having a similar issue, but it doesnt let me switch to cheat mode at all. The value says true but when i go back to my inventory screen its not in cheat mode. I also tried the global check box and nothing.

**Comment by mezz** [comment] 2016-05-07 06:22
@DingoX3 you have pretty much _every_ 1.9 mod, can you try to narrow it down? Does the issue occur with only JEI?

**Comment by DingoX3** [comment] 2016-05-07 06:24
Yea its quite a few mods. Im working on a large pack right now sorry about that. I'll run it alone and see if i have the same issue.

**Comment by DingoX3** [comment] 2016-05-07 06:31
ok confirmed its working when alone with forge 1891. I'll test it alone next time. Could you do me a favor if you have a sec and look at the mods and see if theres one that pops out at you as a possible mod that interacts with that part of jei? Great mod btw. Its a lifesaver and its coming along great.

**Comment by mezz** [comment] 2016-05-07 06:33
Sorry but I really have no idea. The best way to find the mod that causes the issue is to try half your mods at a time. If it works, that half is good and you can set them aside. If it doesn't work, then the ones you left out are good. You can keep doing that until you find the one causing a problem.

**Comment by DingoX3** [comment] 2016-05-07 06:36
Ok sounds good. I'll let you know if i find it.

**Comment by mezz** [comment] 2016-05-07 06:37
Thanks! Good luck.

**Comment by bobbythejobby** [comment] 2016-05-07 09:51
Ah I see Yes the issue occurs everytime I start a new world. Thought it was the same as the old version Too Many Items. You didn't have to change that one every time you started a new world. Just a bit of a pain having to config the mod each time a new world is started, but I guess I will just have to learn to live with it lol

**Comment by mezz** [comment] 2016-05-09 23:50
Alright, sorry about that. I'll close this issue since then. I will probably add a hotkey for cheat mode in the 1.9 version.
@DingoX3 if you find out what happened, please make a new issue.

**Closed as completed by mezz** 2016-05-09 23:50 UTC
Labels: invalid
