### ISSUE TITLE
[1.10.2][3.10.0.265] Using Shift-[+] in EnderIO machine causes lost materials

### ISSUE THREAD

**Issue by Aedda** [mezz/JustEnoughItems#513] opened 2016-10-10 08:30 UTC
Steps to reproduce:

1) Place EnderIO Slice'N'Splice and give power
2) Give self items for multiple of any Slice'N'Splice recipe, I used Ender Resonator for the recipe.
3) Open SnS interface, find recipe in JEI
4) Shift-click the [+], JEI will attempt to insert all available materials into machine however the machine only accepts 1 item in each slot.

Result, SnS makes 1 item, and the excess materials are lost.

**Comment by TehNut** [comment] 2016-10-10 08:43
I believe this is on EnderIO's end as they wrote the transfer handler.

**Comment by mezz** [comment] 2016-10-10 21:52
Thanks for the report!
I'll take a look, this sounds pretty bad.

**Comment by mezz** [comment] 2016-10-10 22:00
Confirmed, and this is on JEI's side since they are using JEI's built-in recipe transfer handler.

**Comment by mezz** [comment] 2016-10-10 23:53
Fixed in JEI 3.12.7

**Closed as completed** 2016-10-10 23:53 UTC
Labels: bug, recipe transfer
