### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Y0ungSandwich** [mezz/JustEnoughItems#591] opened 2016-11-07 21:41 UTC
Crash on startup
JEI is the newest version as is Forge.

https://gist.github.com/Cuppycake/2c7338416a306f4087d5e2c3f32d3b23

**Comment by TehNut** [comment] 2016-11-07 21:42
Caused by JustEnoughTooltips

**Comment by mezz** [comment] 2016-11-07 21:48
Thanks for the report!
It has been reported here: https://github.com/superckl/JustEnoughTooltips/issues/5
Duplicate of #567

**Closed as completed by mezz** 2016-11-07 21:48 UTC
Labels: duplicate

**Comment by P3rf3ctXZer0** [comment] 2016-11-07 22:07
Different Cause 

https://gist.github.com/P3rf3ctXZer0/c8c4a6944347d22c089dd902327f3084

**Comment by mezz** [comment] 2016-11-07 22:38
@P3rf3ctXZer0 that's not related to this issue or JEI. You need to increase the amount of memory you're giving java, or remove mods that are using lots of memory.
