### ISSUE TITLE
Can't bookmark the same item but with different nbt tags

### ISSUE THREAD

**Issue by warning-djkajslh** [mezz/JustEnoughItems#2534] opened 2021-10-23 07:38 UTC
Bookmark a shulker box, then put something in the box, then try to bookmark it again, JEI won't let you.

**Comment by Lodish** [comment] 2021-12-19 20:53
Also have this issue using the 1.16 one (jei-1.16.5-7.7.1.138.jar) where I can't bookmark the same item if it has different nbt, for instance only one written book can be bookmarked. I'm assuming there must be an older version where this does work as I only downloaded and installed jei on the advice of someone using it to save differently lored paper from a server we both played.

**Comment by mezz** [comment] 2022-01-06 15:22
Thank for this report!
This is a duplicate of a much older report: https://github.com/mezz/JustEnoughItems/issues/1940. 
I'm working on a fix for it now.

**Closed as completed by mezz** 2022-01-06 15:22 UTC
Labels: bug
