### ISSUE TITLE
Cache Recipes and Plugins

### ISSUE THREAD

**Issue by kd8lvt** [mezz/JustEnoughItems#679] opened 2016-12-30 03:05 UTC
Thank you for reporting!

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

For issues:
 * Try the latest version, it may have fixed the issue already.
 * If you have NEI or FEI installed, please try without it before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

---------

Hey! As a person with a slower computer, joining servers can be a pain in the behind on larger packs (eg. Hermitpack), as JEI takes almost TEN seconds (aka 9922 ms) to reload plugins, and does so twice every time I join any server (not to mention reloading the recipes twice as well) making the server ultimately time me out almost every single time.

So, it would be nice if JEI, instead of reloading plugins and recipes every single time I attempt to join a server, reload them once every time I join a different server after game reload (eg. I start the game, it loads recipes/plugins, I join Server 1, it reloads it, I join Server 2 it reloads it, I join Server 1 or Server 2 _again_  and it _doesn't_ reload plugins and recipes, then if I were to reload my game it would start this cycle again, that way I would only time out from servers once, rather than almost every time I try.) Apart from this one _tiny_ issue, this is a very well made and useful mod. 

Thanks for all the blood, sweat and tears you've put into JEI, it's a wonderful mod!
  -Kd

(By the way, I'm going to bed after I write this, so I won't be able to reply to anything until tomorrow, sorry...)

**Comment by mezz** [comment] 2016-12-30 03:11
Thanks for the report!
This is an issue with mods reloading JEI when they should not. 
I am working with minetweaker to eliminate JEI reloads entirely.
Duplicate of https://github.com/mezz/JustEnoughItems/issues/551

**Closed as completed by mezz** 2016-12-30 03:11 UTC
Labels: duplicate
