### ISSUE TITLE
[Suggestion] Move items into crafting window

### ISSUE THREAD

**Issue by Raelzaryn** [mezz/JustEnoughItems#1033] opened 2017-10-26 09:42 UTC
I'm aware that you disabled the moving items into the crafting window for a reason.
But with 1.12 Minecraft has a built in recipe book at allows to do just that. Wouldn't it be possible to use that functionality to move the items?

**Comment by mezz** [comment] 2017-11-26 01:02
Sorry I missed this issue.
It seems like a good idea.
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/916

**Closed as completed by mezz** 2017-11-26 01:02 UTC
Labels: duplicate
