### ISSUE TITLE
[Suggestion]: Can't change the Key setting in fabric ver

### ISSUE THREAD

**Issue by mongshal** [mezz/JustEnoughItems#3744] opened 2024-09-06 08:01 UTC
### Suggestion

In Forge ver, I can simply change keysetting in keybind menu but In fabric ver, there in no JEI keysetting in keybind menu
and I couldn't find at mod setting either

I don't think it's glitch

**Comment by mezz** [comment] 2024-09-12 05:20
Thanks for the report!

This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/3000

Key bindings for Fabric have been implemented in JEI 
for 1.20.1: `15.18.0.80`+
and 1.21.1: `19.17.0.196`+

**Closed as not planned by mezz** 2024-09-12 05:20 UTC
Labels: duplicate
