### ISSUE TITLE
[Bug]: Icon when looking at mechanical crafter recipe shifts to the right in the jei

### ISSUE THREAD

**Issue by zachsai** [mezz/JustEnoughItems#2748] opened 2022-03-09 05:38 UTC
### Steps to Reproduce the Bug

look at item from create that is crafted with mechanical crafter
![image](https://user-images.githubusercontent.com/63996164/157379511-75592ec2-bfe3-4e46-87e7-31e093a5d53e.png)

### Expected Behavior

not shift

### Actual Behavior

shifts

**Comment by mezz** [comment] 2022-03-09 18:09
Thanks for the report!
Create fixed this bug here: https://github.com/Creators-of-Create/Create/issues/2779
What versions are you using?

**Comment by mezz** [comment] 2022-03-09 18:09
Likely duplicate of https://github.com/mezz/JustEnoughItems/issues/2718

**Comment by zachsai** [comment] 2022-03-09 20:13
> Thanks for the report! Create fixed this bug here: [Creators-of-Create/Create#2779](https://github.com/Creators-of-Create/Create/issues/2779) What versions are you using?

![image](https://user-images.githubusercontent.com/63996164/157526240-04974d47-88a2-4e13-b304-9c13aaa13326.png)

**Comment by mezz** [comment] 2022-03-09 20:57
Looking at the dates, I think their fix has not been released yet.
I included a fix for this in JEI as well, try updating JEI to version 9.4.0 or higher.

**Comment by zachsai** [comment] 2022-03-10 01:31
I'm using version 9.4.1.112 and it still happens

**Comment by mezz** [comment] 2022-03-14 23:38
I need some more information to solve this issue, please paste your full `latest.log` to https://gist.github.com and link it here.

**Comment by zachsai** [comment] 2022-03-15 00:56
https://gist.github.com/WelpSTudent/fc5ec6813286448383f8c391ca351114

**Comment by zachsai** [comment] 2022-03-15 00:57
![image](https://user-images.githubusercontent.com/63996164/158285110-ed49675c-7f9f-4cb1-a52c-e5d1371fc716.png)

**Comment by mezz** [comment] 2022-03-15 19:23
Thanks, I see the problem now.

Fortunately, it looks like Create has released their update, can you please try it out?
`Create 1.18.1 v0.4e`
https://www.curseforge.com/minecraft/mc-mods/create/files/3687358

**Comment by PepperCode1** [comment] 2022-03-16 21:14
This was indeed fixed in patch E. It was caused by some rendering code not applying the model view matrix after popping all transformations.
(Fixed in Creators-of-Create/Create@2211632f5c6cda15ebc4b8d6c8e335fc3bf9ab2c)

**Closed as completed** 2022-03-16 21:31 UTC
Labels: other mod
