### ISSUE TITLE
Crash while loading world, "ClassNotFoundException"

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#1679] opened 2019-08-15 16:13 UTC
I crash upon loading any of my worlds, and it only happens with JEI (It's my would-be only mod...)
Crash log:
https://gist.github.com/JohnVicres/8affd6f1a721125b87a9814a0f844490

I searched to see if other people had my issue, and most of them have insufficient ram. I checked if I got the same warning in my log, but instead found this:
--
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.event.TickEvent$ClientTickEvent
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:102) ~[modlauncher-3.0.2.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51] {}
	... 35 more
--
What the hell is that? I feel it's an issue with Forge, but it loads fine without JEI so... help?

**Comment by Ommina** [comment] 2019-08-15 19:02
Update Forge to 28.0.45 or later.  (I suppose downgrading JEI is an option as well, but it doesn't seem like a very good one.)

**Comment by mezz** [comment] 2019-08-19 01:42
Thanks for the report!
Yes, please update JEI and Forge to the latest versions.
This was caused by a breaking change in Forge and has been resolved.

**Comment by mezz** [comment] 2019-08-19 01:42
Duplicate of https://github.com/mezz/JustEnoughItems/issues/1663

**Closed as completed by mezz** 2019-08-19 01:42 UTC
Labels: duplicate
