### ISSUE TITLE
1.18 Weird Crash

### ISSUE THREAD

**Issue by itsdinkd** [mezz/JustEnoughItems#2594] opened 2021-12-11 03:45 UTC
opened up craft presence settings and then pressed another hotkey and my client crashed

https://pastebin.com/n5FFzBAB

**Comment by mezz** [comment] 2021-12-17 11:09
Thanks for the report!
This looks like a duplicate of https://github.com/mezz/JustEnoughItems/issues/2597

Maybe Craft Presence is making the same minor mistake as Xaero's mod? Please report this issue to Craft Presence and link them to these issues.

**Comment by itsdinkd** [comment] 2021-12-17 18:01
Looks like someone beat me to it a week ago

https://gitlab.com/CDAGaming/CraftPresence/-/issues/144

**Comment by CDAGaming** [comment] 2022-01-31 16:12
Hey there! After quite an extended break, I'll be pushing v1.8.9 within the next week to accomodate this fix (Cancelling the keyTyped event by returning true after my setScreen event)

This issue, which linked to Xaero's + an explanation of the cause was never linked to be in the aforementioned issue post, and I do apologize it's taken me quite some time to address this.

**Comment by CDAGaming** [comment] 2022-01-31 16:30
A temporary build has been published to https://gitlab.com/CDAGaming/CraftPresence/-/jobs/2035560497

If possible, @itsdinkd please let me know whether this jar resolves the issue, so I can then proceed with a v1.8.9 release.

**Comment by mezz** [comment] 2022-01-31 19:48
Thanks for the update @CDAGaming, I think that your fix should address the issue.

**Comment by CDAGaming** [comment] 2022-08-12 20:05
Reconfirmed from another ticket sent into me, rip

https://github.com/ClaudiusMinimus/Create_Potato_1.18.x/issues/7

**Comment by CDAGaming** [comment] 2022-08-12 20:08
Edit: As it turns out, I completly forgot about pushing a version with the fix, since I never received a confirmation that the build does in fact fix the issue, I'll be pushing v1.8.10 to resolve this shortly

**Comment by CDAGaming** [comment] 2022-08-12 21:49
This can now be closed as resolved, v1.8.10 is now releasing with the fix, alongside some other tweaks.

**Comment by mezz** [comment] 2022-08-12 21:50
Thanks!

**Closed as completed by mezz** 2022-08-12 21:50 UTC
Labels: other mod
