### ISSUE TITLE
1.11.2-4.3.6.282 ClassCastException ItemAir (Rendering Recipe Crash)

### ISSUE THREAD

**Issue by TwitchtvCarbs** [mezz/JustEnoughItems#871] opened 2017-05-28 04:38 UTC
Getting a strange rendering crash when shift clicking the + button
Also happens sometimes when simply just looking at recipes as well.

https://pastebin.com/P17uMWPZ

**Comment by mezz** [comment] 2017-05-28 04:53
Thanks for the report!
This seems to be an issue from [Vanilla Builders Extension](https://minecraft.curseforge.com/projects/vanilla-builders-extension/issues?filter-action=&filter-tag=), try reporting to them.

**Comment by TwitchtvCarbs** [comment] 2017-05-28 05:03
Oh whoops, sorry about that! I wasn't sure. Going to report to them now.

**Comment by mezz** [comment] 2017-05-28 05:21
No problem. I'll close this for now since I'm pretty sure JEI is not the cause.

**Closed as completed by mezz** 2017-05-28 05:21 UTC
Labels: other mod
