### ISSUE TITLE
Buffs Appear on wrong side (1.18.1)

### ISSUE THREAD

**Issue by Shadow212121** [mezz/JustEnoughItems#2608] opened 2021-12-14 00:28 UTC
![2021-12-13_18 16 08](https://user-images.githubusercontent.com/79116680/145910561-186af48c-a0e2-4df3-bc56-368d698f8254.png)
Buff is from Alex's Mobs

**Comment by mezz** [comment] 2021-12-17 11:02
Thanks for the report!
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/2588

**Closed as completed by mezz** 2021-12-17 11:02 UTC
Labels: duplicate
