### ISSUE TITLE
jei_1.12.2-4.16.1.300 have a problem with other mod!like NEI

### ISSUE THREAD

**Issue by chenshunglong** [mezz/JustEnoughItems#2064] opened 2020-08-23 13:55 UTC
there is a problem about  AppleSkin mod、crafttweaker jei support、 JER、moreoverlayys、NEI、random things、Tool belt.
The report says that the above mod lacked the right dependencies. 
I do not  good at the information about any mod.But I found that I remove the latest JEI ，the problem was gone. Just hope this message will help you. If not，I am sorry，please ignore this message.
 

![877](https://user-images.githubusercontent.com/70091796/90979798-0c21a300-e58a-11ea-8f46-a8de96c23b0c.PNG)

 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

**Comment by Valafi** [comment] 2020-08-23 20:47
Duplicate of #2060

**Comment by mezz** [comment] 2020-08-24 01:02
Thanks for the report!
This should be fixed in the next release.

**Closed as completed by mezz** 2020-08-24 01:02 UTC
