### ISSUE TITLE
Minecraft Crashing after Loading the World

### ISSUE THREAD

**Issue by skyant83** [mezz/JustEnoughItems#1692] opened 2019-08-21 03:33 UTC
### Every time I load up my world, I get an error and my game crashes. This is the error I get:

https://gist.github.com/SkyAnt83/4900edf0c621da1a6c390706433574a9

**Comment by mezz** [comment] 2019-08-21 04:07
Thanks for the report!
Please update JEI and Forge to the latest versions.
This was caused by a breaking change in Forge and has been resolved.

Duplicate of #1663

**Closed as completed by mezz** 2019-08-21 04:07 UTC
Labels: duplicate

**Comment by skyant83** [comment] 2019-08-21 04:20
Both forge and jei are updated to the most recent version

**Comment by mezz** [comment] 2019-08-21 04:25
The log shows you have `jei-1.14.4-6.0.0.9.jar` but the latest is `jei-1.14.4-6.0.0.10.jar`.
