### ISSUE TITLE
[Crash]: Forge 1.20.1 Mouse Moving

### ISSUE THREAD

**Issue by Djavidan17** [mezz/JustEnoughItems#3628] opened 2024-07-24 11:43 UTC
### Steps to Reproduce the Crash

1. No matter in which mode are you, open inventory tab
2. Move mouse towards JEI Area
3. Crash  happens

### Mod Pack Version (Optional)

1.20.1 Custom Modpack on the base of Create:Perfect World 2

### Extra Notes (Optional)
Following from other issues here, i assumed that this crash might be caused by Artifacts & Supplementaries. So I tried to reproduce crash without these mods, and it still crashes

_No response_

### Crash Report

https://gist.github.com/Djavidan17/82d08a741a5b4a81030638bc1dbd0e08

**Comment by mezz** [comment] 2024-07-24 23:49
Thanks for the report!
This is an especially difficult-to-read crash report because a mod is using Mixins on JEI and crashing.

Here is the most relevant part:
```
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [destroy.mixins.json:TooltipRendererMixin from mod destroy] from phase [DEFAULT] in config [destroy.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	... 49 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on inDrawHoveringText could not find any targets matching 'Lmezz/jei/common/gui/TooltipRenderer;drawHoveringText(Lnet/minecraft/client/gui/GuiGraphics;Ljava/util/List;IILjava/lang/Object;Lmezz/jei/api/ingredients/IIngredientRenderer;)V' in mezz.jei.common.gui.TooltipRenderer. Using refmap destroy.refmap.json [PREINJECT Applicator Phase -> destroy.mixins.json:TooltipRendererMixin from mod destroy -> Prepare Injections ->  -> handler$fpc000$destroy$inDrawHoveringText(Lnet/minecraft/client/gui/GuiGraphics;Ljava/util/List;IILjava/lang/Object;Lmezz/jei/api/ingredients/IIngredientRenderer;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
```

Based on this, it looks like the `destroy` mod is failing to apply a mixin to JEI, which causes a crash. 

This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/3594
The issue has been reported to `destroy` here: https://github.com/petrolpark/Destroy/issues/396

**Closed as not planned by mezz** 2024-07-24 23:49 UTC
Labels: other mod

**Comment by Djavidan17** [comment] 2024-07-25 10:15
> Thanks for the report!
> This is an especially difficult-to-read crash report because a mod is using Mixins on JEI and crashing.
> 
> Here is the most relevant part:
> ```
> Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [destroy.mixins.json:TooltipRendererMixin from mod destroy] from phase [DEFAULT] in config [destroy.mixins.json] FAILED during APPLY
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
> 	... 49 more
> Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on inDrawHoveringText could not find any targets matching 'Lmezz/jei/common/gui/TooltipRenderer;drawHoveringText(Lnet/minecraft/client/gui/GuiGraphics;Ljava/util/List;IILjava/lang/Object;Lmezz/jei/api/ingredients/IIngredientRenderer;)V' in mezz.jei.common.gui.TooltipRenderer. Using refmap destroy.refmap.json [PREINJECT Applicator Phase -> destroy.mixins.json:TooltipRendererMixin from mod destroy -> Prepare Injections ->  -> handler$fpc000$destroy$inDrawHoveringText(Lnet/minecraft/client/gui/GuiGraphics;Ljava/util/List;IILjava/lang/Object;Lmezz/jei/api/ingredients/IIngredientRenderer;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
> ```
> 
> Based on this, it looks like the `destroy` mod is failing to apply a mixin to JEI, which causes a crash. 
> 
> This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/3594
> The issue has been reported to `destroy` here: https://github.com/petrolpark/Destroy/issues/396

Hello, i tested this crash attempt on older version of JEI, 15.2.0.27, and it doesn't crash on this version
