### ISSUE TITLE
Cannot access the config menu?

### ISSUE THREAD

**Issue by switchmaxfx** [mezz/JustEnoughItems#2018] opened 2020-07-19 20:24 UTC
Using 1.15.2 and when i click the config menu nothing happens. I can toggle cheats on and off but not access the menu.

**Comment by wannesdemeyer** [comment] 2020-07-29 15:08
I have the same issue on 1.16.1 using JEI version 1.16.1-7.0.0.6 + Forge 32.0.80. When clicking while holding control I can toggle cheat mode, just like @gguy825, but normal clicking does nothing.

**Comment by mezz** [comment] 2020-08-02 00:16
Thanks for the report!
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/1526

**Closed as completed by mezz** 2020-08-02 00:16 UTC
Labels: duplicate
