### ISSUE TITLE
Not loading on 1.14.4 latest forge version not sure how to fix

### ISSUE THREAD

**Issue by Joe26** [mezz/JustEnoughItems#1666] opened 2019-08-08 20:46 UTC
Hi, I am very unknowledgeable when it comes to using mods manually and installing seperate so here goes. I'm using twitch launcher 1.14.4 with forge latest version however I am not sure why but it keeps crashing when loading world now I am not sure why as there is no other mod installed whilst I am trying to use it so was a bit curious to see what forge version on the twitch launcher I am meant to be using whilst using this mod even though it says its for 1.14.3

**Comment by Joe26** [comment] 2019-08-08 20:52
I know there is numerous posts about this but sadly most of the mods I am using at the moment require forge .45 minium so I am trying to balance what I need for mods but I am very appreciative of your work and support

**Comment by Joe26** [comment] 2019-08-08 20:57
Never mind I am stupid and misread a post your waiting for a bug fix for forge then you shall be updating and fixing the bug with JEI is that correct if so any idea how long like 4 months a year if not got any idea then that is ok I will just need to do without for now.

**Comment by Ommina** [comment] 2019-08-09 01:03
I feel like I'm only reading half of a conversation here.

At any rate, I would be very surprised if the present situation lasted more than a few weeks.  This is not a promise that it won't, just that I would be surprised if it did.  Stuff just needs to happen, but stuff needs to happen in place one before it can happen in place two.  But happen it will.

**Comment by nickolasdeluca** [comment] 2019-08-09 02:36
Hey, I know this is not the right place to ask but I don't where to, so... I was wondering how do I know which version of forge to use with JEI's 6.0.0.9 version?

**Comment by GiovaX9** [comment] 2019-08-09 03:29
🧐
boy or girl
update this fabulous mod, as people are starting to complain that you don't update the mod Just Enough Item mod (JEI) Mod
come on. you have to update the mod, that people want to play with this mod, from the minecraft version, from the. 1.13 to version 1.14.3. please update it

**Comment by Ommina** [comment] 2019-08-09 04:44
@GiovaX9 Please see https://github.com/mezz/JustEnoughItems/issues/1663#issuecomment-519380607 

In short, other fixes elsewhere must happen first.

**Comment by bloodconfetti** [comment] 2019-08-09 06:14
[crash-2019-08-09_00.13.33-server.txt](https://github.com/mezz/JustEnoughItems/files/3484997/crash-2019-08-09_00.13.33-server.txt)

**Comment by leeterry** [comment] 2019-08-09 18:38
@nickolasdeluca just start testing by going back to forge version 28.0.41 first. He had updated the mod here recently and had just finished the update around the time forge released the new version. Furthermore, he said the problem is with the 28.0.45 version of forge and therefore it is likely that the one he used was 28.0.41. If that fails go back 1 more and keep trying till you find it. Sadly, my mods wont work with older version of forge and so I am stuck here.

**Comment by Ommina** [comment] 2019-08-09 19:14
See #1667 

JEI 6.0.0.10 is available on Curse, which purports to work with Forge 28.0.45. Give that a go.

**Comment by nickolasdeluca** [comment] 2019-08-09 19:19
@leeterry I'm having the same problem, my other mods only work with 28.0.45, can't downgrade forge either.

@Ommina I'll give it a go, thanks for the heads up!

**Comment by mezz** [comment] 2019-08-10 04:43
Thanks for the report!

Please try not to pile on to an issue this way without checking the latest version. It creates some confusion about what's going on.

@Ommina has it right.
This has been fixed in JEI 6.0.0.10, available now.
It works with Forge 28.0.45. :)

**Closed as completed by mezz** 2019-08-10 04:43 UTC
Labels: duplicate
