### ISSUE TITLE
[Other]: JEI Fabric has remapping errors with IJeiFluidIngredient preventing it being used

### ISSUE THREAD

**Issue by AlphaMode** [mezz/JustEnoughItems#2891] opened 2022-07-13 23:46 UTC
### Other

![image](https://user-images.githubusercontent.com/26313415/178855491-1e117c9c-3138-4e8b-addf-6467d8ef18f8.png)
As seen in the image the classes don't get remapped this is preventing me from implementing fluids in jei

**Comment by mezz** [comment] 2022-07-14 00:35
Thanks for the report!
Can you show me your build.gradle setup? I'm curious how you are requiring JEI's API in gradle

**Comment by AlphaMode** [comment] 2022-07-14 01:02
https://github.com/Alpha-s-Stuff/TinkersConstruct/blob/457f49f8de92e70107ff8915555d9b340f2f6f9c/build.gradle#L130 I copied the wiki from here https://github.com/mezz/JustEnoughItems/wiki/Getting-Started-%5BJEI-10-or-higher-for-Forge-or-Fabric%5D

**Comment by mezz** [comment] 2022-07-14 04:42
Thanks for the extra info! That looks correct to me.
I will ask modmuss, a loom developer, for help.

@modmuss50 do you know if I am doing something wrong with the way I create the obfuscated jei-fabric-api jar, or if I am telling modders to use the wrong loom commands to include it in their project?

**Comment by TropheusJ** [comment] 2022-07-23 01:42
Noticed this is only the case for the API jar. It's correct for the full jar.

**Comment by modmuss50** [comment] 2022-07-31 18:11
Hi, sorry I only just saw this. (Poking me on discord is a better way to get in contact)

Is the API jar a mod with a fabric.mod.json file? Loom only remaps deps that have a fabric.mod.json file. Deps without are left untouched.

**Comment by mezz** [comment] 2022-08-05 23:06
The API jar is not its own mod, it's just a bunch of interface files. Should I declare it as its own mod?

**Comment by TelepathicGrunt** [comment] 2022-08-23 15:37
I am trying to use JEI in Quilt workspace. Same issue as above where JEI does not get the mc classes compiled correctly in JEI sources. However, if use the jar from curseforge instead by cursemaven, the source is now correct and I am able to extend IJeiFluidIngredient. Dunno if this may help with trying to figure out the cause
```
modCompileOnlyApi "curse.maven:jei-238222:3944625"
//modCompileOnlyApi "mezz.jei:jei-${libs.versions.jeimc.get()}-fabric:${libs.versions.jei.get()}"
```
Pic of JEI source from JEI maven:
![image](https://user-images.githubusercontent.com/40846040/186200806-1c44532b-aebf-4293-b695-7f6c05d7d25d.png)
Pic of JEI source from using CurseMaven to pull from CurseForge:
![image](https://user-images.githubusercontent.com/40846040/186200937-1ae498d4-3a11-4483-96cd-682b65ceb4bb.png)

**Comment by pixar02** [comment] 2022-09-27 15:19
Think the Issue is still happening, even though it's been cold for some time.
First Plugin creation step already has a problem. `public net.minecraft.resources.ResourceLocation getPluginUid()`
It actually errors at the path before the Actual ResourceLocation class which doesn't exit in Fabric.
build.gradle file:
![image](https://user-images.githubusercontent.com/7142721/192566771-a355e4e7-65c2-4a41-9682-2d7eeae66ca3.png)
gradle.properties
![image](https://user-images.githubusercontent.com/7142721/192566876-22356ae5-2396-4fd9-a7a5-a49616549734.png)

**Comment by solonovamax** [comment] 2024-05-27 22:30
The current workaround I am using (which isn't particularly nice) is I've got:
```kotlin
modCompileOnly("mezz.jei:jei-1.20.1-fabric:15.3.0.4") {
    exclude(group = "mezz.jei")
}
```
so, I depend on `jei-*-fabric` instead of `jei-*-fabric-api`, and then I exclude all the deps it tries to bring in, as it's already a fat jar.

**Comment by mezz** [comment] 2024-09-12 05:22
This has been resolved in https://github.com/mezz/JustEnoughItems/issues/3451
JEI publishes an intermediary-mapped common-api jar for fabric now.

**Closed as completed by mezz** 2024-09-12 05:22 UTC
Labels: bug
