### ISSUE TITLE
Unable to open config in 1.16.1

### ISSUE THREAD

**Issue by noahthomas2014** [mezz/JustEnoughItems#2013] opened 2020-07-15 16:05 UTC
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by mezz** [comment] 2020-08-02 00:16
Thanks for the report!
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/1526

**Closed as completed by mezz** 2020-08-02 00:16 UTC
Labels: duplicate
