### ISSUE TITLE
Crash Report: Refined Storage 1.0.5 and JEI 3.11.1.276

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#461] opened 2016-09-27 05:05 UTC
Minecraft: 1.10.2
Forge: 12.18.1.2094
Refined Storage: 1.0.5

I tested JEI versions listed below.
Crashes
JEI: 3.11.1.276
JEI: 3.11.1.275
JEI: 3.11.1.274
JEI: 3.11.1.273
JEI: 3.11.1.272
JEI: 3.11.1.271
JEI: 3.11.1.270
JEI: 3.11.1.229

Works
JEI: 3.10.0.268

JEI Bug report link: https://github.com/mezz/JustEnoughItems/issues/461
Refined Storage Bug report link: https://github.com/raoulvdberge/refinedstorage/issues/388
Crash Log: http://pastebin.com/R5M75Uk8
[gist](https://gist.github.com/BlakeDarwinXE/4fb402a409b738bb501cd6d02ca6e46e)

**Comment by mezz** [comment] 2016-09-27 05:16
Thanks for the report!
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/453
It has already been fixed in refined storage, but the update has not yet been released.
You can use JEI 3.10 in the meantime.

**Closed as completed by mezz** 2016-09-27 05:16 UTC
Labels: duplicate
