### ISSUE TITLE
[Bug]: Disconnection When Using Search Bar

### ISSUE THREAD

**Issue by SuperStefan97** [mezz/JustEnoughItems#3698] opened 2024-08-20 02:38 UTC
### Steps to Reproduce the Bug

1. Enter Any World old or new
2. Search for anything on the creative menu

### Expected Behavior

Search the item

### Actual Behavior

Disconnects me from singleplayer worlds

### latest.log

https://gist.github.com/SuperStefan97/a9da7b758da8aebb47607e007571b634

**Comment by mezz** [comment] 2024-08-28 13:24
Duplicate of https://github.com/mezz/JustEnoughItems/issues/3699

**Closed as not planned by mezz** 2024-08-28 13:24 UTC
