### ISSUE TITLE
Issue - Console Spam

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [mezz/JustEnoughItems#593] opened 2016-11-08 21:05 UTC
Console Spam - Client Side
https://gist.github.com/P3rf3ctXZer0/6e2373dc3eb6bb5e3c00a1912215e45a

**Comment by mezz** [comment] 2016-11-08 22:58
Thanks for the report!
This is a Tinker's issue, reported here: SlimeKnights/TinkersConstruct#2539
Duplicate of https://github.com/mezz/JustEnoughItems/issues/571

**Closed as completed by mezz** 2016-11-08 22:58 UTC
Labels: duplicate

**Comment by P3rf3ctXZer0** [comment] 2016-11-09 01:58
Even though it only started as of your latest version?
