### ISSUE TITLE
JEI creating empty config folder

### ISSUE THREAD

**Issue by RasutoK** [mezz/JustEnoughItems#1627] opened 2019-07-06 03:50 UTC
JEI creating empty config folder and clicking the wrench in-game does nothing. UI shows up in game, I just can't config the mod.
![explorer_XyLtgJ6Vj7](https://user-images.githubusercontent.com/52589557/60751180-1b552400-9f77-11e9-978e-8885b898ff58.png)
![javaw_SuwKA43LqD](https://user-images.githubusercontent.com/52589557/60751185-1ee8ab00-9f77-11e9-876a-efeb62839616.png)
![explorer_9aFLUuwjQb](https://user-images.githubusercontent.com/52589557/60751187-2445f580-9f77-11e9-870c-23794d2f2f9a.png)

**Comment by mezz** [comment] 2019-07-09 20:42
Thanks for the report!
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/1526
JEI doesn't have proper config files in the latest versions, I am waiting for Forge to finish the config GUI code.

**Closed as completed by mezz** 2019-07-09 20:42 UTC
Labels: duplicate
