### ISSUE TITLE
[1.12.2] Crashes Forge MDK Test Client on Startup

### ISSUE THREAD

**Issue by KaktuszSok** [mezz/JustEnoughItems#2009] opened 2020-07-13 03:38 UTC
I'm having no luck trying to add JEI to my test environment, however it works just fine in a clean MultiMC instance with my built mod and JEI added. Whenever I run minecraft from eclipse with jei in the /run/mods folder, I get this crash on JEI registering a texture: https://gist.github.com/KaktuszSok/4d19fa6ac338cd3093dc983b47258db8

I also tried following the guide to adding JEI through my build.gradle. After changing a - to a _, running gradlew build works fine. However, running gradlew eclipse does not add JEI to my referenced libraries automatically (as is seen in a video from 2018 when using setupDecompWorkspace). JEI also does not get added to the test client automatically even after running genEclipseRuns.

If I add the JEI jar manually to the build path, it crashes minecraft on startup with the same message as in the log above.

How do I add JEI to my test client and IDE without causing a crash? Here is my build.gradle:
https://gist.github.com/KaktuszSok/14f63a4bfe8cb9b692ee44e19c9939f0
gradle.properties:
https://gist.github.com/KaktuszSok/277bcf43040e5082f211af1449aa827f

Using the JEI files which gradle downloads to the user folder and caches does not help.
Thanks in advance

EDIT: I don't know what tf I did but the jei jars are now visible in the IDE. I still get the crash on startup though.

EDIT 2: This seems related to https://github.com/mezz/JustEnoughItems/issues/1512, though that's for 1.13.2. Do I have to change to forge 2847 i.e. FG2.3 to use jei in my test runtime environment?

**Comment by basdxz** [comment] 2020-07-16 07:50
Having the same issues, it seems like this is also the same thing that was happening on #1962, #1960 and #1959. 
From what I've gathered, the pull #1963 was intended to port JEI 1.12.2 to FG3 along with getting the access transformers working again, which seems to be the issue if you want to use FG3. 
Mezz did work on https://github.com/mezz/JustEnoughItems/tree/1.12-FG3 to get FG3 working, but was stuck on getting the resources to load, my pull #2015 fixes that small issue.
However, even with said changes I get the identical crash. Using JEI compiled from my own fork https://github.com/basdxz/JustEnoughItems/tree/1.12-FG3 using the 'build' gradle run to get the artifacts and put them in my local libs.
If anyone familiar with JEI/ATs has a moment I would love some help

**Comment by basdxz** [comment] 2020-07-17 12:39
Alright I got it to work, FG3+ doesn't passthrough ATs it seems. If you manually add the JEI ATs into your mod it works flawlessly with the latest builds off the maven.

**Comment by mezz** [comment] 2020-08-02 00:13
Thanks for the help @basdxz 
This should be fixed on the latest version (JEI 4.16.0) for 1.12.2

**Closed as completed by mezz** 2020-08-02 00:13 UTC
