### ISSUE TITLE
Incompatibility issue with liteloader

### ISSUE THREAD

**Issue by Sir-Will** [mezz/JustEnoughItems#1243] opened 2018-05-22 21:54 UTC
When liteloader is installed the game crashes with this report:
(jei_1.12.2-4.9.1.179)
```
java.lang.IllegalArgumentException: recipeCategories must not be empty.
	at mezz.jei.util.ErrorUtil.checkNotEmpty(ErrorUtil.java:201)
	at mezz.jei.gui.ingredients.IngredientLookupState.<init>(IngredientLookupState.java:23)
	at mezz.jei.gui.recipes.RecipeGuiLogic.<init>(RecipeGuiLogic.java:34)
	at mezz.jei.gui.recipes.RecipesGui.<init>(RecipesGui.java:83)
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:85)
	at mezz.jei.startup.ProxyCommonClient.lambda$loadComplete$0(ProxyCommonClient.java:116)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:131)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:112)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:814)
	at com.mumfrey.liteloader.client.ResourcesClient.refreshResources(ResourcesClient.java:45)
	at com.mumfrey.liteloader.client.LiteLoaderEventBrokerClient.onStartupComplete(LiteLoaderEventBrokerClient.java:275)
	at net.minecraft.client.Minecraft.handler$onStartupComplete$zzh000(Minecraft.java:3390)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:569)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at mezz.jei.util.ErrorUtil.checkNotEmpty(ErrorUtil.java:201)
	at mezz.jei.gui.ingredients.IngredientLookupState.<init>(IngredientLookupState.java:23)
	at mezz.jei.gui.recipes.RecipeGuiLogic.<init>(RecipeGuiLogic.java:34)
	at mezz.jei.gui.recipes.RecipesGui.<init>(RecipesGui.java:83)
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:85)
	at mezz.jei.startup.ProxyCommonClient.lambda$loadComplete$0(ProxyCommonClient.java:116)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:131)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:112)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:814)
	at com.mumfrey.liteloader.client.ResourcesClient.refreshResources(ResourcesClient.java:45)
	at com.mumfrey.liteloader.client.LiteLoaderEventBrokerClient.onStartupComplete(LiteLoaderEventBrokerClient.java:275)
	at net.minecraft.client.Minecraft.handler$onStartupComplete$zzh000(Minecraft.java:3390)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:569)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by Tkain** [comment] 2018-05-26 20:52
Can confirm this still occurs in jei_1.12.2-4.9.1.192.

**Comment by mezz** [comment] 2018-05-26 22:08
Thanks for the report!
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/1189
I have not been able to find the root cause of this issue yet.

**Closed as completed by mezz** 2018-05-26 22:08 UTC
Labels: duplicate
