### ISSUE TITLE
JEI causes NoClassDefFoundError on MC 1.10.2 Forge 12.18.1.2095

### ISSUE THREAD

**Issue by SteamDragon** [mezz/JustEnoughItems#492] opened 2016-10-03 21:04 UTC
I'm currently using jei_1.10.2-3.12.3.293 on minecraft 1.10.2 with forge-1.10.2-12.18.1.2095 and sometimes during play i got crashed with exception

```
 [00:56:47] [Client thread/FATAL]: Unreported exception thrown!
java.lang.NoClassDefFoundError: mezz/jei/gui/MasterFocus
    at me.superckl.jet.handler.RenderTickHandler.resetGuiLogic(RenderTickHandler.java:284) ~[RenderTickHandler.class:?]
    at me.superckl.jet.handler.RenderTickHandler.checkLastItem(RenderTickHandler.java:275) ~[RenderTickHandler.class:?]
    at me.superckl.jet.handler.RenderTickHandler.onRenderTick(RenderTickHandler.java:76) ~[RenderTickHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_553_RenderTickHandler_onRenderTick_Pre.invoke(.dynamic) ~[?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168) ~[EventBus.class:?]
    at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:884) ~[GuiIngameForge.class:?]
    at net.minecraftforge.client.GuiIngameForge.renderCrosshairs(GuiIngameForge.java:215) ~[GuiIngameForge.class:?]
    at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:146) ~[GuiIngameForge.class:?]
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1072) ~[bnz.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076) ~[bcx.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

When i trying to run without JEI all seems fine, but i want to use JEI 
Crash report:
https://gist.github.com/SteamDragon/7bfd6727df552d3c3b7974b24146ccb9

**Comment by GirafiStudios** [comment] 2016-10-03 21:05
Caused by Just Enough Tooltips

**Comment by mezz** [comment] 2016-10-03 21:25
Thanks for the report!
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/483

**Closed as completed by mezz** 2016-10-03 21:25 UTC
Labels: duplicate

**Comment by SteamDragon** [comment] 2016-10-03 21:28
Thanks for the fast answer
