### ISSUE TITLE
1.14.3 Config and Cheats

### ISSUE THREAD

**Issue by AstragoDE** [mezz/JustEnoughItems#1634] opened 2019-07-10 14:12 UTC
The Config is not opening. (leftclick on wrence)
Cheats dont work on servers

Using newest version

**Comment by GirafiStudios** [comment] 2019-07-10 14:14
Duplicate of https://github.com/mezz/JustEnoughItems/issues/1526

**Comment by AstragoDE** [comment] 2019-07-10 14:14
right sry

**Closed as completed** 2019-07-10 19:03 UTC
Labels: duplicate
