### ISSUE TITLE
JEI crashes the game on startup of certain world

### ISSUE THREAD

**Issue by Alex1331xela** [mezz/JustEnoughItems#1748] opened 2019-10-02 01:45 UTC
Minecraft Version: 1.14.4
Forge Version: 28.1.26
JEI Version: 6.0.0.13

When trying to start the world, JEI crashes the game on world startup. It might be relevant that JEI was working fine with the world back on Forge v28.0.45 - v28.0.58.

Crash log:
[hs_err_pid20036.log](https://github.com/mezz/JustEnoughItems/files/3679104/hs_err_pid20036.log)

**Comment by Alex1331xela** [comment] 2019-10-04 01:34
Update: I've narrowed down the problem to be between JEI and the resource pack I'm using, Vanilla Tweaks. This resource pack changes textures, sounds, and models; I'm not sure which causes the issues with JEI.

Here is the texture pack, hopefully this can help:
[VanillaTweaks_r895342.zip](https://github.com/mezz/JustEnoughItems/files/3688629/VanillaTweaks_r895342.zip)

**Comment by TehNut** [comment] 2019-10-04 01:50
https://github.com/mezz/JustEnoughItems/issues/1698

**Comment by TheSnowyChickens** [comment] 2019-10-05 22:27
Same bug here. xD

**Comment by mezz** [comment] 2019-10-07 04:07
Thanks for the report!
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/1698
I will close this issue, please follow the other one so everything is together.

**Closed as completed by mezz** 2019-10-07 04:07 UTC
Labels: duplicate
