### ISSUE TITLE
[Crash]: when trying to view the recipes on the potions table, the game crashes; jei-1.20.1-forge-15.8.0.19

### ISSUE THREAD

**Issue by 0Trinster0** [mezz/JustEnoughItems#3639] opened 2024-07-28 12:47 UTC
### Steps to Reproduce the Crash

1. I select a random potion in the jei mod menu, the potions tab is enabled
2. when I click on the option to look at other recipes, the game crashes.
![2024-07-28_07 41 05](https://github.com/user-attachments/assets/39e40ae8-e6ad-4c37-8758-3cfc4d17ba88)

### Extra Notes (Optional)

additionally I will leave you the log for further information
[latest.log](https://github.com/user-attachments/files/16403781/latest.log)

### Crash Report

https://gist.github.com/0Trinster0/0398addf3f88f293eaa378ac6d9fedc3#file-gistfile1-txt

**Comment by alfaceafc** [comment] 2024-07-28 18:38
Sorry if the translation is not very good, I don't speak English and I'm using google translate. 
I have a similar issue, when hovering over two specific items in the Silent Gear mod, blueprint pack and blueprint paper, the game crashes and closes. This also happens when I place the recipe items on the grid and place the cursor over the desired item, the game crashes before I even click, then closes the game. 
Detail, after the crash the game saves progress before closing.

[crash-2024-07-28_11.02.45-client.txt](https://github.com/user-attachments/files/16404858/crash-2024-07-28_11.02.45-client.txt)

**Comment by mezz** [comment] 2024-07-29 02:17
Thanks for the report!
This will be fixed in the next version, released shortly.

**Comment by alfaceafc** [comment] 2024-07-30 11:28
Congratulations for the readiness and agility in seeking a solution to our problem. 

I updated the mod as soon as it came out and tested it, but the problem persists, however I did some tests and noticed that the problem is only happening in the mod package I created. I created a new world in the modification package I made to check if it was a bug related to the map, but it also gave an error. I tested it on ATM 9 To the sky and this error does not happen, I also made a new package of modifications only with JEI and Silent Gear and it did not present the error. 

I believe that some mod from the mod pack I created is the cause of the problem. 

Thank you very much!

**Comment by mezz** [comment] 2024-07-31 06:25
Thank you for your kind reply.
Can you please upload a new crash log and client log here so that I can take a look at the new error?

**Comment by alfaceafc** [comment] 2024-07-31 23:33
Sorry but unfortunately I deleted the modpack that was giving the errors and all the logs were deleted along with it.

**Comment by mezz** [comment] 2024-08-01 04:03
Ok thanks for letting me know. 
I will close this issue for now. 
Please open a new issue if you run into the problem again.

**Closed as completed by mezz** 2024-08-01 04:03 UTC
Labels: bug
