### ISSUE TITLE
Minecraft caught exception with Just Enough Items

### ISSUE THREAD

**Issue by RaidingPanda24** [mezz/JustEnoughItems#1187] opened 2018-04-14 02:01 UTC
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)
This happened when I tried to load a mod pack I was working on that had jei and nei installed.

**Comment by KnightMiner** [comment] 2018-04-14 04:16
You are going to need more information than that.  Either post a crash report, or of there is none game logs. Use pastebin or gist.github.com in either case

**Comment by RaidingPanda24** [comment] 2018-04-14 04:17
[crash-2018-04-13_20.54.55-client.txt](https://github.com/mezz/JustEnoughItems/files/1909989/crash-2018-04-13_20.54.55-client.txt)

**Comment by HenryLoenwind** [comment] 2018-04-14 20:22
-> https://github.com/MinecraftForge/MinecraftForge/issues/4865

**Comment by mezz** [comment] 2018-04-14 21:00
Thanks for the report!
Looks like this was fixed in the latest Forge, you can solve the problem by updating your version of Forge.

**Closed as completed by mezz** 2018-04-14 21:00 UTC
Labels: forge

**Comment by MasterAden52** [comment] 2018-10-30 23:37
I updated my forge, but I still got the error. please help!

Crash Report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 10/30/18 7:36 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Not Enough Items (nei)
Caused by: java.lang.IllegalAccessError: tried to access class net.minecraft.potion.PotionHelper$MixPredicate from class codechicken.nei.util.helper.potion.PotionRecipeHelper
	at codechicken.nei.util.helper.potion.PotionRecipeHelper.init(PotionRecipeHelper.java:60)
	at codechicken.nei.init.NEIInitialization.bootNEI(NEIInitialization.java:70)
	at codechicken.nei.proxy.ProxyClient.loadComplete(ProxyClient.java:54)
	at codechicken.nei.NotEnoughItems.loadComplete(NotEnoughItems.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:752)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 665176376 bytes (634 MB) / 1476395008 bytes (1408 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2772 Optifine OptiFine_1.12.2_HD_U_E2 23 mods loaded, 23 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State   | ID                  | Version                  | Source                                        | Signature                                |
	|:------- |:------------------- |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJA  | minecraft           | 1.12.2                   | minecraft.jar                                 | None                                     |
	| UCHIJA  | mcp                 | 9.42                     | minecraft.jar                                 | None                                     |
	| UCHIJA  | FML                 | 8.0.99.99                | forge-1.12.2-14.23.5.2772.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA  | forge               | 14.23.5.2772             | forge-1.12.2-14.23.5.2772.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA  | bibliocraft         | 2.4.5                    | BiblioCraft-Mod-1.12.2.jar                    | None                                     |
	| UCHIJA  | buildcraftlib       | 7.99.18                  | buildcraft-7.99.18.jar                        | None                                     |
	| UCHIJA  | buildcraftcore      | 7.99.18                  | buildcraft-7.99.18.jar                        | None                                     |
	| UCHIJA  | buildcraftbuilders  | 7.99.18                  | buildcraft-7.99.18.jar                        | None                                     |
	| UCHIJA  | buildcraftenergy    | 7.99.18                  | buildcraft-7.99.18.jar                        | None                                     |
	| UCHIJA  | buildcraftfactory   | 7.99.18                  | buildcraft-7.99.18.jar                        | None                                     |
	| UCHIJA  | buildcraftrobotics  | 7.99.18                  | buildcraft-7.99.18.jar                        | None                                     |
	| UCHIJA  | buildcrafttransport | 7.99.18                  | buildcraft-7.99.18.jar                        | None                                     |
	| UCHIJA  | buildcraftsilicon   | 7.99.18                  | buildcraft-7.99.18.jar                        | None                                     |
	| UCHIJA  | cfm                 | 5.15.0                   | cfm-5.15.0-mc1.12.2.jar                       | None                                     |
	| UCHIJA  | codechickenlib      | 3.2.0.345                | CodeChickenLib-1.12.2-3.2.0.345-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA  | waila               | 1.8.26                   | Hwyla-Mod-1.12.2.jar                          | None                                     |
	| UCHIJA  | inventorytweaks     | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJA  | jei                 | 4.12.1.217               | jei_1.12.2-4.12.1.217.jar                     | None                                     |
	| UCHIJA  | malisiscore         | 1.12.2-6.4.0             | malisiscore-1.12.2-6.4.0.jar                  | None                                     |
	| UCHIJA  | malisisdoors        | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                 | None                                     |
	| UCHIJA  | radixcore           | 1.12.x-2.2.1             | RadixCore-1.12.x-2.2.1-universal.jar          | None                                     |
	| UCHIJA  | mca                 | 1.12.2-5.3.1             | Minecraft-Comes-Alive-Mod-1.12.2.jar          | None                                     |
	| UCHIJEE | nei                 | 2.4.1                    | NotEnoughItems-1.12.2-2.4.1.238-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |

	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 391.35' Renderer: 'GeForce GTX 660 Ti/PCIe/SSE2'
	OptiFine Version: OptiFine_1.12.2_HD_U_E2
	OptiFine Build: 20180728-185429
	Render Distance Chunks: 32
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Chocapic13 V7 High.zip
	OpenGlVersion: 4.6.0 NVIDIA 391.35
	OpenGlRenderer: GeForce GTX 660 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by mezz** [comment] 2018-11-04 19:43
@MasterAden52 `Caught exception from Not Enough Items (nei)`
Please report that to NEI here https://github.com/TheCBProject/NotEnoughItems/issues
