### ISSUE TITLE
[Bug]: Common-API is not published with intermediate mappings (Fabric)

### ISSUE THREAD

**Issue by ICY105** [mezz/JustEnoughItems#3451] opened 2024-03-04 17:15 UTC
### Steps to Reproduce the Bug

Implement JEI in a fabric mod that is not using parchment mappings. The fabric example mod is sufficient.

### Expected Behavior

Adding JEI to a project should remap the API to your project's mappings. 

### Actual Behavior

Remapping works for the fabric-api, however the common-api does not have intermediate mappings and is stuck on parchment. For example, the method `getPluginUid()`, claims to require the return type `net.minecraft.resources.ResourceLocation` which doesn't exist, instead of `net.minecraft.util.Identifier` which is the same class under Yarn mappings.

**Comment by JongWasTaken** [comment] 2024-06-12 11:36
This issue is still not resolved on version 15.3.0.7, making it impossible to use this API with yarn mappings (unless there is a way to remap it by myself?).

**Comment by mezz** [comment] 2024-06-17 10:29
Thanks for the report!
I ran into limitations in the tools I use when trying to publish this jar. 
I opened an issue with VanillaGradle some time ago here: https://github.com/SpongePowered/VanillaGradle/issues/69
I'll ping them in the issue there to see what the current status is.

**Comment by sshcrack** [comment] 2024-07-14 17:02
So the only way to support JEI is to switch to mojmaps?

**Comment by mezz** [comment] 2024-09-03 13:42
I might have finally been able to fix this simply, here: https://github.com/mezz/JustEnoughItems/commit/d05376b3e901e918ef1cc51bd864f11e35884995
Please try out JEI version `19.16.4.165` for minecraft `1.21.1` and let me know how it goes.

**Comment by mezz** [comment] 2024-09-08 11:04
This is still an issue but I think I have a way forward. 
I have moved off of VanillaGradle and the new toolchain should have a way to support this.

**Comment by mezz** [comment] 2024-09-09 02:25
This has been fixed in JEI for 1.21.1 (`19.17.0`+) and 1.20.1 (`15.18.0`+)
Please depend on the fabric api this way:
```kotlin
modImplementation("mezz.jei:jei-${minecraft_version}-fabric-api:${jei_version}")
modRuntimeOnly("mezz.jei:jei-${minecraft_version}-fabric:${jei_version}")
```
and it will pull in an intermediary mapping version of common-api automatically.

If you have a multi-project and want to depend on the intermediary mapping version of common-api directly, you can do it with
```kotlin
modImplementation("mezz.jei:jei-${minecraft_version}-common-api-intermediary:${jei_version}")
```
(all this is visible on the maven, for example here's 1.21.1: https://maven.blamejared.com/mezz/jei/jei-1.21.1-common-api-intermediary/)

**Closed as completed by mezz** 2024-09-09 02:25 UTC
Labels: bug

**Comment by unilock** [comment] 2024-12-02 06:47
`common-api-intermediary` v15.20.0.105 (1.20.1) doesn't appear to be mapped to Intermediary...

<img width="740" alt="image" src="https://github.com/user-attachments/assets/ec2d792e-aafd-48d1-986b-7967e8318d10">

**Comment by mezz** [comment] 2024-12-02 06:53
Hmm it look fine to me, please check your gradle setup @unilock.
The file is here: https://maven.blamejared.com/mezz/jei/jei-1.20.1-common-api-intermediary/15.20.0.105/jei-1.20.1-common-api-intermediary-15.20.0.105.jar

And here are the contents: 
![Screenshot 2024-12-02 at 3 51 24 PM](https://github.com/user-attachments/assets/4f9e319f-0e35-4dd5-8522-8c6b71f61369)

I checked and the source jar looks correct too

**Comment by unilock** [comment] 2024-12-05 00:37
Hmm, decompiling the jar manually does show the correct Intermediary mappings... maybe clearing the Gradle caches would've fixed it? I don't have that development environment set up at the moment, anyway.

**Comment by VityaSchel** [comment] 2025-04-12 22:12
> `common-api-intermediary` v15.20.0.105 (1.20.1) doesn't appear to be mapped to Intermediary...
> <img alt="image" width="740" src="https://private-user-images.githubusercontent.com/11802133/391437848-ec2d792e-aafd-48d1-986b-7967e8318d10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQ0OTIxODQsIm5iZiI6MTc0NDQ5MTg4NCwicGF0aCI6Ii8xMTgwMjEzMy8zOTE0Mzc4NDgtZWMyZDc5MmUtYWFmZC00OGQxLTk4NmItNzk2N2U4MzE4ZDEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDEyVDIxMDQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5NDExYTg3NDk4NjNkMjEwM2EwYTY1NTdlNDQ0ZjJmNTJmZGM2NGNlODIzMGExNWEyMzdlY2NjNGIzZGUxYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yAEQ0NKxSXygOtHVD0ObrdaorGu7y1ugsV8btt_s7ZQ">

This didn't help me:(

I had this problem with ResourceLocation not existing because I'm using yarn mappings in vscode. After upgrading jei_version to 15.18.0.83 in gradle.properties (my mod uses 1.20.1 minecraft version, I found matching version number of JEI here https://maven.blamejared.com/mezz/jei/) and updating classpath through java extension I still had previous jei version in definitions. So when I ran `Java: Clean Java Language Server Workspace` command through command palette which deleted gradle cache to install newer jei version with fixed mappings and then `./gradlew` in terminal, after following to IModPlugin definition I could finally see compatible mappings!! like this: `Identifier getPluginUid();`

But vscode cached this error and kept saying `getPluginUid() in MyModJEIPlugin cannot implement getPluginUid() in IModPlugin  return type Identifier is not compatible with ResourceLocation` despite IModPlugin not even having ResourceLocation at all. I ran `Java: Clean Java Language Server Workspace`, then `./gradlew genSources`. At this point everything suddenly stopped working at all and minecraft imports couldn't be resolved anymore. Removing caches and reinstalling everything didn't help, I also ran `./gradlew --refresh-dependencies` which didn't resolve the issue. I tried running `Java: Clean Java Language Server Workspace` again, then immediatelly closed vscode, ran `rm -rf ~/.gradle .gradle bin build run` to start from beginning and opened vscode again which downloaded gradle for 5th time in 24 hours to my computer and dependencies, then after restarting vscode several times I ran client but was presented with an error again: `Caused by: java.lang.IllegalAccessError: class net.minecraft.registry.SimpleRegistry tried to access method 'void net.minecraft.registry.entry.RegistryEntry$Reference.setRegistryKey(net.minecraft.registry.RegistryKey)' (net.minecraft.registry.SimpleRegistry and net.minecraft.registry.entry.RegistryEntry$Reference are in unnamed module of loader 'knot' @2a742aa2)`. I ran `./gradlew vscode` which seems to reinstall loom again for some reason, then reverted changes to launch.json made by this command. Now I started client but was presented with:

```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'jei' at 'mezz.jei.fabric.JustEnoughItems'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
        at knot//net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:514)
        at knot//net.minecraft.client.main.Main.main(Main.java:188)
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
        at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
        at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/resources/ResourceLocation
        at knot//mezz.jei.api.recipe.RecipeType.create(RecipeType.java:17)
        at knot//mezz.jei.common.Constants.<clinit>(Constants.java:14)
        at knot//mezz.jei.fabric.network.ServerNetworkHandler.registerServerPacketHandler(ServerNetworkHandler.java:11)
        at knot//mezz.jei.fabric.JustEnoughItems.onInitialize(JustEnoughItems.java:17)
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
        ... 7 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.resources.ResourceLocation
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        ... 12 more
```
I confirmed version of jei in the code and also it seems that the definition of IModPlugin has Identifier getPluginUid(); so it should compile, but it doesn't. I also tried `./gradlew build` just in case but was met with `error: package net.minecraft.client.render.entity.model does not exist
  import net.minecraft.client.render.entity.model.EntityModelLayer;` yet again. I'm kinda out of ideas how ~~java can be so fucking bad at resolving dependencies~~ to fix this, I restarted vscode again, didn't help.

**Comment by VityaSchel** [comment] 2025-04-12 23:20
Alright I found the issue that's causing `Caused by: java.lang.NoClassDefFoundError: net/minecraft/resources/ResourceLocation`, it's because of some change in JEI versions.

I was actually fine with 15.2.0.22 but since it didn't support yarn mappings I found this issue and mezz answer about fix introduced in 15.18.0+ for 1.20.1 so I obviously needed to update to it...

|JEI version|Does it run for me|
|---|---|
|15.2.0.22|✅|
|15.3.0.1|✅|
|15.17.0.74|✅|
|15.18.0.78|✅|
|15.18.0.79|❌|
|15.18.0.80|❌|
|15.18.0.82|❌|
|15.18.0.83|❌|

So 15.18.0.79 introduced some kind of bug that crashes minecraft :/ 

I'm not a java developer so please guide me on how to upgrade to newer versions of jei for 1.20.1 but from my developer experience I might just take a guess that you previously had mojang mappings (net/minecraft/resources/ResourceLocation) as some kind of dependency after migrating from them to intermediate isomorphic mappings? and so all versions of 15.18 up to 15.18.0.78 included it, which is why there is no error because gradle pulls it to my project as part of jei dependencies, but starting with 15.18.0.79 perhaps you realized it's no longer needed because jei now uses common mappings? but why does it crash? I couldn't find commit that marked 15.18.0.79 version release so I can't really know what exactly happened, I could only find commit that published 15.18.0, so if you happen to find the commit link that made changes in this version, let me know pls

**Comment by VityaSchel** [comment] 2025-04-13 14:51
update: I switched from vscode to intellij idea community edition and everything works perfectly, even with 15.20.0.106

**Comment by unilock** [comment] 2025-04-14 15:00
I've heard elsewhere that the issue with JEI's Intermediary jar not getting remapped is related to it not including a `fabric.mod.json`.
