### ISSUE TITLE
Hiding items issue

### ISSUE THREAD

**Issue by DrDarkfire** [mezz/JustEnoughItems#672] opened 2016-12-25 13:28 UTC
Hiding items in JEI is nice, but when I go to hiding items, anything that has a tag on the end and using the same base ID it hides all of them. For example <agricraft:water_channel_full>.withTag({agri_material_meta: 13, agri_material: "forestry:planks.0"})
<agricraft:water_channel_full>.withTag({agri_material_meta: 9, agri_material: "forestry:planks.fireproof.0"})
I would like to hide each individual one of these from within the mod instead of all of them at once.

**Comment by mezz** [comment] 2018-05-26 21:44
Closing as a duplicate of https://github.com/mezz/JustEnoughItems/issues/608
Unfortunately with the way item subtypes work, I think I am not going to be able to fix this simply until 1.13.

**Closed as completed by mezz** 2018-05-26 21:44 UTC
Labels: duplicate
