### ISSUE TITLE
[1.12][4.6.0.61] Crash if changing key bindings

### ISSUE THREAD

**Issue by mcenderdragon** [mezz/JustEnoughItems#897] opened 2017-06-13 14:08 UTC
It seems like the game crashen if you try to change the key bindings. 
```
java.lang.NullPointerException: Updating screen events
	at net.minecraft.client.settings.KeyBinding.compareTo(KeyBinding.java:162)
```

I think this is because KeyBindings have now a Map were they put a Striung and an int to sort them, and if JEI doesnt register its category it causes a NPE.

**Comment by mezz** [comment] 2017-06-17 21:01
Thanks for the report!
This is a duplicate of #893
This was a Forge bug (MinecraftForge/MinecraftForge#3985) and has been fixed in the latest version.

**Closed as completed by mezz** 2017-06-17 21:01 UTC
Labels: duplicate
