### ISSUE TITLE
[Bug]: Items in JEI are completely jumbled

### ISSUE THREAD

**Issue by katubug** [mezz/JustEnoughItems#3731] opened 2024-09-02 13:52 UTC
### Steps to Reproduce the Bug

I just installed jei-1.20.1-forge-15.17.0.74.jar to my modded instance, started the game, and opened my inventory.

### Expected Behavior

I expected the items to be sorted by mod.

### Actual Behavior

https://i.imgur.com/wl53lPc.png absolute chaos lol

### latest.log

https://gist.github.com/katubug/1e40e7b26d612fb468b89f9c9d7e2c9f

**Comment by Kamiinaz** [comment] 2024-09-02 15:00
I'm having the exact same issue ever since the update:
![image](https://github.com/user-attachments/assets/84f1cfeb-a6b2-4eee-8ed1-03d2b934b6a6)

Sorting configuration is still default:
![image](https://github.com/user-attachments/assets/4dc80ac1-e503-4dbb-90ca-49f9f034acbc)

**Comment by mezz** [comment] 2024-09-03 10:58
Thanks for the report!
Unfortunately I am not able to reproduce this issue if only JEI is installed.
Can you please try removing mods to see which one could be causing a conflict? I can help solve the issue from there.

**Comment by lozovoyDanil** [comment] 2024-09-04 13:28
I also had this issue, so after I deleted two random mods (which happened to be [Trowel](https://modrinth.com/mod/trowel) and [Fabric Language Kotlin](https://modrinth.com/mod/fabric-language-kotlin), required by Trowel), the issue was resolved. However, I couldn't reproduce the problem again; even after adding these mods back, JEI sorting worked correctly. So, maybe these two mods aren't the problem. JEI version 19.16.4.165 for Fabric 1.21.1

**Comment by moninformateur** [comment] 2024-09-04 18:34
Same issue here. I do not have the Trowel and Fabric Kotlin installed. This happened directly after update to 15.17.0.76. Reverting to previous versions fixes the issue.

**Comment by xd4rkzghost01** [comment] 2024-09-04 19:56
Also Happend in my modpack (build my own). I also dont have these mods but when running the game the 1st time i open my inventory it was all good, but after couple minute (surely open/close inv. while mining) i realise my JEI was all mix up.
Edit: i have Kotlin but for forge.

**Comment by mezz** [comment] 2024-09-05 00:52
It seems like another mod is conflicting with JEI or causing an issue here.
So far nobody has been able to identify what's conflicting.
Please try removing mods to figure out which one is causing a problem.
Once you have narrowed things down, I can help debug or find the right place to report to.

**Comment by katubug** [comment] 2024-09-05 01:57
After I have done a binary search of my entire mods folder... it's nothing. It's just fine, now. Nothing else changed. I don't know if it was fixed in one of the last 2 updates, or if it was just a weird blip on my end, but it's working so... shrug.

I'm not sure if you want to close this or see if another reporter has any findings, but as far as I'm concerned, it's resolved.

**Comment by Kamiinaz** [comment] 2024-09-05 14:53
I've just noticed I don't have this issue on my singleplayer world with the exact same modlist.
But on my server the issue persists.

Modlist is the same, with the same game and mod versions, but fabric version was not (server fabric launcher was 0.16.0 while client is **0.16.3**)

JEI Version was **jei-1.20.1-fabric-15.17.0.74**.

1. I updated the server fabric version to **0.16.3** as well as JEI to **jei-1.20.1-fabric-15.17.0.76**, to match my client.
2. The issue still persisted on the server, but all is well in my singleplayer world still.
3. Started testing with the mods. Did a reverse search: Disabled every single mod except JEI and the Fabric API.
4. Started testing on a new test world (on the server) without any datapacks or old mod dependencies.
5. The problem still persists. Pasting screenshot and server log, if it helps:
![image](https://github.com/user-attachments/assets/4ad371f6-f694-4d87-9144-8f15d133b417)

Server log:

```
C:\Users\Miguel Sousa\Downloads\Minecraft Server>java -Xmx2G -jar fabric-server-mc.1.20.1-loader.0.16.3-launcher.1.0.1.jar nogui
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[15:17:55] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.16.3
[15:17:55] [main/INFO]: Loading 45 mods:
        - fabric-api 0.92.2+1.20.1
           |-- fabric-api-base 0.4.31+1802ada577
           |-- fabric-api-lookup-api-v1 1.6.36+1802ada577
           |-- fabric-biome-api-v1 13.0.13+1802ada577
           |-- fabric-block-api-v1 1.0.11+1802ada577
           |-- fabric-block-view-api-v2 1.0.1+1802ada577
           |-- fabric-blockrenderlayer-v1 1.1.41+1802ada577
           |-- fabric-client-tags-api-v1 1.1.2+1802ada577
           |-- fabric-command-api-v1 1.2.34+f71b366f77
           |-- fabric-command-api-v2 2.2.13+1802ada577
           |-- fabric-commands-v0 0.2.51+df3654b377
           |-- fabric-containers-v0 0.1.64+df3654b377
           |-- fabric-content-registries-v0 4.0.11+1802ada577
           |-- fabric-convention-tags-v1 1.5.5+1802ada577
           |-- fabric-crash-report-info-v1 0.2.19+1802ada577
           |-- fabric-data-attachment-api-v1 1.0.0+de0fd6d177
           |-- fabric-data-generation-api-v1 12.3.4+1802ada577
           |-- fabric-dimensions-v1 2.1.54+1802ada577
           |-- fabric-entity-events-v1 1.6.0+1c78457f77
           |-- fabric-events-interaction-v0 0.6.2+1802ada577
           |-- fabric-events-lifecycle-v0 0.2.63+df3654b377
           |-- fabric-game-rule-api-v1 1.0.40+1802ada577
           |-- fabric-item-api-v1 2.1.28+1802ada577
           |-- fabric-item-group-api-v1 4.0.12+1802ada577
           |-- fabric-key-binding-api-v1 1.0.37+1802ada577
           |-- fabric-keybindings-v0 0.2.35+df3654b377
           |-- fabric-lifecycle-events-v1 2.2.22+1802ada577
           |-- fabric-loot-api-v2 1.2.1+1802ada577
           |-- fabric-loot-tables-v1 1.1.45+9e7660c677
           |-- fabric-message-api-v1 5.1.9+1802ada577
           |-- fabric-mining-level-api-v1 2.1.50+1802ada577
           |-- fabric-model-loading-api-v1 1.0.3+1802ada577
           |-- fabric-models-v0 0.4.2+9386d8a777
           |-- fabric-networking-api-v1 1.3.11+1802ada577
           |-- fabric-networking-v0 0.3.51+df3654b377
           |-- fabric-object-builder-api-v1 11.1.3+1802ada577
           |-- fabric-particles-v1 1.1.2+1802ada577
           |-- fabric-recipe-api-v1 1.0.21+1802ada577
           |-- fabric-registry-sync-v0 2.3.3+1802ada577
           |-- fabric-renderer-api-v1 3.2.1+1802ada577
           |-- fabric-renderer-indigo 1.5.2+85287f9f77
           |-- fabric-renderer-registries-v1 3.2.46+df3654b377
           |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
           |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
           |-- fabric-rendering-v0 1.1.49+df3654b377
           |-- fabric-rendering-v1 3.0.8+1802ada577
           |-- fabric-resource-conditions-api-v1 2.3.8+1802ada577
           |-- fabric-resource-loader-v0 0.11.10+1802ada577
           |-- fabric-screen-api-v1 2.0.8+1802ada577
           |-- fabric-screen-handler-api-v1 1.3.30+1802ada577
           |-- fabric-sound-api-v1 1.0.13+1802ada577
           |-- fabric-transfer-api-v1 3.3.5+8dd72ea377
           \-- fabric-transitive-access-wideners-v1 4.3.1+1802ada577
        - fabricloader 0.16.3
           \-- mixinextras 0.4.1
        - java 22
        - jei 15.17.0.76
        - minecraft 1.20.1
[15:17:55] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.7 Source=file:/C:/Users/Miguel%20Sousa/Downloads/Minecraft%20Server/libraries/net/fabricmc/sponge-mixin/0.15.2+mixin.0.8.7/sponge-mixin-0.15.2+mixin.0.8.7.jar Service=Knot/Fabric Env=SERVER
[15:17:55] [main/INFO]: Compatibility level set to JAVA_16
[15:17:55] [main/INFO]: Compatibility level set to JAVA_17
[15:17:56] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.4.1).
[15:18:08] [main/WARN]: You specified a resource pack without providing a sha1 hash. Pack will be updated on the client only if you change the name of the pack.
[15:18:08] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[15:18:09] [main/INFO]: Found new data pack fabric, loading it automatically
[15:18:10] [main/INFO]: [fabric-registry-sync] Loaded registry data [file 1/4]
[15:18:11] [main/INFO]: Loaded 7 recipes
[15:18:11] [main/INFO]: Loaded 1271 advancements
[15:18:11] [main/INFO]: Applied 0 biome modifications to 0 of 64 new biomes in 1.938 ms
[15:18:11] [Server thread/INFO]: Starting minecraft server version 1.20.1
[15:18:11] [Server thread/INFO]: Loading properties
[15:18:11] [Server thread/INFO]: Default game type: SURVIVAL
[15:18:11] [Server thread/INFO]: Generating keypair
[15:18:11] [Server thread/INFO]: Starting Minecraft server on *:25565
[15:18:12] [Server thread/INFO]: Using default channel type
[15:18:12] [Server thread/INFO]: Preparing level "teste"
[15:18:14] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[15:18:17] [Worker-Main-3/INFO]: Preparing spawn area: 0%
[15:18:17] [Worker-Main-5/INFO]: Preparing spawn area: 0%
[15:18:17] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[15:18:17] [Worker-Main-5/INFO]: Preparing spawn area: 0%
[15:18:17] [Worker-Main-3/INFO]: Preparing spawn area: 0%
[15:18:17] [Worker-Main-4/INFO]: Preparing spawn area: 0%
[15:18:17] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[15:18:18] [Worker-Main-3/INFO]: Preparing spawn area: 0%
[15:18:18] [Worker-Main-2/INFO]: Preparing spawn area: 4%
[15:18:19] [Worker-Main-2/INFO]: Preparing spawn area: 79%
[15:18:19] [Server thread/INFO]: Time elapsed: 4622 ms
[15:18:19] [Server thread/INFO]: Done (6.816s)! For help, type "help"
```

Since it was not completely vanilla ([15:18:09] [main/INFO]: Found new data pack fabric, loading it automatically), I went again and removed any server side resourcepacks, just in case.
Somehow, removing the resourcepack (customized Vanilla Tweaks, can send dropbox link if needed), fixed the issue (?) even if I didn't activate the pack from the menu.

To double check and see if it's the actual issue, I went ahead and added the resourcepack again and tested it.
I can confirm that the [resourcepack](https://www.dropbox.com/scl/fi/zz20tg9vzazcfut7h6du0/VanillaTweaks_r224450_MC1.20.x.zip?rlkey=p02fvfv81zj4xft189tg9anqx&st=nqh87jjg&dl=0), once enabled, caused the JEI item jumble.

I can replicate this in my singleplayer map: as soon as I enable the resource pack, the item list shuffles everything. Even If  I disable it during the session, it won't fix it immediately. I have to disconnect and reconnect and then it will be fixed with the pack disabled.

Having realized this, I re-enabled every mod and tested just without the resourcepack. As predicted, JEI is working just fine with every single mod

Not sure if there's anything you can do as Vanilla Tweaks is a very modular resourcepack, it might be having an issue with JEI or maybe any other mod. It's hard to identify the issue and it will differ for everyone, not to mention game versions and whatnot.

I will just not use the incompatible resourcepack and enjoy JEI and all other mods, as that seems to be the issue (unless it was a crazy coincidence, but given the extensive testing, I think it's the issue here).
If there's a fix for this, great. If not, It's totally fine and understandable given the nature of the resourcepack in question.
Not sure if it happens with other resourcepacks too.

**Comment by Kamiinaz** [comment] 2024-09-05 18:03
> I will just not use the incompatible resourcepack and enjoy JEI and all other mods, as that seems to be the issue (unless it was a crazy coincidence, but given the extensive testing, I think it's the issue here). If there's a fix for this, great. If not, It's totally fine and understandable given the nature of the resourcepack in question. Not sure if it happens with other resourcepacks too.

I've just updated the resourcepack and noticed I made some incompatible selections within the resourcepack itself (multiple changes to the same blocks for instance).
I've fixed my choices and tried again and now I'm able to use JEI AND the resourcepack together without any issue.

Problem solved here, despite not really finding the actual problem.

**Comment by Kalikars** [comment] 2024-09-07 08:25
I also had the same issue updating to the newest version. Deleting the 'world' folder within JEI configs regenerated the folder and seemingly fixed itself, although no file within that folder generated. It seems like older files within there are conflicting with newer version's sorting rules?

**Comment by mezz** [comment] 2024-09-18 07:47
Good news, I was able to reproduce this bug in singleplayer with only JEI, by changing the language.
The issue seems to be triggered by the resource reload pathway in JEI.

**Comment by mezz** [comment] 2024-09-18 08:25
I have pushed a fix for this in the latest versions of JEI, please try it out and let me know if you run into any more issues.

**Closed as completed** 2024-09-18 08:24 UTC
Labels: bug
