### ISSUE TITLE
Using Autofill for recipes into Artisan Wotktables void items/fluids and tools

### ISSUE THREAD

**Issue by Freebi85** [mezz/JustEnoughItems#1464] opened 2019-01-16 12:57 UTC
With jei_1.12.2-4.14.4.258 ->Using Autofill for recipes into Artisan Wotktables void items/fluids and tools.
With jei_1.12.2-4.14.4.259 ->same problem + manually crafting dosent work anymore.

With jei_1.12.2-4.14.4.251 ->no problems^^

Minecraft 1.12.2
Forge: .2087

**Comment by codetaylor** [comment] 2019-01-16 17:14
It looks like this commit is the culprit: https://github.com/mezz/JustEnoughItems/commit/0b73c440a7f114333db267c1c283d3f3b135a83f#diff-d60e3f216533fe7a914066833895f1c9

I'm not sure what the problem is without spending more time.

**Comment by codetaylor** [comment] 2019-01-16 17:38
I get a NPE in my log output when reproducing this: https://gist.github.com/codetaylor/6d660891effbcc82b164024141f4c577

**Comment by codetaylor** [comment] 2019-01-16 18:10
It looks like the `toTransfer` map's keys are not the actual slot numbers, but rather an index into the `craftingSlots` list and are used to retrieve the actual slot numbers from the list. 

The current code will work for containers that have slot numbers that are identical to the indices of the `craftingSlots` array. It will break when the indices and slot numbers differ, which is the case here.

For example, when setting breakpoints, the `toTransfer` map contains entries `[0 => ItemStack, 1 => ItemStack, ..., 9 => ItemStack]` and in the line [here](https://github.com/mezz/JustEnoughItems/blob/1.12/src/main/java/mezz/jei/transfer/BasicRecipeTransferHandlerServer.java#L58), `craftingSlotNumber` was `46`, therefore a null ItemStack was returned from the map. The NPE short-circuits the logic and some of the items are cleared from the inventory, but never make it to the crafting slots.

I think if the line linked above...

```java
ItemStack transferItem = toTransfer.get(craftingSlotNumber);
```

... were changed to ...

```java
ItemStack transferItem = toTransfer.get(craftingSlots.indexOf(craftingSlotNumber));
```

... it would solve the issue.

I'll set it up and try it out.

**Comment by codetaylor** [comment] 2019-01-16 19:13
I can confirm that making this change does correct the problem, however, shift-clicking the `+` for an Artisan Worktable (AW) recipe no longer fills 'as many stacks as possible' which was the purpose of [this change](https://github.com/mezz/JustEnoughItems/pull/1068) (PR). The PR introduced the `requireCompleteSets` flag to allow shift-click transferring of as many items as possible.

The code introduced in the fix for https://github.com/mezz/JustEnoughItems/issues/1412 negates the changes made in the PR because the stack size for all items transferred is limited to the smallest stack size of the whole group. When transferring AW recipe ingredients that include tools, the stack size for all items is limited to one, even though I explicitly set the `requireCompleteSets` flag to `false`.

This can be addressed by wrapping the code of interest like so:

```java
if (requireCompleteSets) {
  ItemStack transferItem = toTransfer.get(craftingSlots.indexOf(craftingSlotNumber));
  int slotStackLimit = craftingSlot.getItemStackLimit(transferItem);
  minSlotStackLimit = Math.min(slotStackLimit, minSlotStackLimit);
}
```

This will preserve the functionality introduced by the PR.

I am confident that this will not influence the fix for https://github.com/mezz/JustEnoughItems/issues/1412 because the `requireCompleteSets` flag is, by default, set to `true` and must be explicitly set to `false` by the mod using that feature, which the Slice 'n Splice does not do.

**Closed as completed** 2019-01-20 06:15 UTC
