### ISSUE TITLE
Recipes not being display with newest version

### ISSUE THREAD

**Issue by SaphieNyako** [mezz/JustEnoughItems#2514] opened 2021-10-06 08:36 UTC
version: jei-1.16.5-7.7.1.122.jar

Since the new update recipes are not being displayed of multiple mods.
Examples are:
feywild - dwarven anvil, altar
botania - elven trades, mana infusion
create - alot of recipes

**Comment by Freebi85** [comment] 2021-10-06 10:45
Can confirm. Like Immersive Engineering's Coke Oven or multiblocks in general.
Cheers

**Comment by robotgryphon** [comment] 2021-10-06 12:09
Can also confirm, this breaks Compact Crafting recipe display as well

**Comment by Baggytrousers27** [comment] 2021-10-06 14:57
Recipes from token enchanting are broken in 1.17.1 (37.0.82) with jei-1.17.1-8.1.0.21.

**Comment by Hubry** [comment] 2021-10-06 15:33
The change:
https://github.com/mezz/JustEnoughItems/blob/eaeff62f3cfa0ab839032be1e078fb7a00b9b46b/src/main/java/mezz/jei/recipes/RecipeManagerInternal.java#L117-L121
Which leads to here:
https://github.com/mezz/JustEnoughItems/blob/eaeff62f3cfa0ab839032be1e078fb7a00b9b46b/src/api/java/mezz/jei/api/recipe/category/IRecipeCategory.java#L132-L135

The problem is that the majority of modders have set their custom recipe types to return true from `isSpecial`, because the recipe book emits a log message for every single recipe it does not known how to handle (see `ClientRecipeBook#getCategory`).

**Comment by MrNoe93** [comment] 2021-10-06 16:16
also broken are the ones for Draconic Evolution, Thermal, and Blood Magic

**Comment by SaphieNyako** [comment] 2021-10-06 20:38
```
  @Override
    default boolean isSpecial() {
        return false;
    }
```

Setting it false fixed it. 
Thanks.

**Comment by KnightMiner** [comment] 2021-10-07 00:51
If your goal is just fixing this in your mod, overriding `isHandled` in your JEI category will fix this without the sideeffect of recipe book log spam.

**Comment by mezz** [comment] 2021-10-07 03:23
Thanks for the report!
Hubry's assessment is correct.
This should be fixed in the next version.

**Comment by ZAKsPop** [comment] 2021-10-08 12:50
I had to go back to jei-1.16.5-7.7.1.119 before it worked correctly. Mekanism recipes were missing. I'm sure others as well.

**Comment by mezz** [comment] 2021-10-10 03:40
Please try with 
`jei-1.16.5-7.7.1.125`

**Comment by hypernova132** [comment] 2021-10-11 23:53
> Please try with `jei-1.16.5-7.7.1.125`

There are still missing recipes in this version

**Comment by mezz** [comment] 2021-10-12 00:46
Can you please give specific information about which recipes are missing, and from which mods?

**Comment by hypernova132** [comment] 2021-10-12 02:49
> Can you please give specific information about which recipes are missing, and from which mods?

Of the mods I use it's all non-vanilla methods from tinkers except for casting. As well as all non-vanilla methods from thermal expansion, mekanism, astral sorcery, botania, resourceful bees, mystical agriculture, and draconic evolution.

**Comment by mezz** [comment] 2021-10-12 02:59
Are you using the most recent version of Tinker's as well? 
It seems related to this issue, which they marked as resolved with JEI's update: https://github.com/SlimeKnights/TinkersConstruct/issues/4636

If you still get the issue with the latest JEI and Tinker's, please link a client log here and I can take a look.

**Comment by hypernova132** [comment] 2021-10-12 06:01
> Are you using the most recent version of Tinker's as well? It seems related to this issue, which they marked as resolved with JEI's update: [SlimeKnights/TinkersConstruct#4636](https://github.com/SlimeKnights/TinkersConstruct/issues/4636)
> 
> If you still get the issue with the latest JEI and Tinker's, please link a client log here and I can take a look.

Turns out I didn't have the right version of JEI

**Comment by mezz** [comment] 2021-10-12 07:43
Ok cool, thanks for confirming. Glad it’s fixed!

**Closed as completed by mezz** 2021-10-12 07:43 UTC
Labels: bug
