### ISSUE TITLE
[Suggestion]: Keybinds on Fabric

### ISSUE THREAD

**Issue by ElRokur** [mezz/JustEnoughItems#3443] opened 2024-02-26 02:41 UTC
### Suggestion

Cannot change the keybinds on fabric because it doesnt exist the option to do so.

As i searched a bit.. this is a known bug:

#3355 
#3136 
#3000

All of those have been closed due to inactivity. It is a shame :(
For now i guess its time to use another mod, since keybinds are essential to me

**Comment by GhostBone** [comment] 2024-04-11 09:56
me, too. Sad :-(

**Comment by Kalikars** [comment] 2024-07-24 21:41
Bumping this. Not having keybinds = not being able to use the mod.

**Comment by Cicopath** [comment] 2024-09-05 02:09
Would also greatly appreciate keybinds. Unfortunately I haven't found much on this issue

**Comment by mezz** [comment] 2024-09-12 05:21
Thanks for the report!

This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/3000

Key bindings for Fabric have been implemented in JEI 
for 1.20.1: `15.18.0.80`+
and 1.21.1: `19.17.0.196`+

**Closed as not planned by mezz** 2024-09-12 05:21 UTC
Labels: duplicate
