### ISSUE TITLE
[Bug]: Fabric 1.20.1, JEI packets not syncing with client, causing JEI to not work for both server and client (and addons of JEI)

### ISSUE THREAD

**Issue by DiamondKing9998** [mezz/JustEnoughItems#3531] opened 2024-06-08 17:41 UTC
### Steps to Reproduce the Bug

1. Download linked modpack on client
2. Use [ServerPackCreator](https://serverpackcreator.de/#/) to make the dedicated server template, using 10gb of max ram and 8gb of min ram, and with the default client side mods from SPC removed automatically
3. Run client and server
4. Connect client to server
5. Game allows you to join, but a log message occurs "Packet too big (is [number], should be less than 8388608)" and JEI is not loaded on client or server.

### Expected Behavior

Using a packet mod of your choice to up the packet limit, JEI should load properly. Additionally, I'm pretty sure JEI is also able to be used client-side only but I don't know that for sure, but if it is it shouldn't matter anything about the server

### Actual Behavior

JEI gets disabled after error appears in the server log (Packet too big (is [number], should be less than 8388608))

### Mod Pack URL (Optional)

Prism Launcher pack (.zip): https://www.mediafire.com/file/x5ni8on7g7zu3vo/CardonCraftFromLinux.zip/file

### Mod Pack Version (Optional)

n/a (private modpack)

### Extra Notes (Optional)

I'm having a mod error loop problem, if you will. My server works normally, except for that when I join, JEI errors and does not work on the server. This is due to sending larger packets than the packet limit. I'm able to (presumably) fix this issue using another mod called Packet Fixer, but that creates a conflict between the same code with XXL Packets.  XXL Packets is necessary on the server because without it anyone that joins gets an error about "Unable to fit NUMBER into 3." For some reason XXL Packets does not affect modded packets, only Vanilla. But either way, JEI is very necessary on my modded server bc otherwise you have no idea how to craft anything as it's a somewhat big modpack. I'd appreciate any help given.

Additionally when using the modpack with REI and their addons, REI sends its own error in the log stating something of a desync between client and server. When using EMI instead, the bottom left text in the inventory on the client says something about waiting for Recipes to sync. 

### latest.log

https://mclo.gs/x0s7L2G

**Comment by mezz** [comment] 2024-09-09 02:58
Thanks for the report!
Sorry I did not see this earlier.

The problem is not from JEI, REI, or EMI. All of these mods wait for the vanilla recipe sync to complete before they can start, but something you're doing is breaking the recipe sync.

JEI doesn't send anything from the server to the client except in response to requests from the player (like enabling cheat mode, or transferring a recipe to the crafting grid). These packets are small and would not cause the issue you're describing.

I hope you are able to find some help to figure out what's wrong, but I can say that is not directly caused by a recipe viewer mod.

**Closed as not planned by mezz** 2024-09-09 02:58 UTC
Labels: troubleshooting
