### ISSUE TITLE
JEI crashes minecraft with null reference exception

### ISSUE THREAD

**Issue by ClassyCircuit** [mezz/JustEnoughItems#2694] opened 2022-01-25 16:55 UTC
JEI is crashing my minecraft client on a regular basis, yesterday it happened about 5 times during 1 hour.

Description: keyPressed event handler
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "object" is null

Full crash report: https://gist.github.com/janissimsons/47d26909f965a558ac684a4af683ab6e

MC version: 1.18.1, forge loader.

**Comment by mezz** [comment] 2022-01-25 19:20
Thanks for the report!
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/2683
It can be fixed by updating JourneyMap to the latest version.

**Closed as completed by mezz** 2022-01-25 19:20 UTC
Labels: duplicate
