### ISSUE TITLE
[1.18.1-9.2.1.71] In "Mouse Pickup" Cheat Mode with items in hand, holding shift key while hovering a different item in Ingredients List voids items in hand

### ISSUE THREAD

**Issue by sdarkwell** [mezz/JustEnoughItems#2678] opened 2022-01-13 17:59 UTC
**Hello,**

While in "Mouse Pickup" Cheat Mode, after holding shift and clicking to pick up a full stack of items, if shift continue to be held and the mouse is moved, the items are erased from hand.

The need for shift to be released appears quite sensitive, as I have found myself required to deliberately hold down shift, click on an item to pick up a stack, then release the shift key before moving the mouse cursor to place the stack into my inventory/hotbar. Even a slight movement will erase the stack.

**Thank you and be well!**
- S.

**Comment by mezz** [comment] 2022-01-17 02:55
Thanks for the report!
I tried this out in single-player but was not able to reproduce the issue. Holding shift didn't cause the item to be deleted.
Do you have any other JEI keybinds set to SHIFT that might interfere?
Are there any other conditions that must be met for this bug to occur?

**Comment by sdarkwell** [comment] 2022-01-17 10:37
Hello @mezz,

Thank you for the response!

Testing the issue again, I was able to re-created it on a clean installation and no changes to the defaults. Further, I believe the issue occurs not when the mouse moves, but rather when either "Shift" key is active (held or pressed) while hovering over a JEI item other than the item currently in-hand.

Because in my typically setup, JEI items are quite small, I didn't recognize that it was required to hover over another item to cause the issue to occur–I attributed it to the movement of the mouse cursor itself. My apologies!

Here is a detailed breakdown of the details in the case that it helps:

**Setup:**
- Minecraft: v1.18.1
- Forge: v39.0.36
- JEI: v9.2.3.78

**Preparation:**
1. Start Minecraft
2. (Wait for Minecraft to start)
3. Click "Create New World"
4. Change "Allow Cheats" to "On"
5. Click "Create New World"
6. (Wait for new world to generate)
7. Press "E" key to display JEI
8. Hold the "Ctrl" key and click the "JEI Config" button to enable "Cheat Mode"

**Producing the error:**
1. Press and hold the left "Shift" key
2. Continue holding the left "Shift" key and click any item in JEI (eg: "Stone")
3. (A stack of the item is now in your hand)
4. While still holding the left "Shift" key, move the mouse cursor over another item in JEI (eg: "Granite")
5. (Your hand now displays that it is no longer holding anything)

NOTE: The issue also occurs with items picked up from the inventory. If you pick up items from your inventory, hover over any other items in the JEI Ingredients List, then press either shift key, the contents of your hand are voided.

Hope that helps. :)

**Thank you again and be well!**
\- S.

**Comment by mezz** [comment] 2022-03-24 22:21
This issue appears to be resolved in the latest versions of JEI. 
I tested on `1.18.2-9.5.4.165`. Can you confirm?

**Comment by sdarkwell** [comment] 2022-03-25 12:32
**Hello @mezz,**

Thank you for taking the time to review this issue!

Unfortunately, this issue persists with `jei-1.18.2-9.5.4.166`.
I created an entirely new Minecraft 1.18.2 instance with only JEI installed.

Also, another detail I've noted is that the items are only voided from your cursor on hover if you hover an item in the JEI items list _other than_ the held item. In other words, if you have stone in hand and pass your cursor over stone in the items list while holding shift, they won't void, but if you instead pass your cursor over granite while holding shift, they will.

**Hope that helps! Thank you so much and be well!**
\- S.

**Comment by mezz** [comment] 2022-03-25 20:24
I have tried to reproduce this issue like you described, but I do not encounter the problem.
During this video I am holding shift the whole time:

https://user-images.githubusercontent.com/916092/160195675-fee8774d-c409-43c4-b38f-45c9b2b284ac.mov

**Comment by mezz** [comment] 2022-03-25 20:24
Maybe this is an issue in Forge, have you tried using the latest version of Forge?

**Comment by mezz** [comment] 2022-11-02 03:56
Sorry for the long delay, I have finally reproduced and fixed this issue in the latest version of JEI 11 for 1.19.2 and JEI 10 for 1.18.2.
https://github.com/mezz/JustEnoughItems/commit/5252f70c55bcef8bdf474013eacb2625375ec740

To reproduce the issue, I needed to release shift and then press it again while hovered over the ingredient list.

**Closed as completed by mezz** 2022-11-02 03:56 UTC
Labels: bug
