### ISSUE TITLE
[Bug]: Resource packs make JEI random sorting items

### ISSUE THREAD

**Issue by PUrE-elF** [mezz/JustEnoughItems#3771] opened 2024-09-18 13:08 UTC
### Steps to Reproduce the Bug

When I add resource pack that require optifine. It cause the problem. like this in the example picture below :
![IMG_20240918_173824](https://github.com/user-attachments/assets/ae6a0c08-2464-4267-97ad-928cf850aa5a)

I could just remove the resource pack. But it crashing in my server resourcepacks. and it cannot be undone with any way.

Resourcepack name : Better illagers, Better Farm Animals_v0.08

I need help for this. 
Thank you. 

### Expected Behavior

Even add any resource packs, JEI should sorting items as usual.

### Actual Behavior

If remove all the resource packs it stop the bug. But when I add any resource packs back again it still cause the bug.

### latest.log

https://mclo.gs/UD8OGDF

**Comment by mezz** [comment] 2024-09-20 05:24
Thanks for the report!
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/3731 and has been fixed in the latest versions.

**Closed as not planned by mezz** 2024-09-20 05:24 UTC
Labels: duplicate
