### ISSUE TITLE
Having Duplicate JEI mods installed causes computer crash.

### ISSUE THREAD

**Issue by DatrixTHLK** [mezz/JustEnoughItems#502] opened 2016-10-05 07:25 UTC
I'm not sure but everytime I try to open and play minecraft my computer crashes on me and I have to restart. Done this 4 times already and I have no idea what the cause of it is but minecraft seems to go up to step 3/7 and then the crash occurs and my computer runs into a problem and has to restart...

**Comment by DatrixTHLK** [comment] 2016-10-05 07:28
I found out that problem it was caused by having two of the same mods in the mods folder but one was an older version and one was the newest version (Both JEI 301 and 302) . I don't think any other mod has done that to me before though even when having a duplicate installed

**Comment by mezz** [comment] 2016-10-05 07:55
Thanks for the report!
There's no way for JEI to crash your computer by itself, at its worst it will crash Minecraft or Java.
The only thing that could crash your computer entirely is a bug in Java or in your graphics drivers, I think you should try updating both of those.

**Comment by mezz** [comment] 2016-10-05 07:58
I asked around and someone suggested the problem could also be from broken ram, if you update Java and your graphics drivers and it still crashes, try this:
http://www.howtogeek.com/260813/how-to-test-your-computers-ram-for-problems/

**Comment by mezz** [comment] 2016-10-05 08:01
In any case I'm _really_ sure this isn't caused by JEI so I'm closing the issue, but feel free to reply here with anything you find out.

**Closed as completed by mezz** 2016-10-05 08:01 UTC
Labels: invalid

**Comment by DatrixTHLK** [comment] 2016-10-05 08:08
Will do so. The graphics card is fully up-to-date, Java update 101 is the most up-to-date version. I will try the diagnostic tool then. 

My diagnostic tool said there weren't any errors yet my pc crashed on me three times before it told me that.

**Comment by DatrixTHLK** [comment] 2016-10-05 08:08
Will do so. The graphics card is fully up-to-date, Java update 101 is the most up-to-date version. I will try the diagnostic tool then.

**Comment by mezz** [comment] 2016-10-05 08:48
Hmm what else can we check...
Maybe hard drive corruption? 
http://www.howtogeek.com/howto/windows-vista/guide-to-using-check-disk-in-windows-vista/

**Comment by DatrixTHLK** [comment] 2016-10-05 08:56
Check Disk found no errors either, on my C drive. I haven't optimized my computer I will try doing that as well. In other words Defragmenting.

**Comment by DatrixTHLK** [comment] 2016-10-05 09:08
I'll also check if malware is infecting my computer

**Comment by mezz** [comment] 2016-10-05 09:11
Hm at this point I don't have any more ideas. You may get better help on the Minecraft Forge forum. There are more people to help and they probably have more experience with bugs like this.
http://www.minecraftforge.net/forum/index.php?board=15.0

**Comment by DatrixTHLK** [comment] 2016-10-05 09:34
Well thanks for the help nonetheless. I doubt many mod authors would do the same.

**Comment by DatrixTHLK** [comment] 2016-10-06 02:01
It works now. I reinstalled Java and Minecraft (at least unmodded it works) going to do a test to see with modded now. Modded works also as far as launching goes. I guess the Java release that was downloaded was corrupted somehow and caused my computer to crash. In turn caused minecraft to give me a white output screen and having to reinstall it.

**Comment by mezz** [comment] 2016-10-06 06:26
Alright cool. I wonder how that happened without any harddrive or memory issues. Anyway glad it worked out!

**Comment by DatrixTHLK** [comment] 2016-10-10 12:40
Yes, same. :)
