### ISSUE TITLE
Not Sure What Happened Here...

### ISSUE THREAD

**Issue by zzApotheosis** [mezz/JustEnoughItems#389] opened 2016-08-13 07:13 UTC
Java 1.8.0_102 64bit
Minecraft 1.10.2
MCP 9.32
Forge 12.18.1.2056
OptiFine_1.10.2_HD_U_C2
Just Enough Items 3.8.1.242

I'm not entirely sure what happened to the whole mod altogether, but this was the crash report I got when attempting to click where the wrench icon is supposed to be... https://drive.google.com/file/d/0B_wljXPJi507MXhiZmFzRllxZUE/view?usp=sharing

You can see for yourself what happens here: https://drive.google.com/file/d/0B_wljXPJi507QU5sVVB3WjZQRUE/view?usp=sharing

On a side note, I have tested this with only JEI installed. The mod operates perfectly fine, so this issue seems to be caused by another mod. After further testing, I have found that the mod that causes this weird bug is AppleCore (version 1.3.5 for Minecraft 1.10.2). Also note that the game immediately crashes with this crash report when ONLY JEI and AppleCore are installed together. The game loads into the single player world just fine when OptiFine is installed alongside JEI and AppleCore: https://drive.google.com/file/d/0B_wljXPJi507Q0NqVl9Hay1aaEk/view?usp=sharing

I have not tested any further.

Thanks for this great mod! Hopefully this helps in development.

**Comment by miuirussia** [comment] 2016-08-13 09:08
Confirm it!

**Comment by mrapplexz** [comment] 2016-08-13 09:22
Can confirm.

**Comment by mezz** [comment] 2016-08-13 22:00
Thanks for the report!
This is a duplicate of #387, it has been fixed in the latest AppleCore.

**Closed as completed by mezz** 2016-08-13 22:00 UTC
Labels: duplicate
