### ISSUE TITLE
[Bug]: not showing percentages of probabilities with the create mod

### ISSUE THREAD

**Issue by Travistads** [mezz/JustEnoughItems#3746] opened 2024-09-06 17:10 UTC
### Steps to Reproduce the Bug

 1. look at recipes of the create mod

### Expected Behavior

see the percentage chance of getting materials in the crusher of the create mod

### Actual Behavior

I can't see the percentages chance

### Extra Notes (Optional)

this bug has append before in older versions of JEI

**Comment by mezz** [comment] 2024-09-07 01:49
Thanks for the report!
You are probably using an old version, please update to jei-1.20.1-forge-15.14.0.64 or newer.
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/3683

**Closed as not planned by mezz** 2024-09-07 01:49 UTC
Labels: duplicate
