### ISSUE TITLE
rendering crash upon clicking the extraction pump item from factory tech

### ISSUE THREAD

**Issue by DrDarkfire** [mezz/JustEnoughItems#1306] opened 2018-07-23 19:48 UTC
When I was trying to view the recipe for the extraction pump from factory tech, it crashed my game. It is seemingly the only item that crashes me so far. It was recreated multiple times
[crash-2018-07-23_15.39.44-client.txt](https://github.com/mezz/JustEnoughItems/files/2220789/crash-2018-07-23_15.39.44-client.txt)

**Comment by DrDarkfire** [comment] 2018-07-24 16:13
Not an optifine issue. One of my playtesters NOT using opftifine reproduced the bug.

**Comment by mezz** [comment] 2018-07-25 05:59
Thanks for the report!
This is the same crash as https://github.com/mezz/JustEnoughItems/issues/1303
I have just released a new version of JEI that will help figure out the cause of this issue.
I will close this issue as a duplicate, please continue discussion in https://github.com/mezz/JustEnoughItems/issues/1303

**Closed as completed by mezz** 2018-07-25 05:59 UTC
Labels: duplicate
