### ISSUE TITLE
Cannot ctrl-click on OS X

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#523] opened 2016-10-15 12:10 UTC
Hello

I am trying to hide an item in JEI, so I went to the config menu and enabled "Item Hiding Mode". When I hover the item I want to hide, I can see "Ctrl-click to hide" in the tooltip.
However I am using an Apple computer, and ctrl-click is mapped system-wide to right-click. So when I try to ctrl-click, JEI just shows the uses of that item (normal right-click behavior) and doesn't hide it.
Is there a way to use something else than ctrl-click for OS X?

Also, manually editing the itemBlacklist.cfg in the config folder works, this is just a suggestion for convenience.

Thank you for your work

(sorry for my bad english)

**Comment by shadowfacts** [comment] 2016-10-15 13:26
Try pressing the Command key (⌘) and clicking at the same time. Minecraft control key bindings use Command on macOS.

**Comment by TehNut** [comment] 2016-10-15 15:18
The tooltip was fixed in 54184570f30003341694f98c471e9982ab2e418f

**Comment by ghost** [comment] 2016-10-15 19:17
Thank you for your answers.

Cmd-click actually works.

Sorry, I only tested with the release builds, I forgot to check the beta builds, my bad :/
You may close this issue.

**Comment by mezz** [comment] 2016-10-15 21:43
Dupe of #319 sortof

**Closed as completed** 2016-10-15 21:43 UTC
Labels: duplicate
