### ISSUE TITLE
 hello the JEI mod does not work well (@ version @) and when will they release the update to repair it?

### ISSUE THREAD

**Issue by Rodrix8050** [mezz/JustEnoughItems#2068] opened 2020-08-24 21:41 UTC
Hi I've been making a mod pack but it didn't give me the mod, please it's one of my favorite mods :c

**Comment by Tahakk** [comment] 2020-08-25 06:34
Duplicate of #2060

**Comment by Valafi** [comment] 2020-08-25 19:42
@Rodrix8050 are you sure you're using the latest release? You forgot to mention which version you're using.

**Comment by mezz** [comment] 2020-08-26 00:44
Thanks for the report!
Please update to the latest version, that one has an issue.

**Closed as completed by mezz** 2020-08-26 00:44 UTC
Labels: duplicate
