### ISSUE TITLE
[Bug]: [1.19] Missing Client config on Mod menu

### ISSUE THREAD

**Issue by ffuentesm** [mezz/JustEnoughItems#2860] opened 2022-06-18 19:12 UTC
### Steps to Reproduce the Bug

Install JEI in 1.19
Go to JEI mod menu config

### Expected Behavior

There should be a client config in the mod menu to set the UI size and other settings. 

### Actual Behavior

There is no Ingame client config and requires a menu file config setting.
![image](https://user-images.githubusercontent.com/44974827/174452982-40b16eee-b684-4ee7-8202-aabcc8d930be.png)

### latest.log

https://gist.github.com/ffuentesm/b76ee4cbe0d08c39610b1148e9c16d32

**Comment by zpprsprk** [comment] 2022-06-22 05:01
This seems to be affecting 1.18.2 version 10.1.0.208 as well

**Comment by taj1994** [comment] 2022-07-28 20:32
Same issue with `jei-1.18.2-forge-10.1.3.238` in 1.18.2

**Comment by EtherialMind** [comment] 2022-07-30 07:17
I have been seeing the same issue and from what I can tell it seems that the client config is being generated as a .ini file rather than a .toml file causing it to be inaccessible. I am no expert so I may be way off but that is my guess.

**Comment by EtherialMind** [comment] 2022-07-30 07:18
at least on the 1.18.2 version of this issue

**Comment by CassieRoseZA** [comment] 2022-07-30 11:42
Only stable version iv found is 232

**Comment by mezz** [comment] 2022-07-31 04:46
Thanks for the report!
This is happening because I rewrote the configs to work on both Forge and Fabric. 
This mod menu can only show Forge configs, so I need to find another way to make it display.

**Comment by TheRealWormbo** [comment] 2022-08-03 08:03
That seems suboptimal, considering the client (rather than server) config is the thing players care about most. Other mods are compatible with both Forge and Fabric, and still are able to expose their raw configuration through the Forge-specific API.
(Not exposing it to the API would only be reasonable if there was a custom in-game way to access it. You probably shouldn't require players to dig through the config folders.)

**Comment by mezz** [comment] 2022-08-05 23:00
Yes, agreed. This is marked as a bug accordingly.
Unfortunately there is no "Forge-specific API", it is a Forge-specific implementation. You must use their implementation to be compatible with mods that display the config menu. I am not sure how other mods are implementing their configs to be cross-platform but if you know of some then I can take a look for ideas.

**Comment by TheRealWormbo** [comment] 2022-08-06 06:01
I think Botania would be a good example of strictly separating common ("XPlat") and loader-specific (Forge/Fabric) code, including the configuration. I believe their approach is internally defining an interface to access their configuration values, and then for each loader system they implement that interface with the platform-specific configuration system. For Forge that's Forge's configuration API, and for Fabric they appear to be using [fiber](https://github.com/FabLabsMC/fiber).

**Comment by TheRealWormbo** [comment] 2022-08-06 06:33
I think Botania would be a good example of strictly separating common ("XPlat") and loader-specific (Forge/Fabric) code, including the configuration. I believe their approach is internally defining an interface to access their configuration values, and then for each loader system they implement that interface with the platform-specific configuration system. For Forge that's Forge's configuration API, and for Fabric they appear to be using [fiber](https://github.com/FabLabsMC/fiber).

**Comment by Sandrituky** [comment] 2023-04-14 21:23
The issue is still here. We should be able to config how many columns and rows will show in-game! :(

**Comment by Claradeta** [comment] 2023-05-25 18:19
Yeah it keeps happening

**Comment by tovc** [comment] 2023-06-12 09:00
nearly a year on and this still hasn't been fixed...

**Comment by TeKett** [comment] 2023-06-21 16:30
> Thanks for the report! This is happening because I rewrote the configs to work on both Forge and Fabric. This mod menu can only show Forge configs, so I need to find another way to make it display.

How about just making a simple if-else? Cant be that hard to check if its using fabric or forge. I mean you are already doing that no? Else you would have had 2 different versions and this would never have been a problem. And the server config still works as it should. So i fail to see what the issue could be.

On a similar note, it dosn't even find it even if you rename the file to .toml, so i cant even fix it on my side.

**Comment by Faylen** [comment] 2023-07-06 16:40
I'm going to bump this as well because I'm also having this exact same issue. It doesn't make you feel good when you see this issue has existed for well over a year & many tickets regarding the issue are automatically closed because you don't respond & the original posters don't bother coming back and opening them again.
Using Minecraft version 1.19.2, forge version 43.2.10
Can access server config just fine, but I don't care about that. I want the client config. That I can't access :/

**Comment by joel4848** [comment] 2023-07-16 23:30
bump again, this is incredibly frustrating

**Comment by staridiot** [comment] 2023-10-03 06:32
Doesn't look like this was ever fixed, and this is causing issues for modpacks on older versions like 1.18.2.

**Comment by Claradeta** [comment] 2023-10-03 06:42
I really can't believe this issue just keeps happening, are devs even
checking the thread?

**Comment by DessertOverlord** [comment] 2023-10-22 19:28
Can confirm this is still an issue

**Comment by penguin-glitch** [comment] 2023-12-10 01:52
This could be a suggested feature for Configured, to auto generate GUI config menus from .ini files?

**Comment by audaki** [comment] 2024-06-17 11:53
If you are using fabric, look here: https://github.com/mezz/JustEnoughItems/issues/3127#issuecomment-1435689878

**Closed as completed** 2024-06-18 06:35 UTC
Labels: bug
