### ISSUE TITLE
[1.10.2]Craft tweaker error

### ISSUE THREAD

**Issue by YOYOK9** [mezz/JustEnoughItems#651] opened 2016-12-03 20:29 UTC
So back again with more errors... I have recently added CraftTweaker and minetweakerRecipeMaker and noticed that when I log into the pack it takes for ever for JEI to load the new recipes. The scripts are both client and server side. 

Log from client console (copied)
http://pastebin.com/uKQfgrLr

Can give more info let me know.

**Comment by mezz** [comment] 2016-12-06 19:18
Thanks for the report!
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/551
We are working on solutions for this but it is taking a while.
You can discuss more in that issue if you have more questions.

**Closed as completed by mezz** 2016-12-06 19:18 UTC
Labels: duplicate
