### ISSUE TITLE
[Bug][1.19.2 Forge 11.3.0.271]: Items being deleted from cursor in cheat mode. 

### ISSUE THREAD

**Issue by Rosethorns** [mezz/JustEnoughItems#3022] opened 2022-10-20 01:47 UTC
### Steps to Reproduce the Bug

Event A:
1. With cheat mode enabled
2. Shift click an item to pick up a stack

Event B:
1. With cheat mode enabled
2. Attempt to pick up more than 2 items in the mouse stack

### Expected Behavior

While cheat mode is enabled items should not be removed from the cursor while picking up a stack or more than 2 items.

### Actual Behavior

A Outcome: The stack will sometimes be removed from the cursor. This doesn't always happen but when it does occur it will happen consistently until the stack stays "picked up"

B Outcome: The stack will always be removed on the third item as if the player was trying to the delete a stack of items by placing them in the JEI item "area" 

### Extra Notes (Optional)

This has been occuring to my knowledge with all 1.19.2 versions of JEI

### latest.log

https://gist.github.com/Rosethorns/2456b9fc9b309679260a01ffbdd9df62

**Comment by mezz** [comment] 2022-10-29 23:17
Thank you for the report!
I think this has the same root cause as https://github.com/mezz/JustEnoughItems/issues/3002, JEI is not handling its packets on the correct thread. 
I have submitted a fix for this (https://github.com/mezz/JustEnoughItems/commit/f758d0d4c9b0568091253dfc7fbb4b0e2ec55dff) but the build system is not working right now, so the updated release is a bit delayed.
Please try this out when there's a new build of JEI for 1.19.2 available, it should hopefully fix this problem.

**Comment by mezz** [comment] 2022-11-01 02:24
The build system is working again, so I was able to create a new version.
Please try out JEI version `11.4.0.279` and let me know if the issue has been fixed.

**Comment by Rosethorns** [comment] 2022-11-01 23:44
Sorry to inform you, this is still occurring on version 11.4.0.279
Both issues, no more than 2 per mouse stack when selecting singles and also whole stacks sometimes being eaten when shift clicking.

**Comment by mezz** [comment] 2022-11-02 03:37
Thank you for confirming for me!

I was finally able to reproduce "Event A" by picking up an item and then pressing any key (even shift) while hovering over the ingredient list. The "delete items" handler is supposed to check for a left-click, but it turned out it was just accepting any input at all, which is likely the cause of the problem. This is fixed in https://github.com/mezz/JustEnoughItems/commit/5252f70c55bcef8bdf474013eacb2625375ec740

"Event B" was easily reproduced and fixed in https://github.com/mezz/JustEnoughItems/commit/1f93f82bfc6bac8b3a90c06c1a4f26c53ea40b6b. To see if you can pick up more of an item, I was mistakenly checking if ItemStacks were identical, instead of checking that they could stack.

These should both be fixed in JEI version `11.4.0.282`. 
Please let me know if you are still able to reproduce "Event A" some other way or if I was able to actually fix it!

**Comment by Rosethorns** [comment] 2022-11-03 03:43
Great news

I can't reproduce either event looks like both have been fixed. Thanks!

**Comment by mezz** [comment] 2022-11-03 17:13
Excellent! Thanks for the good report and confirming the fix, Rorax.

**Closed as completed by mezz** 2022-11-03 17:13 UTC
Labels: bug
