### ISSUE TITLE
JEI menu not appearing ingame on server

### ISSUE THREAD

**Issue by IchigoGames** [mezz/JustEnoughItems#1687] opened 2019-08-17 20:10 UTC
Issue jei does not show up in game on server but does show up in singeplayer 
Minecraft 1.14.4
jei-1.14.4-6.0.0.10
forge 28.045 and 28.0.49
[latest.log](https://github.com/mezz/JustEnoughItems/files/3512404/latest.log)

**Comment by mezz** [comment] 2019-08-18 19:04
Thanks for the report!
Is this a duplicate of https://github.com/mezz/JustEnoughItems/issues/1684?

**Comment by IchigoGames** [comment] 2019-08-18 22:29
Found it was going to test all the mods listed above to start off so i picked the one i added the most recent as this use to not be a issue and it was Chance Cubes (by turkey2349) ChanceCubes-1.14.4-4.0.0.298 with it added to server no jei without it on server jei shows up. so ill go make a report on there next.

**Comment by IchigoGames** [comment] 2019-08-18 22:30
> Thanks for the report!
> Is this a duplicate of #1684?
yes some one said to open a new one in case the issue was not the same

**Comment by mezz** [comment] 2019-08-18 22:32
Ok thanks. Since they are the same, let's try to keep conversation in one place (the other issue).

**Closed as completed by mezz** 2019-08-18 22:32 UTC
Labels: duplicate
