### ISSUE TITLE
[1.18.1-9.2.3.77] JEI causes crash when used in conjuction with JourneyMap

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#2683] opened 2022-01-17 00:02 UTC
Hello,
When in the JourneyMap menu and using the chat coordinate feature, upon pressing enter to chat, the game crashes. When I talked to the JourneyMap devs, they said this is an issue on your end.

# Steps to reproduce
- Use JourneyMap's chat coordinate feature
- Press enter to send a message of the coordinates pasted in by JourneyMap
- Game crashes upon pressing enter

Crash log from lastest.log

https://gist.github.com/DannyLeWasTaken/385d3b9c4c848817f5a53656a3170563

I had also tried this with .78 version and the problem had still persisted even when using the latest version of Forge, JourneyMap, and JEI.

**Comment by Ommina** [comment] 2022-01-17 01:26
JEI and JourneyMap are fairly ubiquitous.  I would be surprised if there were not a third factor in play.

Can you please give it a try without Optifine and NotEnoughCrashes?  As a start, anyway.

**Comment by mezz** [comment] 2022-01-17 03:04
Thanks for the report!
It looks like you reported this to JourneyMap here but deleted the contents? https://github.com/TeamJM/journeymap/issues/377

I ran into this same issue caused by another minimap mod here: https://github.com/mezz/JustEnoughItems/issues/2597
The discussion there should be helpful for TeamJM.
I suspect the same thing is happening with JourneyMap, or another mod may be involved?

I submitted a "fix" to Forge that will ensure the game crashes in this situation before it gets to JEI: https://github.com/MinecraftForge/MinecraftForge/pull/8296

**Comment by Ommina** [comment] 2022-01-17 04:47
Well this is embarrassing.  I completely forgot about the "enter on waypoint" crashes.  Sorry!

**Comment by mezz** [comment] 2022-01-17 04:48
No problem, thanks for your help Ommina!

**Comment by ghost** [comment] 2022-01-20 18:55
Ah sorry I didn't respond on time!
The crashes dooes seem to persist despite removing Optifine or NotEnoughCrashes, but it looks like the issue was resolved.
I deleted my other issue because I forgotten to follow the instructions in the issue template 😅

**Comment by mezz** [comment] 2022-01-20 19:13
Hmm sorry I don't follow you exactly, is this bug still happening? 
If you still see the bug, please open an issue with Journeymap and link back here, otherwise we can close this issue.

**Comment by ghost** [comment] 2022-01-21 03:39
Ah sorry, I badly worded it. I mean to say "It looks like has been identified". The issue still persists. I talked to the JourneyMap devs on the discord server and they said it was something on your end.

**Comment by mezz** [comment] 2022-01-21 22:13
Are you able to replicate this bug with just JEI and JourneyMap?

**Comment by mysticdrew** [comment] 2022-01-24 18:32
> Are you able to replicate this bug with just JEI and JourneyMap?

I am yes.

> Thanks for the report! It looks like you reported this to JourneyMap here but deleted the contents? [TeamJM/journeymap#377](https://github.com/TeamJM/journeymap/issues/377)
> 
> I ran into this same issue caused by another minimap mod here: #2597 The discussion there should be helpful for TeamJM. I suspect the same thing is happening with JourneyMap, or another mod may be involved?
> 
> I submitted a "fix" to Forge that will ensure the game crashes in this situation before it gets to JEI: [MinecraftForge/MinecraftForge#8296](https://github.com/MinecraftForge/MinecraftForge/pull/8296)

Thanks for this, looking at their crashlogs when they came in to our discord it looked like your ReflectionUtils was causing the issue. Which is why I directed them here, I have put in a fix for null screens in the KeyboardKeyPressedEvent.Post, which will be in journeymap 5.8.0beta12 for 1.16.5-1.18.1 when it is released.

**Comment by mezz** [comment] 2022-01-24 19:20
Thank you for checking and fixing this one @mysticdrew!

**Closed as completed by mezz** 2022-01-24 19:20 UTC
Labels: other mod
