### ISSUE TITLE
[1.12]Latest Version-Crash when going in controls menu

### ISSUE THREAD

**Issue by MathiewMay2** [mezz/JustEnoughItems#900] opened 2017-06-14 23:21 UTC
Game will crash when going in controls menu to change basic game keybinds realy anoying need to uninstall mod every time i change something PLZ FIX

**Comment by GirafiStudios** [comment] 2017-06-14 23:23
Was fixed in Forge version 14.21.0.2324.

**Comment by MathiewMay2** [comment] 2017-06-14 23:24
Thanks for fast reply but game crash when starting the mod in 14.21.0.2324 while using liteloader for voxel map

**Comment by GirafiStudios** [comment] 2017-06-14 23:26
If that is the case, could you then please pastebin the crash log?

**Comment by MathiewMay2** [comment] 2017-06-14 23:28
Never mind it seems like NoMansLib crash while loading in 14.21.0.2324 
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from NoMansLib (nmmlib)

i will check with them thanks for your time 👍

**Comment by GirafiStudios** [comment] 2017-06-14 23:39
Well good you figured it out. Another time, please make sure it is a Forge issue before reporting it here.
Also please close this issue. You can do that right next to the "Comment" button.

**Closed as completed** 2017-06-14 23:41 UTC
Labels: duplicate

**Comment by mezz** [comment] 2017-06-17 21:08
Thanks for the report!
This is a duplicate of #893
This was a Forge bug (MinecraftForge/MinecraftForge#3985) and has been fixed in the latest version.
