### ISSUE TITLE
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)

### ISSUE THREAD

**Issue by Wolfy618** [mezz/JustEnoughItems#2725] opened 2022-02-18 12:09 UTC
Got this error when loading up a personal mod pack in 1.12.2. (Java fully updated.)

Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)

FULL LOGS: https://pastebin.com/qAHAZRPA

Thanks in Advanced.

**Comment by xkeksi** [comment] 2022-02-18 15:31
???????? it says out of memory increase your maximum ram minecraft can use....

**Comment by Wolfy618** [comment] 2022-02-19 00:29
Okay, i already have 8gb in, ill try more

**Comment by Ommina** [comment] 2022-02-19 02:37
Given the error message, and the fact that you only have 87 mods loaded, you may also consider trying allocating less memory, not more.  Try 5 or even 4GB.

Yes, I appreciate that feels counterintuitive, but the error message isn't "I'm out of heap space", but "I've spent too much time collecting garbage".

**Comment by Wolfy618** [comment] 2022-02-19 04:43
I tried 4.5GB, This is what happened. 

New Crash Log: https://pastebin.com/BmBW3UpD

**Comment by Ommina** [comment] 2022-02-19 05:58
Phooey.  Try 3GB.  If that doesn't work, revert to 4.5 and add -XX:-UseGCOverheadLimit to the command line.  The latter will disable the error, but may just change the problem from 'crashes' to 'locks up', which many might consider a dubious improvement.

But it might also just work, so it's worth trying.

Is this a personal pack, or is it widely available?

**Comment by Wolfy618** [comment] 2022-02-19 06:06
Okay ill try that stuff, but quick question. To add to the command line, do I add it to JVM Arguments?

Its a personal pack

**Comment by Ommina** [comment] 2022-02-19 07:05
Yes, just add it to the JVM arguments.   (In fact, it IS a JVM argument.)

Thanks on the personal pack question.  That leaves open the possibility that it is some mod, or combination of mods, that are making life difficult for Java.  I'm pretty confident that JEI is not at fault here (indeed, JEI doesn't appear in your second crash report), but that's small consolation when you just want the thing to work.

**Comment by Wolfy618** [comment] 2022-02-19 07:34
https://pastebin.com/HSr68aJ8

New crash, changed from 3GB to 4.5GB and added the JVM Argument.

**Comment by Ommina** [comment] 2022-02-19 09:50
That looks like the debug.log -- I don't see a crash there, although there are some exceptions being thrown by 'Nef's Medieval decoration', but I can't promise that's creating a crash.  Do you have a fresh crash log?

(And I hope mezz isn't especially annoyed that we're continuing this here.)

**Comment by Wolfy618** [comment] 2022-02-19 10:43
Okay, I ran the game again. but after like 4 mins of loading it doesn't respond and crash. The exit code is -805306369.

https://pastebin.com/nFeEm3L1

**Comment by mezz** [comment] 2022-02-21 19:24
Weird, I've actually never seen this error before and I had to look it up.
This isn't caused by JEI so I will close the issue, but please feel free to continue discussing and working out the error here if that's helpful!

**Closed as completed by mezz** 2022-02-21 19:24 UTC
