### ISSUE TITLE
1.8.9-Forge 11.15.1.1726 Crash Called Already Building

### ISSUE THREAD

**Issue by WenXin20** [mezz/JustEnoughItems#155] opened 2016-02-05 01:28 UTC
Crashes when searching or scrolling using the arrow buttons, says something about the minesweeper mod, but even after i removed that mod, it crashes with a different mod in the crash log.
Crash Log:
(https://github.com/mezz/JustEnoughItems/files/118507/crash-2016-02-04_19.22.31-client.txt)

**Comment by mezz** [comment] 2016-02-05 02:08
Thanks for the report!
I'm not able to reproduce this issue. Please try removing as many mods as you can and see if you can find the one causing the conflict.
![2016-02-04_18 06 53](https://cloud.githubusercontent.com/assets/916092/12836059/3ed00862-cb6a-11e5-9aba-af45664cd4d5.png)
It may help to try and see if this issue also happens in the creative menu, without JEI (press Control-O to close JEI).

**Comment by WenXin20** [comment] 2016-02-05 02:31
Ok, I do know that when I type tan for tangle log with the agricultural Revolution Mod  is when it crashes. I will try to figure out what crashes it.

**Comment by mezz** [comment] 2016-02-05 16:35
I am closing this because I believe it is not an issue with JEI. 
Please report the issue to the Agricultural Revolution Mod and link back here.

**Closed as completed by mezz** 2016-02-05 16:35 UTC
Labels: other mod
