### ISSUE TITLE
[Bug]: "Tooltip error, see logs"

### ISSUE THREAD

**Issue by PemonBit** [mezz/JustEnoughItems#3521] opened 2024-05-27 02:03 UTC
### Steps to Reproduce the Bug

After instaling modpack on the server jei crafting recepies just dosen;t work.

### Expected Behavior

JEI should just show recepies.

### Actual Behavior

On all items I only see "Tooltip error, see logs".

### latest.log

https://gist.github.com/PemonBit/0049b98b8ddf66f5e15b7781fe96c587

**Comment by Veynam** [comment] 2024-06-09 21:10
Delete shield expansion, that mod is causing this issue for me

**Comment by mezz** [comment] 2024-06-11 05:23
Thanks for the report! This happens when a modded item crashes. In previous versions of JEI it would just crash the game.
Here, JEI tried to stop the whole game from crashing but something in the system might still be really broken.
Try the latest release of JEI from today, I updated it to try to contain the damage a bit better.

**Comment by mezz** [comment] 2024-06-11 05:23
Duplicate of https://github.com/mezz/JustEnoughItems/issues/3473

**Closed as not planned by mezz** 2024-06-11 05:23 UTC
