### ISSUE TITLE
[Suggestion]: CTRL + A to highlight everything in search bar.

### ISSUE THREAD

**Issue by andylmfao** [mezz/JustEnoughItems#2986] opened 2022-09-11 13:50 UTC
### Suggestion

title, a simple addition of being able to CTRL + A highlight the inventory search bar just like REI does it.

**Comment by mezz** [comment] 2022-09-11 21:38
Thanks for the suggestion!
This should already work, can you confirm it works if you only have JEI installed?

**Comment by andylmfao** [comment] 2022-09-12 13:18
Yeah it does work with Only JEI. Weird, In ATM7 it just straight up doesn't work. Is it an option in the config somewhere? (Also, another suggestion which might need another thread, a CTRL Click to quick craft from REI would also be cool.)

**Comment by andylmfao** [comment] 2022-09-12 17:41
Update. I figured out what it was. Turns out It's an issue with inventories. Whenever I open anything that Isn't the player inventory, I lose the ability to CTRL + A. Very strange.

**Comment by mezz** [comment] 2022-09-12 18:09
If JEI is working fine by itself, this is caused by a conflict with another mod. 
Can you remove mods and see which one is causing the conflict?

**Comment by andylmfao** [comment] 2022-09-13 13:23
I'm on ATM7, that would take quiet some time. Would a debug/normal log suffice?

**Comment by mezz** [comment] 2022-09-13 17:19
I was able to find another bug reported here for the same thing: https://github.com/mezz/JustEnoughItems/issues/2807
It looks like this is a mod conflict with FTB Mods and has been reported here: https://github.com/FTBTeam/FTB-Mods-Issues/issues/262
Hope that helps. I'll close this issue as a duplicate.

**Closed as completed by mezz** 2022-09-13 17:19 UTC
Labels: duplicate

**Comment by desht** [comment] 2022-10-07 14:36
This will be fixed in the next FTB Library release, but the problem is more subtle than a straightforward FTB Lib bug, so I'll comment here with the technical detail...

I originally thought this was FTB Lib somehow swallowing the Ctrl-A keypress, but not at all.  The keypress actually gets through to JEI just fine.  The actual problem is due to the exclusion area that FTB Lib reports to JEI (via `getGuiExtraAreas()`)

The area reported by FTB Lib has a negative (X,Y) value - (-1, -1) to be precise (due to a bounding box calculation and expansion of that box by 2 pixels in each direction).  JEI doesn't like negative coordinates, and silently clamps the -1 values to 0 in  `GuiScreenHelper#updateExclusionAreas()`, the `ImmutableRect2i` constructor to be specific.

Problem with that is, on the next frame JEI compares that updated rectangle with the value that FTB Lib gives - and it's mismatched, every time. So JEI goes and calls `updateScreen()` on its two overlays, every time, and one of the results of that is that the filter textfield loses its selection.

(That was... interesting... to track down)

Couple of possible solutions:
* Throw an exception if the X/Y values are negative.  Risky, since it could crash a lot of existing code.
* Just allow negative X/Y values in the exclusion areas.  If they're only used to check for overlaps (which, looking at code, appears to be the case), this should be pretty safe?

**Comment by mezz** [comment] 2022-10-07 17:10
Thank you for the in-depth analysis and fix @desht, I really appreciate it.

Could you open an issue for this JEI bug?
Specifically this part
> JEI compares that updated rectangle with the value that FTB Lib gives - and it's mismatched, every time. So JEI goes and calls updateScreen() on its two overlays, every time, and one of the results of that is that the filter textfield loses its selection.

I think there is another solution, which is to make sure the comparison always happens after the clamping so that it's consistent.
