### ISSUE TITLE
[Bug]: Incorrect smithing recipes shown

### ISSUE THREAD

**Issue by AzrannAVANA** [mezz/JustEnoughItems#3713] opened 2024-08-27 15:49 UTC
### Steps to Reproduce the Bug

\> Look into the netherite upgrade recipes
\> Misinformation

### Expected Behavior

The correct recipes should be shown, with the correct components...
![image](https://github.com/user-attachments/assets/046cdc2b-ebf2-4c0b-b2d7-759ceccd4f32)

### Actual Behavior

As an example, the netherite sword recipe shows a netherite sword instead of a diamond one...
![image](https://github.com/user-attachments/assets/92bf1428-b3c4-44b3-9462-243621945e48)

And it goes for any recipes even custom made, such as the same recipe modified to output dirt instead...
![image](https://github.com/user-attachments/assets/4244f3b5-d432-4cfe-a189-a5244616f04c)
![image](https://github.com/user-attachments/assets/05129296-301b-4b91-bde7-7a20ddbeeb7e)

It would appear that the output item is put over the middle input, leading to an incorrect recipe shown.

### Mod Pack URL (Optional)

https://modrinth.com/modpack/vortex-foundations

### Mod Pack Version (Optional)

2.4-A2

### Extra Notes (Optional)

The recipes themselves are fine, it's just JEI showing them incorrectly-

### latest.log

https://gist.github.com/AzuryxxVortex/68c845e7e996dd0a143b858a8b1fbd7c

**Comment by mezz** [comment] 2024-08-28 12:46
Thanks for the report!
This is fixed today, and a duplicate of https://github.com/mezz/JustEnoughItems/issues/3693

**Closed as not planned by mezz** 2024-08-28 12:46 UTC
