### ISSUE TITLE
Help! The game crashed whilst updating screen events The game crashed whilst updating screen events Error: java.lang.NoSuchMethodError: mezz.jei.runtime.JeiRuntime.getItemListOverlay()Lmezz/jei/gui/overlay/IngredientListOverlay;

### ISSUE THREAD

**Issue by Buddly3** [mezz/JustEnoughItems#1344] opened 2018-08-26 21:48 UTC
Every time I open Minecraft up it crashes. I only have the JEI CodeChicken and NEI mods.
My crash report:
---- Minecraft Crash Report ----
// Oops.

Time: 8/26/18 2:39 PM
Description: Updating screen events

java.lang.NoSuchMethodError: mezz.jei.runtime.JeiRuntime.getItemListOverlay()Lmezz/jei/gui/overlay/IngredientListOverlay;
	at codechicken.nei.jei.JEIIntegrationManager.getTextFieldFilter(JEIIntegrationManager.java:124)
	at codechicken.nei.jei.gui.ContainerEventHandler.onGuiMouseEventpre(ContainerEventHandler.java:40)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_56_ContainerEventHandler_onGuiMouseEventpre_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:500)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1758)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at codechicken.nei.jei.JEIIntegrationManager.getTextFieldFilter(JEIIntegrationManager.java:124)
	at codechicken.nei.jei.gui.ContainerEventHandler.onGuiMouseEventpre(ContainerEventHandler.java:40)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_56_ContainerEventHandler_onGuiMouseEventpre_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:500)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.GuiMainMenu
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1758)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 197687096 bytes (188 MB) / 553648128 bytes (528 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2758 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID             | Version      | Source                                        | Signature                                |
	|:------ |:-------------- |:------------ |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft      | 1.12.2       | minecraft.jar                                 | None                                     |
	| UCHIJA | mcp            | 9.42         | minecraft.jar                                 | None                                     |
	| UCHIJA | FML            | 8.0.99.99    | forge-1.12.2-14.23.4.2758.jar                 | None                                     |
	| UCHIJA | forge          | 14.23.4.2758 | forge-1.12.2-14.23.4.2758.jar                 | None                                     |
	| UCHIJA | codechickenlib | 3.2.1.351    | CodeChickenLib-1.12.2-3.2.1.351-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | jei            | 4.12.0.215   | jei_1.12.2-4.12.0.215 (1).jar                 | None                                     |
	| UCHIJA | nei            | 2.4.1        | NotEnoughItems-1.12.2-2.4.1.233-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4358' Renderer: 'Intel(R) HD Graphics'
	Launched Version: 1.12.2-forge1.12.2-14.23.4.2758
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 10.18.10.4358, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (United Kingdom)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Pentium(R) CPU N3540 @ 2.16GHz
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by TehNut** [comment] 2018-08-26 22:10
Duplicate of #1330 
This is an NEI issue

**Closed as completed** 2018-09-06 05:44 UTC
Labels: duplicate
