### ISSUE TITLE
Its says i need forge 14.23.0.2500 or above technical info  [07:57:11] [main/DEBUG] [Forge Mod Loader/]: Mod Forge Mod Loader is missing a pack.mcmeta file, substituting a dummy one ALSO i am running minecraft version 1.12.2 if i run on 1.12 forge will say that its needs to be 1.12.2 or above 

### ISSUE THREAD

**Issue by XtabtyteX** [mezz/JustEnoughItems#1043] opened 2017-11-14 13:04 UTC
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by mezz** [comment] 2017-11-15 04:29
Thanks for the report!
You need Minecraft 1.12.2 and Forge 14.23.0.2500 or above.
You have a Forge version below 14.23.0.2500.

**Comment by mezz** [comment] 2017-11-15 04:30
Duplicate of https://github.com/mezz/JustEnoughItems/issues/1032

**Closed as completed by mezz** 2017-11-15 04:30 UTC
Labels: duplicate
