### ISSUE TITLE
Despite client and server installation of JEI, Move Items button doesn't work

### ISSUE THREAD

**Issue by imawookieman** [mezz/JustEnoughItems#1645] opened 2019-07-22 17:16 UTC
I am also having this issue.

Forge 1.12.2 using the latest JEI and no other mods, I get the same thing.

Karl

**Comment by mezz** [comment] 2019-08-08 05:42
Thanks for the report!
Please keep reports of the same thing together.
Duplicate of https://github.com/mezz/JustEnoughItems/issues/1615

**Closed as completed by mezz** 2019-08-08 05:42 UTC
Labels: duplicate
