### ISSUE TITLE
[Crash]: Game crashes when I check a recipe using JEI

### ISSUE THREAD

**Issue by vampirehuman1** [mezz/JustEnoughItems#3523] opened 2024-05-29 07:58 UTC
### Steps to Reproduce the Crash

I'm not sure if i specifically have all steps right as this is a customised modpack i am using but:

ITEM RECIPE CRASH
*Have mystical Agriculture
*Have JEI
*Click to view the recipe for seedslike 'Apatite Seeds', 'Saltpeter Seeds' using R (I did so due to the fact i was in the menu and did not see a mod that could have placed these into my game
*Complete white screen.
This used to be complete crash with no option of saving it, but now it white screens and i have to manually close the game myself after i uninstalled my shaders to realise it wasnt the shaders. 
![image](https://github.com/mezz/JustEnoughItems/assets/171126761/b9df94d9-b582-4605-b40f-575fb11293c4)

I'm not sure if it's some specific step I have missed.

### Mod Pack Version (Optional)

1.19.2

### Extra Notes (Optional)

I'm not sure if there are other steps which are involved, this is just how i am doing this. There is also an issue where if i click a tab that shows 'Crops' in the botany Pots mod, it does the same thing but instantly closes the game but that is probably a separate issue. I have no mod that should have brough tthese items, In the JEI menu when i search their names, it doesn't show an item itis linked to meaning whatever it is, its part of a mod i dont have. Though when I uninstalled my Shaders to test, and realised the issue was still there, even after reinstall of the shaders I use, it still white screens now instead of instantly crashes. I am, however. stuck on that white screen forcing me to close the game completely. 

### Crash Report

https://gist.github.com/vampirehuman1/53ac41245f6eea59d09de3f1e18473a7

**Comment by mezz** [comment] 2024-07-18 10:01
Thanks for the report! This should be fixed in the next release for 1.19.2, which should be available in around 15-20 minutes.

The issue was caused by a GUI going off the left or top edge of the screen. JEI crashed when trying to figure out how to draw next to it.

**Closed as completed by mezz** 2024-07-18 10:01 UTC
