### ISSUE TITLE
(1.11.2) world doesn't load and block on loading screen

### ISSUE THREAD

**Issue by 0Navis0** [mezz/JustEnoughItems#844] opened 2017-05-04 00:13 UTC
I started to get a strange issue recently, I can't load or create more worlds, Minecraft blocks ternally into the loading screen. I looked into the log and noticed this https://pastebin.com/rLdRx3SW. It seems JEI is linked to this issue. However I don't get any crash and so crash report. I tried to load world without JEI and everything works fine, so it seems to really come from JEI.

**Comment by mezz** [comment] 2017-05-04 00:22
Thanks for the report!
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/842
What mods do you have that add potions, so I can test?

**Closed as completed** 2017-05-04 00:32 UTC
Labels: duplicate

**Comment by 0Navis0** [comment] 2017-05-04 01:18
Sorry for the duplication, thanks for the fix. So far the mods I use which add potions are Blood Magic, Botania, Reliquary, Extra Alchemy, Potions Core and Not Enough Potions.
