### ISSUE TITLE
 Ticking Entity Crash With BDLib Extra Crash Report/Follow Up to Other Posts

### ISSUE THREAD

**Issue by Squirtles** [mezz/JustEnoughItems#233] opened 2016-03-30 20:29 UTC
https://gist.github.com/mezz/ab689c282694abbed13a172d04aae416

**Comment by mezz** [comment] 2016-04-02 23:25
Duplicate of https://github.com/mezz/JustEnoughItems/issues/230

**Closed as completed by mezz** 2016-04-02 23:25 UTC
Labels: duplicate
