### ISSUE TITLE
[Crash]: Can't open inventory

### ISSUE THREAD

**Issue by EricBatista** [mezz/JustEnoughItems#2858] opened 2022-06-17 00:39 UTC
### Steps to Reproduce the Crash

1- Open Inventory
2- The game will crash

### Mod Pack URL (Optional)

https://cdn.discordapp.com/attachments/924737435827601428/987154295092809789/Testpack-v00.zip

### Crash Report

https://gist.github.com/EricBatista/4f2e7089188f5acc8c5910cf82db0d9f

**Comment by mezz** [comment] 2022-06-17 00:50
Thanks for the report!
I think something must have broken earlier and put JEI into a bad state.
Can you please upload your `latest.log` here so I can hopefully see what happened?

**Comment by EricBatista** [comment] 2022-06-17 01:05
https://gist.github.com/EricBatista/9bbfbde40028c1c038f5dc83580c9df9

Here you go!

**Comment by Moobien** [comment] 2022-06-17 06:12
have one from me too Mezz https://gist.github.com/Moobien/a1fecfcabceaa16d47670eb721de15bd

**Comment by Moobien** [comment] 2022-06-17 06:13
Rolling back to 196 works fine

**Comment by mezz** [comment] 2022-06-17 23:50
Thanks for the logs!
I can see you both have the same crash earlier in the log:
```
java.lang.ClassNotFoundException: mezz.jei.common.plugins.vanilla.VanillaPlugin
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at mezz.jei.forge.util.AnnotatedInstanceUtil.getInstances(AnnotatedInstanceUtil.java:47) ~[jei-1.18.2-9.7.0.196.jar%2399!/:9.7.0.196]
	at mezz.jei.forge.util.AnnotatedInstanceUtil.getModPlugins(AnnotatedInstanceUtil.java:27) ~[jei-1.18.2-9.7.0.196.jar%2399!/:9.7.0.196]
	at mezz.jei.forge.startup.ClientLifecycleHandler.<init>(ClientLifecycleHandler.java:74) ~[jei-1.18.2-9.7.0.196.jar%2399!/:9.7.0.196]
	at mezz.jei.forge.JustEnoughItemsClient.onRegisterReloadListenerEvent(JustEnoughItemsClient.java:39) ~[jei-1.18.2-9.7.0.196.jar%2399!/:9.7.0.196]
	at mezz.jei.forge.JustEnoughItemsClient.lambda$register$0(JustEnoughItemsClient.java:28) ~[jei-1.18.2-9.7.0.196.jar%2399!/:9.7.0.196]
...
```

This is very strange, I will try to look into it more.

**Comment by mezz** [comment] 2022-06-17 23:55
I think you have two different versions of JEI? Can you take a look at this:
```
[21:33:13] [main/INFO]: Found mod file jei-1.18.2-9.7.0.196.jar of type MOD with locator {mods folder locator at C:\Minecraft\CurseForge\Instances\CearenseCraft\mods}
[21:33:13] [main/INFO]: Found mod file jei-1.18.2-forge-10.1.0.202.jar of type MOD with locator {mods folder locator at C:\Minecraft\CurseForge\Instances\CearenseCraft\mods}
```

**Comment by mezz** [comment] 2022-06-18 05:03
Based on the logs, I think you both have the same problem: there are two different versions of JEI in your pack

**Comment by Moobien** [comment] 2022-06-18 08:44
I am suspecting Curseforge may have been up to its old tricks of not removing old versions of mods when updating.  reinstalled 202 and ensured no other JEI installed.  got the following crashes. sorry the latest.log is zipped, gist refuses to accept a 41mb log file.


[latest.zip](https://github.com/mezz/JustEnoughItems/files/8933249/latest.zip)
https://gist.github.com/Moobien/727820806286621082b23fa5f3f54989

**Comment by mezz** [comment] 2022-06-18 17:58
Thanks, that new crash looks to be related to #2851
I have submitted a new fix that should work around the crash caused by a modded fluid.

I think the one here is resolved so I will closed it, but please try out the latest version and open new issues if you run into any more problems!

**Closed as completed by mezz** 2022-06-18 17:58 UTC
Labels: troubleshooting

**Comment by Moobien** [comment] 2022-06-18 20:29
Will do Mezz
