### ISSUE TITLE
JEI and JER crash

### ISSUE THREAD

**Issue by adran06** [mezz/JustEnoughItems#1695] opened 2019-08-22 05:47 UTC
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

https://paste.dimdev.org/xoladirife.mccrash Here's a copy of the error. Don't know what it means. Just know it's caused by JEI and JER.

**Comment by way2muchnoise** [comment] 2019-08-22 08:15
Duplicate of https://github.com/way2muchnoise/JustEnoughResources/issues/198, issue is not enough RAM allocated.

**Closed as completed** 2019-09-02 01:21 UTC
