### ISSUE TITLE
Issues with TiCon Recipes

### ISSUE THREAD

**Issue by wylderhoads1809** [mezz/JustEnoughItems#606] opened 2016-11-14 02:43 UTC
The part builder recipe only shows as being only craftable with Firewood (not the case, any wood will work) and the Tool Forge doesn't register as having any crafting recipe.

**Comment by mezz** [comment] 2016-11-14 03:06
Thanks for the report!
This is a Tinker's issue, reported here: SlimeKnights/TinkersConstruct#2539
Duplicate of https://github.com/mezz/JustEnoughItems/issues/571

**Closed as completed by mezz** 2016-11-14 03:06 UTC
Labels: duplicate
