### ISSUE TITLE
Minetweaker Recipes that use NBT data not showing correct recipe is JEI

### ISSUE THREAD

**Issue by goosezilla** [mezz/JustEnoughItems#653] opened 2016-12-06 12:51 UTC
https://github.com/jaredlll08/ModTweaker/issues/394

Seems to be displaying the item with empty NBT tag when required to use specific tags. I think basically it seems switched around somehow. When onlyWithTag is used then it displays only the NBTless version but when you use withTag it will show the recipe with specific tags but will allow the item with ANY tag to complete the craft.

I think this mezz/JustEnoughItems#415 is the same issue

**Comment by Lanse505** [comment] 2016-12-06 13:06
TLDR; The issue is with JEI not displaying said item with the correct NBT.
This should be a JEI issue since CrT don't deal with JEI Picking-Up the recipes.

**Comment by AEnterprise** [comment] 2016-12-06 14:25
sounds like whatever is passing the recipes to JEI isn't giving JEI the correct info then to JEI as i know other mods work with NBT recipes just fine

**Comment by goosezilla** [comment] 2016-12-10 15:14
any ideas on this @mezz ? could really do with this being fixed as more highly configured modpacks come out

**Comment by mezz** [comment] 2016-12-10 21:26
Here's a test recipe I made in JEI that has an item with NBT for the input, it displays correctly.

![2016-12-10_13 25 10](https://cloud.githubusercontent.com/assets/916092/21076279/44d1131c-bedc-11e6-8a61-011abe6daeba.png)

**Comment by mezz** [comment] 2016-12-10 21:30
Here's one with an enchantment, a better example:

![2016-12-10_13 29 58](https://cloud.githubusercontent.com/assets/916092/21076306/cb17d7b2-bedc-11e6-9b4d-2e272e3a654d.png)

**Comment by goosezilla** [comment] 2016-12-11 00:15
Have you tried the same recipes using input items that don't exactly match those nbt values? Ie I think in your example it would accept any diamond pick.

**Comment by mezz** [comment] 2016-12-11 02:34
I overrode `ShapelessRecipes` so that it requires matching NBT.
It's just the same except it uses `ItemStack.areItemStacksEqual(itemstack, itemstack1)` for comparison.
Here's the full code for the recipe I added:
```java
ItemStack pickaxeWithNbt = new ItemStack(Items.DIAMOND_PICKAXE);
pickaxeWithNbt.addEnchantment(Enchantments.FORTUNE, 3);
CraftingManager.getInstance().addRecipe(new ShapelessRecipes(new ItemStack(Items.DIAMOND), Collections.singletonList(pickaxeWithNbt)) {
    @Override
    public boolean matches(InventoryCrafting inv, World worldIn) {
        List<ItemStack> list = Lists.newArrayList(this.recipeItems);

        for (int i = 0; i < inv.getHeight(); ++i) {
            for (int j = 0; j < inv.getWidth(); ++j) {
                ItemStack itemstack = inv.getStackInRowAndColumn(j, i);
                if (!itemstack.isEmpty()) {
                    boolean flag = false;
                    for (ItemStack itemstack1 : list) {
                        if (ItemStack.areItemStacksEqual(itemstack, itemstack1)) {
                            flag = true;
                            list.remove(itemstack1);
                            break;
                        }
                    }

                    if (!flag) {
                        return false;
                    }
                }
            }
        }
        return list.isEmpty();
    }
});
```

And it works as expected in the crafting table, only accepting a pickaxe with fortune 3:

![2016-12-10_18 31 28](https://cloud.githubusercontent.com/assets/916092/21077649/2621060e-bf07-11e6-88aa-c40cd53351b3.png)
![2016-12-10_18 31 31](https://cloud.githubusercontent.com/assets/916092/21077650/262514e2-bf07-11e6-9546-5952a01071f5.png)

**Comment by mezz** [comment] 2016-12-11 23:26
Closing this because I think I have shown proof that this is not a JEI issue.

**Closed as completed by mezz** 2016-12-11 23:26 UTC
Labels: duplicate
