### ISSUE TITLE
Freeze Upon Searching or Crashes when flipping through item pages.

### ISSUE THREAD

**Issue by Shade-Jonezy** [mezz/JustEnoughItems#739] opened 2017-02-18 02:02 UTC
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

I'm using the most current version of Forge (13.20.0.2232) and your most recent JEI.  As stated in the title of this issue when you try to search for items it freezes or flip through the pages of the items, mine crashed before it would go to page six, it stalls for a bit and then crashes soon after.  The only version of Forge that doesn't seem to do this is (13.20.0.2222).  So I don't get why it crashes on later Forge Updates.  I am only using JEI.

**Comment by mezz** [comment] 2017-02-18 02:22
Thank you for reporting!
If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

**Comment by Shade-Jonezy** [comment] 2017-02-18 18:29
When I tried searching items it froze my computer so the only crash report I could get and link involved the page turning.  Here is the link: https://gist.github.com/Shade-Jonezy/c85e1a8e6a6039dbbd1644fc4ed6cd6b

**Comment by mezz** [comment] 2017-02-18 18:53
This seems to be a duplicate of #714
It is an Optifine bug, fixed in Optifine preview B7 for 1.11.2

Try without Optifine and if you still have an issue please send me the new crash report.

**Comment by mezz** [comment] 2017-02-20 08:35
@Shade-Jonezy any luck?

**Closed as completed** 2017-03-02 00:58 UTC
Labels: needs followup
