### ISSUE TITLE
Just Enough Items API

### ISSUE THREAD

**Issue by leonbtww** [mezz/JustEnoughItems#1966] opened 2020-05-16 23:35 UTC
So, i wrote some code for my custom Furnace and got that error.

```
[01:33:00] [Client thread/WARN] [FML]: ****************************************
[01:33:00] [Client thread/WARN] [FML]: * The API JustEnoughItemsAPI from source C:\Users\minep\.gradle\caches\modules-2\files-2.1\mezz.jei\jei_1.12.2\4.8.5.159\de1bdc5f25dce59836e303ac18e0863b9120c579\jei_1.12.2-4.8.5.159.jar is loaded from an incompatible classloader. THIS WILL NOT WORK!
[01:33:00] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.ModAPIManager$APIContainer.validate(ModAPIManager.java:114)
[01:33:00] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.ModAPIManager.registerDataTableAndParseAPI(ModAPIManager.java:174)
[01:33:00] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.ModAPIManager.manageAPI(ModAPIManager.java:232)
[01:33:00] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:569)
[01:33:00] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
[01:33:00] [Client thread/WARN] [FML]: *  at net.minecraft.client.Minecraft.init(Minecraft.java:514)...
[01:33:00] [Client thread/WARN] [FML]: ****************************************
```

**Comment by leonbtww** [comment] 2020-05-22 18:28
https://gist.github.com/leonbtww/552312a2c3b82c65edeb3f377d8a81c4

**Comment by leonbtww** [comment] 2020-06-21 20:20
Hm

**Comment by mezz** [comment] 2020-06-22 00:17
Thanks for the report, this is a duplicate of: https://github.com/mezz/JustEnoughItems/issues/627
You can safely ignore this warning.

**Closed as completed by mezz** 2020-06-22 00:17 UTC
