### ISSUE TITLE
[Crash]: jei-1.19.2-forge-11.5.0.297

### ISSUE THREAD

**Issue by GrizzBear01** [mezz/JustEnoughItems#3083] opened 2022-12-31 17:45 UTC
### Steps to Reproduce the Crash

1, join single player world
2, wait a few seconds after world loads or press any button then game exits

### Extra Notes (Optional)

i play single player on a custom modpack for personal use. game launches fine but after entering new world or rejoining old one the game closes after a few seconds. no crash report is generated but debug log says (if im reading it right)

Caused by: java.lang.ClassNotFoundException: mezz.jei.common.gui.overlay.IngredientListOverlay

### Crash Report

https://gist.github.com/GrizzBear01/30d8181cd75223596132fd8bd592c073

**Comment by thecrazygamer25** [comment] 2023-01-03 08:37
I'm getting the same crash note. What mods are you using? Maybe if we have a few or one in common then we can narrow it down

**Comment by RalavWarnoff** [comment] 2023-01-04 12:19
> I'm getting the same crash note. What mods are you using? Maybe if we have a few or one in common then we can narrow it down

I have the same crash.

I'm using these mods:
1.19.2-YUNG-s-Better-Desert-Temples-v2.2.1-Forge
1.19.2-YUNG-s-Better-Mineshafts-v3.2.0-Forge
1.19.2-YUNG-s-Better-Strongholds-v3.2.0-Forge
alexsmobs-1.21.1-1.19.2
AutoRegLib-1.8.2-55
bettervillage-forge-1.19.2-2.0.0
citadel-2.1.1-1.19
configured-2.0.1-1.19.2
Create-1.19.2-v0.5.0g
Delightful-3.2.1-1.19-1.19.2
Farmer-s-Delight-1.2-1.19
Furniture-Mod-7.0.0-pre34-1.19.1
Infernal-Expansion-Release-2.5.3-for-Minecraft-1.19.2
jei-1.19.2-forge-11.5.0.297
Library-ferret-3.0.0-Forge-1.19.2
moonlight-1.19.2-2.1.20-forge
Quark-3.3-377-1.19.2
Rotten-Creatures-Forge-1.19.2-v1.0.1
supplementaries-1.19.2-2.2.29
Towns-and-Towers-v.1.10-_FORGE-1.19.2
YungsApi-1.19.2-Forge-3.8.0

**Comment by ghost** [comment] 2023-01-05 05:48
are either of you using MoreOverlays ?

**Comment by thecrazygamer25** [comment] 2023-01-05 06:38
I was using the More Overlays Updated. I looked through the full crash report and there was a reference to it. I turned it off and it started working as normal

**Comment by ghost** [comment] 2023-01-05 11:11
this is probably a duplicate of #3064

**Comment by mezz** [comment] 2023-01-19 01:47
Thanks for the report!
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/3064

**Closed as not planned by mezz** 2023-01-19 01:47 UTC
