### ISSUE TITLE
My game crashes when i try to load or create a new world

### ISSUE THREAD

**Issue by Skogen787** [mezz/JustEnoughItems#1659] opened 2019-08-05 18:48 UTC
When i try to use this mod (currently on 1.14.4), my game crashes right before i load into a world, i have tryed without any mods other than JEI, but it still didn't work
Also, when it crashes it doesnt even give a crash report
What could be the problem, and what could i do or cant i do anything about it?

**Comment by Skogen787** [comment] 2019-08-05 18:50
When i try to use this mod (currently on 1.14.4), my game crashes right before i load into a world, i have tryed without any mods other than JEI, but it still didn't work
Also, when it crashes it doesnt even give a crash report
What could be the problem, and what could i do or cant i do anything about it?

**Comment by Tfarcenim** [comment] 2019-08-05 21:31
forge past 28.0.42 or so crashes jei because of breaking changes, making any world with it unusable

**Comment by Skogen787** [comment] 2019-08-05 21:42
Oh, that explains alot, thank you for explaining that, ill keep that in mind

**Comment by Alejandrom3** [comment] 2019-08-07 18:35
> forge past 28.0.42 or so crashes jei because of breaking changes, making any world with it unusable

So is someone going to fix that?

**Comment by mezz** [comment] 2019-08-08 05:23
Thanks for the report!
This is fixed in the latest version.
Duplicate of #1641

**Closed as completed by mezz** 2019-08-08 05:23 UTC
Labels: duplicate

**Comment by Alejandrom3** [comment] 2019-08-08 05:26
> Thanks for the report!
> This is fixed in the latest version.
> Duplicate of #1641

Latest version of jei? because i only see the "jei-1.14.3-6.0.0.8.jar" in curseforge. or you mean the forge version?

**Comment by mezz** [comment] 2019-08-08 05:57
This one, maybe it took some time to get approved by Curse:
https://www.curseforge.com/minecraft/mc-mods/jei/files/2757010
