### ISSUE TITLE
[Crash/Bug]: jei fails to load in 1.19

### ISSUE THREAD

**Issue by scp-3537** [mezz/JustEnoughItems#2882] opened 2022-07-10 01:08 UTC
### Steps to Reproduce the Crash

running jei in 1.19 on forge version 41.0.64 will cause the game to spit out an error and a crash log saying the mod failed to load

### Extra Notes (Optional)

this seems to be a common occurence with a lot of 1.19 mods so it might be something im doing wrong

### Crash Report

https://gist.github.com/scp-3537/fdd68382aed2807f4e69aa5231a02d12

**Comment by Mrbysco** [comment] 2022-07-10 02:04
According to that crash report you're running `Roughly Enough Items` not JEI

**Comment by scp-3537** [comment] 2022-07-10 02:30
oops wrong crash report
tho both are similar, just jei instead of rei
also now its acting differently
wth
https://pastebin.com/yhPb025q
heres the new crashlog ig? im so confused rn

**Comment by Mrbysco** [comment] 2022-07-10 12:56
Duplicate of #2881
It has to do with changes that occurred in Forge 41.0.64+

**Comment by TheRTGGaming** [comment] 2022-07-10 20:40
On latest forge 1.19 - 41.0.91, jei-1.19-forge-11.0.0.206 crashes before the game loads. I can provide the crash report.

**Comment by sekwah41** [comment] 2022-07-12 09:26
@TheaRTGGaming there was a lot of renaming in forge so it's expected a lot of mods would be broken. 94 I believe brought the main last changes for renaming that were announced for now at least.

**Comment by mezz** [comment] 2022-07-14 00:49
Thanks for the report!
Please try using the latest versions of JEI and Forge, this should be fixed.

**Closed as completed by mezz** 2022-07-14 00:49 UTC
