### ISSUE TITLE
[Bug]: Hotkeys trigger while using JEI search

### ISSUE THREAD

**Issue by jackyurchiksparrow** [mezz/JustEnoughItems#3369] opened 2023-12-02 23:12 UTC
### Steps to Reproduce the Bug

1. Determine the hotkey to test (I picked IC2C's toggle key; set as "F")
2. Meet conditions for the hotkey to trigger, if any (in my case wear the jetpack and see that "F" turns it off and on successfully)
3. Open JEI, search something with the letter "F" in it.

### Expected Behavior

Following the steps to reproduce the bag 1-3 the fourth step must be:
4. Go on searching and watch that all hotkeys are blocked from executing while the search box is focused (or at least when the inventory is opened).

### Actual Behavior

4. Watch the jetpack triggers every time you press "F". (Same applied to AE2 terminal; it is set to synchro with JEI).
It does apply to all 

### Extra Notes (Optional)

Minecraft version: 1.12.2
The list of the active mods during the test:
appliedenergistics2-rv6-stable-7.jar
CodeChickenLib-1.12.2-3.2.3.358-universal.jar
IC2Classic-1.12-1.5.7.jar
jei_1.12.2-4.16.1.301.jar

### latest.log

https://gist.github.com/jackyurchiksparrow/c775b6455b73ebfca80516cd1f9687c0

**Comment by Aceplante** [comment] 2023-12-26 04:41
so annoying, is there a fix?

**Comment by jackyurchiksparrow** [comment] 2023-12-26 08:14
I had to change my hotkeys to ctrl + something to avoid it. Extremely unpleasant, I guess I will consider searching for an alternative mod when I have time.

**Comment by jackyurchiksparrow** [comment] 2024-03-25 09:16
Yes, it should

**Comment by Aceplante** [comment] 2024-03-26 21:27
plz fix

**Comment by jackyurchiksparrow** [comment] 2024-06-25 05:41
Yes, it should

**Comment by mezz** [comment] 2024-07-01 07:50
Thanks for the report.
Does this only apply to IC2C or does it impact every mod?
If JEI works with almost everything but IC2C isn't working, please make sure to report this to IC2C and link back here.

**Comment by jackyurchiksparrow** [comment] 2024-07-03 20:18
Created
https://github.com/TinyModularThings/IC2Classic/issues/1174

**Comment by Speiger** [comment] 2024-07-22 10:03
@mezz and @jackyurchiksparrow  this is not a jei bug.
Technically it's not even a ic2c bug because it is intended that keybindings work.
But the gui open thing is actually something i can backport so the jetpack won't disable in the gui but all other keys still act like normal.

But yeah you can close this.

Edit this is intended behavior for the following reason:
"F i am in situation that i can only die in but the jetpack keeps me alive, lets use a gui where i can save all my items, oh crap opening a gui shuts down my jetpack i wish there would have been a way for keys to still work when i am in the gui".
(though the jetpack disabling key should be an exception)

**Comment by mezz** [comment] 2024-07-22 11:56
Hello @Speiger, thank you for the insight into the situation.

I think it is normal for the GUI to interfere with your ability to survive in vanilla Minecraft, for example I cannot swing my sword if I am looking in my inventory. Of course the final decision is left to you, it is your mod, but I hope you can consider this as your choice may go against expectations or best practices, resulting in some confusion for players.

**Comment by Speiger** [comment] 2024-07-22 12:40
@mezz yes I agree on your example, but I also like to point out that context is always important.
But you are fully aware of that.

Anyways i will address the original reported issue (Jetpack disabling when typing) since it is a bug.
But disabling everything could lead to Softlocks in certain aspects since QoL features that prevent base damage (preventing machines accidentally blowing up) is also behind this implementation.
(You can only take out transformer upgrades out when you press a specific key, if you do that accidentally, which is easy without a second key required => BOOM)

Anyways thank you for redirecting the issue to me :)

**Closed as not planned** 2024-07-22 13:31 UTC
Labels: other mod

**Comment by Speiger** [comment] 2024-07-22 13:53
@mezz the update is published to CF so it should be released soon.

**Comment by mezz** [comment] 2024-07-22 22:42
Thank you Speiger
