### ISSUE TITLE
Updating Screen Events

### ISSUE THREAD

**Issue by captcookie** [mezz/JustEnoughItems#310] opened 2016-06-09 01:48 UTC
https://shrib.com/oENiD4SYiWsZ3nl?v=nc

Sample:
Time: 6/8/16 8:39 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
at mezz.jei.gui.ingredients.GuiItemStackFastList.set(GuiItemStackFastList.java:56)
at mezz.jei.gui.ItemListOverlay.updateLayout(ItemListOverlay.java:242)
at mezz.jei.gui.ItemListOverlay.onKeyPressed(ItemListOverlay.java:499)
at mezz.jei.input.InputHandler.handleKeyDown(InputHandler.java:199)
at mezz.jei.input.InputHandler.handleKeyEvent(InputHandler.java:189)
at mezz.jei.GuiEventHandler.onGuiKeyboardEvent(GuiEventHandler.java:129)

**Comment by mezz** [comment] 2016-06-09 03:46
Thanks for the report!
I think this is from another mod's broken item. I'll add a better error log so we can track it down.

**Comment by mezz** [comment] 2016-06-09 03:57
Try out [3.6.2.211.jar](http://minecraft.curseforge.com/projects/just-enough-items-jei/files/2306298)

**Comment by captcookie** [comment] 2016-06-09 04:00
Thanks! Ill let you know how it goes in the morning.

**Comment by Ozzymud** [comment] 2016-06-20 10:12
jei_1.9.4-3.6.7.216

java.lang.NullPointerException: Updating screen events

Full crash: http://paste.ee/p/s5Dm2

Lemme know what else I can provide/do mezz :)

Edit: seems it might be the FEI thing: https://github.com/elix-x/Forever-Enough-Items/issues/20

**Comment by mezz** [comment] 2016-06-20 20:41
@Ozzymud yes, that is a duplicate of https://github.com/mezz/JustEnoughItems/issues/320

**Comment by mezz** [comment] 2016-06-20 20:41
@captcookie any update?

**Comment by Ozzymud** [comment] 2016-06-21 21:36
All fixed on my end after updating to ForeverEnoughItems-1.0.11-1.9.4

**Comment by captcookie** [comment] 2016-06-22 21:57
yes ty

**Closed as completed** 2016-06-22 21:57 UTC
