### ISSUE TITLE
[Crash]: Crash when checking recipes

### ISSUE THREAD

**Issue by ChaosDogG** [mezz/JustEnoughItems#3775] opened 2024-09-20 03:54 UTC
### Steps to Reproduce the Crash

1. Click on any item to check its crafting method
2. Watch as the game collapses and screams at you

### Extra Notes (Optional)

MC Version: 1.19.2
JEI Version: 11.7.0.1028

### Crash Report

https://gist.github.com/ChaosDogG/6f063db70d143d3d2993deb1439e95e2

**Comment by mezz** [comment] 2024-09-20 04:39
Thanks for the report!
```
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in mezz/jei/library/gui/recipes/RecipeLayout::drawRecipe(Lcom/mojang/blaze3d/vertex/PoseStack;II)V has incompatible changes at opcode 69 in callback almostunified-common.mixins.json:compat.JeiRecipeLayoutMixin->@Inject::unified$catchLayoutInfo(Lcom/mojang/blaze3d/vertex/PoseStack;IILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lmezz/jei/api/gui/drawable/IDrawable;IIII)V.
```

This seems to be caused by a failing mixin from the `almostunified` mod. 
Please report to them here and link back to this issue: https://github.com/AlmostReliable/almostunified/issues

**Comment by ChaosDogG** [comment] 2024-09-20 04:47
will do, chief! thanks for the quick reply!

**Comment by mezz** [comment] 2024-09-20 05:22
Looks like the linking between issues didn't work for some reason, so here is the new issue: https://github.com/AlmostReliable/almostunified/issues/93

**Comment by rlnt** [comment] 2024-10-08 08:59
I think you can close this now.

**Closed as completed** 2024-10-08 10:52 UTC
Labels: other mod
