### ISSUE TITLE
[ISSUE] Hiding items with NBT vs Meta

### ISSUE THREAD

**Issue by NightOps007** [mezz/JustEnoughItems#608] opened 2016-11-14 14:35 UTC
When hiding some items, ic2 fluid cells for example, if you hide one of them(individually; not wildcard), they are all hidden. This seems to be a problem with how the contents are recognized for this item. When the info is stored for items using metadata, they can be individually hidden. For items that store info using nbt, it hides them all. Or is it vice-versa? I get those two mixed up sometimes.

**Comment by mezz** [comment] 2016-11-14 23:48
Thanks for the report!
Confirmed, it seems to be working strangely.

**Comment by LabGoblin** [comment] 2016-11-22 23:42
could we also get a way to force UNhide an item? it would be useful for things like gendustrys genetic templates where there isn't an empty one in jei and I don't need all the different permutations

**Comment by mezz** [comment] 2016-11-23 00:16
@bushbaby1234 I think that's this open issue here: https://github.com/mezz/JustEnoughItems/issues/195

**Comment by LabGoblin** [comment] 2016-11-25 07:11
it is indeed. thanks

**Comment by mezz** [comment] 2018-05-26 21:43
I am not easily able to solve this issue in 1.12 because of the way subtypes are implemented.
In 1.13 I think this issue will be resolved. I am closing it now since it is pretty minor and I don't think I will have a good solution any time soon.

**Closed as completed by mezz** 2018-05-26 21:43 UTC
Labels: minor bug
