### ISSUE TITLE
[Crash]: Minecraft 1.20 does not launch with JEI

### ISSUE THREAD

**Issue by Louisv0720** [mezz/JustEnoughItems#3244] opened 2023-06-11 22:03 UTC
### Steps to Reproduce the Crash

1. Use Fabric loader 0.14.21-1.20
2. Use Fabric API 0.83
3. Use JEI 1.20 Fabric 14.0.0.7
4. Launch game, receive error code 1 alongside a crash

### Extra Notes (Optional)

Tried the different 1.20 JEI versions, error persists across all versions.
14.0.0.7 supposedly fixes this issue, but does not.
Error ceases when JEI is removed from mod folder.

### Crash Report

https://gist.github.com/PhoenixPHTM/4c2023db5d53854f88eb294005203917

**Comment by mezz** [comment] 2023-06-11 22:44
Thanks for the report!
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/3243
Luckily for you I just fixed it a few minutes ago, please try with JEI 14.0.0.9 :)

**Closed as completed by mezz** 2023-06-11 22:44 UTC
