### ISSUE TITLE
Crash in modded 1.10.2 (Possibly caused by tabbing out?)

### ISSUE THREAD

**Issue by Moonlightneo** [mezz/JustEnoughItems#496] opened 2016-10-03 23:55 UTC
I'm having a small problem with crashing on occasion, it seems to happen if/when i alt tab, but could also be related to trying to open to LAN, cant say for sure. Posting here cause google didn't help and judging by my relatively shoddy knowledge of a crash report, JEI is related.

**https://gist.github.com/Moonlightneo/225f2796ff870cff02fdcde813715d6b**

**Comment by liach** [comment] 2016-10-03 23:56
I think it is caused by JustEnoughTooltips not updating to the latest version of JEI.

**Comment by Moonlightneo** [comment] 2016-10-03 23:58
Thanks for the lightning fast response, i'll test to see if it's the culprit and be back shortly

**Comment by liach** [comment] 2016-10-03 23:58
It is already fixed in latest JustEnoughTooltips. Please check it out.
https://mods.curse.com/mc-mods/minecraft/238222-just-enough-items-jei

**Comment by mezz** [comment] 2016-10-04 00:00
Thanks for the report!
This is a duplicate of #483
Bug was reported to JET here: superckl/JustEnoughTooltips#3

**Closed as completed by mezz** 2016-10-04 00:00 UTC
Labels: duplicate
