### ISSUE TITLE
Crashing when connecting to server

### ISSUE THREAD

**Issue by Drakoflame** [mezz/JustEnoughItems#370] opened 2016-07-31 01:37 UTC
https://gist.github.com/Drakoflame/ddce0bf9c2f3dd119afebfdcc0555170

Each time, I'd orginally though it was a mod called "Survivalist" but upon removing it the issue persisted

**Comment by mezz** [comment] 2016-07-31 23:49
Thanks for the report!
I believe this is a duplicate of #352, please try with the latest version of JEI and see what the new crash log says.

**Comment by Drakoflame** [comment] 2016-08-05 06:13
Sorry for the delay, but here's the crash logs, one with the current "Stable" release, and one with the newest "Beta" Release (respectively)
https://gist.github.com/Drakoflame/502e3089ff133442709c3349c4e51f9c
(stable)
https://gist.github.com/Drakoflame/a4e30387ddf9cb5d4ac4885ba83afd9e
(Beta)

**Comment by mezz** [comment] 2016-08-07 01:45
Thanks!
This is an ActuallyAdditions issue.
Please see this issue here: https://github.com/Ellpeck/ActuallyAdditions/issues/150.
The other person that had this same problem seems to have resolved it by updating their mods.

**Closed as completed by mezz** 2016-08-07 01:45 UTC
Labels: other mod

**Comment by Drakoflame** [comment] 2016-08-07 07:00
I know you closed this, but I'm still having the issue... I deleted Actually Additions, and updated JEI to the latest version https://gist.github.com/Drakoflame/fd4756210964b339629dc5634a760ab8

**Comment by mezz** [comment] 2016-08-07 10:00
That's an almost identical crash, but it involves the expandable backpack mod instead of actually additions. Please update all your mods, this is not caused by JEI so updating it will not fix the issue. If that doesn't fix the issue, please report to expandable backpacks.
