### ISSUE TITLE
[Bug]: Trying to press the E key in the search bar closes the inventory.

### ISSUE THREAD

**Issue by PenumbraStar** [mezz/JustEnoughItems#2801] opened 2022-04-20 07:39 UTC
### Steps to Reproduce the Bug

Select the Search bar.
Press E.

### Expected Behavior

Pressing E should not close the inventory while searching.

### Actual Behavior

The inventory closes whenever the button is pressed, regardless of searching.

### Extra Notes (Optional)

I am playing with a custom modpack, I have not had the time to troubleshoot this on my own, and the log files are not giving me much information. I have also ran into a bug that results in the search bar being selected automatically whenever a key is pressed within an inventory.

### latest.log

https://gist.github.com/PenumbraStar/3eca1a7828151cfa59ee3ba63b97a972

**Comment by logwet** [comment] 2022-04-20 09:04
I'm running into the same problem

**Comment by logwet** [comment] 2022-04-20 10:35
It appears that this is caused by a conflict with the patch for [MC-147605](https://bugs.mojang.com/browse/MC-147605) in the [Debugify](https://www.curseforge.com/minecraft/mc-mods/debugify) mod and is not a problem on JEI's side. Ref: W-OVERFLOW/Debugify#74
I can confirm that going into the Debugify settings page inside Minecraft and disabling the patch for `MC-147605` resolves the problem for me.

**Comment by Danito360** [comment] 2022-04-25 17:29
> It appears that this is caused by a conflict with the patch for [MC-147605](https://bugs.mojang.com/browse/MC-147605) in the [Debugify](https://www.curseforge.com/minecraft/mc-mods/debugify) mod and is not a problem on JEI's side. Ref: [W-OVERFLOW/Debugify#74](https://github.com/W-OVERFLOW/Debugify/issues/74) I can confirm that going into the Debugify settings page inside Minecraft and disabling the patch for `MC-147605` resolves the problem for me.

You are right, this bug was fixed in newest versions

**Closed as completed** 2022-04-25 19:19 UTC
Labels: other mod
