### ISSUE TITLE
[Help/Question] Item cheating via cheat mod

### ISSUE THREAD

**Issue by ml0130** [mezz/JustEnoughItems#813] opened 2017-04-14 14:50 UTC
I think this is a problem on venillas side but i'm not sure. The video below is my question?
https://youtu.be/AJGbi2D_9zI

**Comment by way2muchnoise** [comment] 2017-04-14 16:06
Related to #807

**Comment by ml0130** [comment] 2017-04-14 16:39
@way2muchnoise i forgot to say this was in a signal player instance

**Comment by mezz** [comment] 2017-04-14 22:21
Thanks for the report!
You're right, this is a vanilla bug: https://bugs.mojang.com/browse/MC-87019
Please log in there and "vote" for the bug so it gets a higher priority.

I'll take a look at it to see if it's possible to fix in Forge or if we have to wait for vanilla to fix it.

(Duplicate of https://github.com/mezz/JustEnoughItems/issues/186)

**Closed as completed by mezz** 2017-04-14 22:21 UTC
Labels: duplicate
