### ISSUE TITLE
[Crash]: Just Enough Items Causing Crashes

### ISSUE THREAD

**Issue by TheMrMoki** [mezz/JustEnoughItems#3679] opened 2024-08-11 00:22 UTC
### Steps to Reproduce the Crash

When using several mods (linked in the Modpack) with all recent versions, JEI causes crashes and/or an error upon mod load.
JEI/incompatibility with JEI seems to be the reason as it only occurs when JEI is present.
I am mostly asking if there's something I'm missing in the crash report.
The linked modpack is an export for CurseForge's mod manager. 

### Mod Pack URL (Optional)

https://drive.google.com/file/d/11V7jhXtAibIMDPjaglok-n4ICpbycxqm/view?usp=sharing

### Extra Notes (Optional)

I am mostly asking if there's something I'm missing in the crash report. Sorry for the inconvenience!

### Crash Report

https://gist.github.com/TheMrMoki/0554c753a76dbbf3e4a8cf2f0a681665

**Comment by DogeGit1** [comment] 2024-08-11 02:44
Seeing as you have both JEI and Gtceu loaded, I believe this to be the same incompatibility of GregTech that has been previously mentioned in post #3664.

**Comment by TheMrMoki** [comment] 2024-08-11 13:49
> Seeing as you have both JEI and Gtceu loaded, I believe this to be the same incompatibility of GregTech that has been previously mentioned in post #3664.

Thank you!

**Comment by Faruk259** [comment] 2024-08-12 01:29
Stupid modders really annoy me, if you are doing a job, you have to do it properly, I tried all the valid versions of this wall plastering job, your mod is not working.

**Comment by DogeGit1** [comment] 2024-08-12 03:14
> Stupid modders really annoy me, if you are doing a job, you have to do it properly, I tried all the valid versions of this wall plastering job, your mod is not working in 1.21

These people don't owe you anything. They do it for the sake of other's enjoyment. If you insult people offering something for free. Do it yourself then. Also a shame you created an account just for slander. Kinda sad in a way

**Comment by TheMrMoki** [comment] 2024-08-12 15:55
> Stupid modders really annoy me, if you are doing a job, you have to do it properly, I tried all the valid versions of this wall plastering job, your mod is not working in 1.21

bro wtf you on. I came here to ask for insight from people who have sharper eyes from me not to have mfs rant about their frustrations. go to reddit or some shit where it makes sense

**Comment by mezz** [comment] 2024-08-13 06:50
If you would like a small window into what it takes to correctly resolve issues like this, check out my post in the other thread:
https://github.com/mezz/JustEnoughItems/issues/3664#issuecomment-2285451253

My code changes alone were over 1,000 lines and they couldn't break backward compatibility with any one of thousands of mods.
Excluded from this are the long discussions on Discord and failed design attempts that we tried out and discarded along the way.

If you're so intelligent, you do it next time @Faruk259 
Otherwise, my Patreon is here and I normally charge around $200 an hour freelance, so this bug clocks in at around $5,800 if you don't mind https://www.patreon.com/mezz

For everyone else, thanks for your patience!
Closing as duplicate of #3664

**Closed as not planned by mezz** 2024-08-13 06:50 UTC
