### ISSUE TITLE
Crash with legiblenei

### ISSUE THREAD

**Issue by h3oCharles** [mezz/JustEnoughItems#1312] opened 2018-07-31 12:05 UTC
https://gist.github.com/KarBoy2314PL/7e23a09c7a1730b097c8c2776938e714

plz help

**Comment by mezz** [comment] 2018-08-02 04:14
Thanks for the report!
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/1302
The issue has been reported to legiblenei here: https://minecraft.curseforge.com/projects/legiblenei/issues/11

**Closed as completed by mezz** 2018-08-02 04:14 UTC
Labels: duplicate
