### ISSUE TITLE
[SUGGESTION] Item search: Search for string NOT in item name

### ISSUE THREAD

**Issue by profiluefter** [mezz/JustEnoughItems#1034] opened 2017-10-27 14:49 UTC
Would be great if you can add this feature.

**Comment by mezz** [comment] 2017-10-28 04:00
To help me understand better, can you give an example search string that would use this?

**Comment by liach** [comment] 2017-10-28 04:56
Excluding ingredients with a certain string in their names?

**Comment by profiluefter** [comment] 2017-10-28 07:50
Exactly what I meant. (Not native speaker)

**Comment by KnightMiner** [comment] 2017-10-28 12:43
I think mezz was asking for a specific example where you would use this, so why you want it

**Comment by profiluefter** [comment] 2017-10-29 17:30
Example: stone -cobble

**Comment by profiluefter** [comment] 2017-10-29 17:31
Would be great in big modpacks

**Comment by mezz** [comment] 2017-11-02 05:22
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/820
I am working on implementing it now.

**Closed as completed by mezz** 2017-11-02 05:22 UTC
Labels: duplicate
