### ISSUE TITLE
1.13.2 config not working

### ISSUE THREAD

**Issue by drakosoldier298** [mezz/JustEnoughItems#1546] opened 2019-04-07 22:26 UTC
in the game the wrench to open config to allow editing of the mod like enabling cheat mode the button doesn't work even going into the mod list on the main menu I cannot open the config.

**Comment by mezz** [comment] 2019-04-07 22:28
Thanks for the report!
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/1526, please see the comments there.

**Closed as completed by mezz** 2019-04-07 22:28 UTC
Labels: duplicate
