### ISSUE TITLE
Ability to press T on items in your inventory to find them in the world not just t over items in Jei 

### ISSUE THREAD

**Issue by ProsperCraft** [mezz/JustEnoughItems#438] opened 2016-09-20 23:40 UTC
I love that you can find items in chests or containers by pressing T when they are in JEI, could you please make it so you can do the same with items in the inventory so we can know which chest to put them away in?

**Comment by TehNut** [comment] 2016-09-20 23:50
That is not JEI. I believe this is More Overlays.

**Comment by mezz** [comment] 2016-09-21 00:42
Duplicate of #432
This feature is already added by More Overlays.

**Closed as completed by mezz** 2016-09-21 00:42 UTC
Labels: duplicate

**Comment by ryankhart** [comment] 2018-04-15 05:50
For the record, this is not a duplicate of #432. This issue is about pressing T when hovering your mouse over an item in order to find it in the world around you. It causes a sparkle on the container that contains that item. #432 is about double-clicking the search bar to find items you are actually holding in your inventory.
