### ISSUE TITLE
Initial focused tab when viewing usages isn't the first tab in the list

### ISSUE THREAD

**Issue by TeamDman** [mezz/JustEnoughItems#1524] opened 2019-03-22 23:24 UTC
By default, it seems to focus on the vanilla crafting tab, which isn't always the first item in the list. 
https://i.imgur.com/nT2PSgT.png
Makes it seem as if recipes are missing (even though they aren't.)

Good solutions could be either ensuring that the vanilla crafting tab is also always first in the list in addition to being the default view, or making the first tab in the list the default view instead.

Running jei_1.12.2-4.15.0.269.jar
Related to: #473

**Comment by Saereth** [comment] 2019-03-22 23:31
to expand on this issue, this only happens in a server/multiplayer setting. the same pack and same player will default to page 1 in single player with expected behavior.

**Comment by mezz** [comment] 2019-03-24 19:37
Thanks for the report!
I must have broken the ordering some time recently, I'll look into it.

**Comment by mezz** [comment] 2019-03-24 20:04
I'm not able to reproduce this issue.
Is there a specific pack it's happening with?

The vanilla tabs are supposed to always come first.
The default view is based on the inventory you're looking at, when you're in a crafting table then the vanilla crafting tab should be the default view.

**Comment by TeamDman** [comment] 2019-03-24 22:36
Experiencing the issue on FTB Interactions 1.01
Pack hasn't launched to the public yet, I'll DM you the link on Discord


Streamable link to a video example
https://streamable.com/aa0zb

**Comment by mezz** [comment] 2019-03-25 00:49
![2019-03-24_17 48 41](https://user-images.githubusercontent.com/916092/54888753-24edcc80-4e5d-11e9-9b61-d0582be59001.png)

This has been fixed in the next version of JEI (building now).

**Closed as completed** 2019-03-25 00:49 UTC
Labels: minor bug
