### ISSUE TITLE
[Bug]: the percentages of probabilities with the create mod no longer appear

### ISSUE THREAD

**Issue by 0Trinster0** [mezz/JustEnoughItems#3706] opened 2024-08-24 15:28 UTC
### Steps to Reproduce the Bug

1. I open the recipe menu of the mod create 
2. when reviewing recipes such as the crushing wheel or the milestone, the percentages of the items that have a chance of being generated in these mechanisms are not shown. 

### Expected Behavior

see the percentages of probability of generation of the materials of the mod create mechanisms

### Actual Behavior

I can't see the percentages of the items with a chance of being awarded that the mechanism gives in certain recipes.

### Extra Notes (Optional)

I leave images for more clarity, I'm using jei-1.20.1-forge-15.12.2.51 version.
![2024-08-24_10 25 44](https://github.com/user-attachments/assets/ecee5283-d7f4-4b12-b7be-756bfc346953)
![2024-08-24_10 25 53](https://github.com/user-attachments/assets/64777cbb-f0ae-4d7a-b33d-9af9608c8d8c)
![2024-08-24_10 25 36](https://github.com/user-attachments/assets/15b4d513-fae6-4920-938f-06027bfe52ac)
![2024-08-24_10 25 39](https://github.com/user-attachments/assets/2f0238ca-220c-4d44-8fee-690762ee604b)

### latest.log

https://gist.github.com/0Trinster0/bc9d4cf381ffe4f683498dc1acb38c14#file-gistfile1-txt

**Comment by AGkizlis** [comment] 2024-08-26 01:57
Same with botany pots growth rate multipliers for different soils.

**Comment by mezz** [comment] 2024-08-28 12:52
Thanks for the report!
You are using an old version, please update to `jei-1.20.1-forge-15.14.0.64`
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/3683

**Closed as not planned by mezz** 2024-08-28 12:52 UTC
Labels: duplicate
