### ISSUE TITLE
[Bug]: The server must have jei installed

### ISSUE THREAD

**Issue by Raptorr505** [mezz/JustEnoughItems#3708] opened 2024-08-25 02:16 UTC
### Steps to Reproduce the Bug

Whenever I click on a recipe and try to click on the "+" sign to send the items to the crafting automatically, I get an error that says "The server must have jei installed". The only problem is that I'm playing singleplayer.

### Expected Behavior

Since I'm not playing on a server, I should be able to use the "+" sign to put the items on the crafting table automatically, without any issue.

### Actual Behavior

Whenever I click on a recipe and try to click on the "+" sign to send the items to the crafting automatically, I get an error that says "The server must have jei installed". The only problem is that I'm playing singleplayer. This started to happen out of seemingly nowhere. 
![Captura de ecrã 2024-08-25 025547](https://github.com/user-attachments/assets/ab55fa4c-355c-49c8-9b46-ec194a8e560e)

### Extra Notes (Optional)

I'm playing on a private modpack that I made (which means that I gathered a bunch of mods and placed them in the mods folder). if necessary, I can share the mod list. I've also made a few datapacks, but the error remains even without the datapacks. I tried to use my modpack without any jei addons. The error remains.

### latest.log

https://gist.github.com/Raptorr505/0a44791ed7b9442dbc57fa4deaa95902

**Comment by mezz** [comment] 2024-08-28 12:58
Thanks for the report!
This is an issue with Pixelmon, duplicate of: https://github.com/mezz/JustEnoughItems/issues/3685

**Closed as not planned by mezz** 2024-08-28 12:58 UTC
Labels: duplicate
