### ISSUE TITLE
1.12.2] Jei is not showing all recipies

### ISSUE THREAD

**Issue by olafWojtczyk** [mezz/JustEnoughItems#1577] opened 2019-05-19 17:13 UTC
Jei is not showing all recipies. It's showing IC2 And some thermal expansion recipies.

**Comment by P3rf3ctXZer0** [comment] 2019-05-28 22:43
Actually I am having the exact same issue. I am u-jei_1.12.2-4.15.0.279-b.jar 

Here is my changelog

https://github.com/P3rf3ctXZer0/Zer0Necrosis-Project-Workbench/releases/tag/mc-1.12.2-IfYouWantItWorkForIt-0009

Fun fact all furnace recipes are visible just seems to not like workbench. I will be reverting releases to see if that helps.

**Comment by P3rf3ctXZer0** [comment] 2019-05-28 22:49
Um I reverted to release and my world um - what? 
![2019-05-28 17_47_59-saves](https://user-images.githubusercontent.com/10351221/58517428-f8ae3f00-8170-11e9-8327-82850fd475d1.jpg)

**Comment by P3rf3ctXZer0** [comment] 2019-05-28 22:55
@Labiq can I see your mod list forge version and jei version?

**Comment by P3rf3ctXZer0** [comment] 2019-05-29 00:29
This is a duplicate of this https://github.com/mezz/JustEnoughItems/issues/1561 @Shadows-Of-Fire your mod seems to break JEI and Crafttweaker.

**Comment by P3rf3ctXZer0** [comment] 2019-05-29 01:49
https://github.com/CreativeMD/IGCM/issues/55

Solved @Labiq Remove FastWorkbench and Ingame Config Manager.

**Comment by mezz** [comment] 2019-06-01 03:04
Thanks for the info P3rf3ctXZer0

**Closed as completed by mezz** 2019-06-01 03:04 UTC
Labels: other mod
