### ISSUE TITLE
Crashing Entire Game

### ISSUE THREAD

**Issue by speedy815** [mezz/JustEnoughItems#655] opened 2016-12-08 04:04 UTC
I working with about 31 mods in the pack but when I get to a certain page wit JEI my entire game crashes.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.60-beta.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 12/7/16 9:52 PM
Description: Rendering screen

java.lang.IllegalAccessError: tried to access field net.minecraft.item.ItemStack.field_77990_d from class cofh.api.energy.ItemEnergyContainer
	at cofh.api.energy.ItemEnergyContainer.getEnergyStored(ItemEnergyContainer.java:98)
	at de.ellpeck.actuallyadditions.mod.items.base.ItemEnergy.getDurabilityForDisplay(ItemEnergy.java:99)
	at net.minecraft.client.renderer.RenderItem.func_180453_a(RenderItem.java:420)
	at mezz.jei.gui.ingredients.GuiIngredientFast.renderOverlay(GuiIngredientFast.java:205)
	at mezz.jei.gui.ingredients.GuiIngredientFast.renderOverlay(GuiIngredientFast.java:195)
	at mezz.jei.gui.ingredients.GuiIngredientFastList.render(GuiIngredientFastList.java:187)
	at mezz.jei.gui.ItemListOverlayInternal.drawScreen(ItemListOverlayInternal.java:305)
	at mezz.jei.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:88)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_277_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:590)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:73)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:47)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at cofh.api.energy.ItemEnergyContainer.getEnergyStored(ItemEnergyContainer.java:98)
	at de.ellpeck.actuallyadditions.mod.items.base.ItemEnergy.getDurabilityForDisplay(ItemEnergy.java:99)
	at net.minecraft.client.renderer.RenderItem.func_180453_a(RenderItem.java:420)
	at mezz.jei.gui.ingredients.GuiIngredientFast.renderOverlay(GuiIngredientFast.java:205)
	at mezz.jei.gui.ingredients.GuiIngredientFast.renderOverlay(GuiIngredientFast.java:195)
	at mezz.jei.gui.ingredients.GuiIngredientFastList.render(GuiIngredientFastList.java:187)
	at mezz.jei.gui.ItemListOverlayInternal.drawScreen(ItemListOverlayInternal.java:305)
	at mezz.jei.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:88)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_277_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:590)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:73)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:47)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiInventory
	Mouse location: Scaled: (618, 12). Absolute: (1854, 1019)
	Screen size: Scaled: (640, 353). Absolute: (1920, 1057). Scale factor of 3

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['SPEEDY815'/153587, l='MpServer', x=1034.06, y=76.00, z=-270.70]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-256,64,136), Chunk: (at 0,4,8 in -16,8; contains blocks -256,0,128 to -241,255,143), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 4908398 game time, 5053861 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 71 total; [EntityZombie['Zombie'/153730, l='MpServer', x=1060.50, y=19.00, z=-282.50], EntityPlayerSP['SPEEDY815'/153587, l='MpServer', x=1034.06, y=76.00, z=-270.70], EntityZombie['Zombie'/153728, l='MpServer', x=1061.51, y=20.00, z=-275.76], EntityZombie['Zombie'/153729, l='MpServer', x=1064.39, y=17.02, z=-276.30], EntityCreeper['Creeper'/153734, l='MpServer', x=1111.50, y=27.00, z=-316.50], EntityChicken['Chicken'/153610, l='MpServer', x=961.15, y=67.00, z=-333.26], EntityChicken['Chicken'/153611, l='MpServer', x=957.86, y=66.00, z=-323.46], EntityCreeper['Creeper'/153608, l='MpServer', x=955.21, y=30.00, z=-333.50], EntityCreeper['Creeper'/153615, l='MpServer', x=971.47, y=14.00, z=-338.16], EntityCow['Cow'/153619, l='MpServer', x=958.85, y=67.00, z=-314.53], EntityChicken['Chicken'/153620, l='MpServer', x=973.02, y=67.00, z=-330.49], EntityItem['item.item.egg'/153621, l='MpServer', x=973.70, y=67.00, z=-330.13], EntityZombie['Zombie'/153627, l='MpServer', x=960.63, y=15.00, z=-198.81], EntityCreeper['Creeper'/153630, l='MpServer', x=964.50, y=37.00, z=-318.50], EntityCow['Cow'/153631, l='MpServer', x=974.82, y=71.00, z=-307.57], EntityBoat['Boat'/153629, l='MpServer', x=960.18, y=62.52, z=-299.16], EntitySkeleton['Skeleton'/153634, l='MpServer', x=974.50, y=19.00, z=-278.50], EntityEnderman['Enderman'/153635, l='MpServer', x=969.50, y=41.00, z=-286.50], EntityChicken['Chicken'/153632, l='MpServer', x=972.78, y=70.00, z=-309.56], EntityItem['item.item.egg'/153633, l='MpServer', x=971.84, y=70.00, z=-309.88], EntityCreeper['Creeper'/153639, l='MpServer', x=971.50, y=20.00, z=-257.50], EntitySkeleton['Skeleton'/153636, l='MpServer', x=970.51, y=40.00, z=-280.67], EntitySkeleton['Skeleton'/153637, l='MpServer', x=958.50, y=15.00, z=-246.50], EntityCreeper['Creeper'/153642, l='MpServer', x=1005.54, y=20.00, z=-202.14], EntityBat['Bat'/153770, l='MpServer', x=978.07, y=20.99, z=-335.45], EntitySkeleton['Skeleton'/153643, l='MpServer', x=1002.51, y=24.00, z=-203.79], EntityBat['Bat'/153640, l='MpServer', x=972.47, y=21.82, z=-256.16], EntityBat['Bat'/153768, l='MpServer', x=976.25, y=21.00, z=-340.88], EntityCow['Cow'/153650, l='MpServer', x=991.35, y=68.00, z=-345.18], EntitySkeleton['Skeleton'/153654, l='MpServer', x=1002.54, y=19.00, z=-256.74], EntitySkeleton['Skeleton'/153655, l='MpServer', x=976.50, y=35.00, z=-308.50], EntityZombie['Zombie'/153653, l='MpServer', x=983.49, y=27.00, z=-253.19], EntityCreeper['Creeper'/153659, l='MpServer', x=988.50, y=14.00, z=-291.50], EntitySpider['Spider'/153656, l='MpServer', x=977.50, y=35.00, z=-311.50], EntitySpider['Spider'/153657, l='MpServer', x=977.50, y=35.00, z=-309.50], EntityBat['Bat'/153662, l='MpServer', x=999.01, y=13.07, z=-308.30], EntityCreeper['Creeper'/153663, l='MpServer', x=992.83, y=15.00, z=-285.46], EntityCreeper['Creeper'/153660, l='MpServer', x=991.50, y=14.00, z=-290.50], EntityBat['Bat'/153661, l='MpServer', x=992.55, y=14.32, z=-305.44], EntityZombie['Zombie'/153664, l='MpServer', x=999.50, y=16.00, z=-281.50], EntitySquid['Squid'/153669, l='MpServer', x=1018.44, y=43.34, z=-211.87], EntityCreeper['Creeper'/153675, l='MpServer', x=1043.50, y=45.00, z=-297.50], EntityCow['Cow'/153679, l='MpServer', x=1029.49, y=84.00, z=-335.80], EntityBoat['Boat'/153676, l='MpServer', x=1048.94, y=61.00, z=-283.34], EntityBoat['Boat'/153677, l='MpServer', x=1047.15, y=62.52, z=-282.47], EntityZombie['Zombie'/153682, l='MpServer', x=1024.50, y=18.00, z=-306.50], EntityChicken['Chicken'/153683, l='MpServer', x=1053.47, y=62.61, z=-336.94], EntityCow['Cow'/153680, l='MpServer', x=1038.50, y=74.00, z=-341.50], EntityCow['Cow'/153681, l='MpServer', x=1037.81, y=86.00, z=-338.55], EntityCow['Cow'/153684, l='MpServer', x=1043.72, y=64.00, z=-344.86], EntityChicken['Chicken'/153685, l='MpServer', x=1044.80, y=64.00, z=-342.43], EntityBat['Bat'/153698, l='MpServer', x=1103.87, y=16.24, z=-208.04], EntitySkeleton['Skeleton'/153697, l='MpServer', x=1084.23, y=33.00, z=-192.76], EntityBat['Bat'/153703, l='MpServer', x=1103.08, y=15.46, z=-208.62], EntitySpider['Spider'/153710, l='MpServer', x=1099.30, y=14.10, z=-295.30], EntityZombie['Zombie'/153711, l='MpServer', x=1103.42, y=13.00, z=-293.25], EntitySquid['Squid'/153709, l='MpServer', x=1071.40, y=58.86, z=-280.85], EntityCreeper['Creeper'/153714, l='MpServer', x=1046.50, y=18.00, z=-241.50], EntityCreeper['Creeper'/153715, l='MpServer', x=1101.50, y=21.00, z=-276.50], EntityZombie['Zombie'/153712, l='MpServer', x=1103.32, y=13.00, z=-292.50], EntityZombie['Zombie'/153713, l='MpServer', x=1090.79, y=20.00, z=-284.47], EntitySpider['Spider'/153718, l='MpServer', x=1040.00, y=20.00, z=-204.02], EntitySkeleton['Skeleton'/153716, l='MpServer', x=1089.49, y=23.00, z=-273.71], EntitySquid['Squid'/153717, l='MpServer', x=1052.37, y=58.13, z=-245.69], EntityCreeper['Creeper'/153722, l='MpServer', x=1094.50, y=18.00, z=-323.50], EntityBat['Bat'/153723, l='MpServer', x=1058.41, y=23.88, z=-281.66], EntitySkeleton['Skeleton'/153720, l='MpServer', x=1057.56, y=49.00, z=-313.32], EntityCreeper['Creeper'/153726, l='MpServer', x=1112.21, y=13.00, z=-323.49], EntityCreeper['Creeper'/153727, l='MpServer', x=1106.83, y=26.00, z=-322.40], EntityCreeper['Creeper'/153724, l='MpServer', x=1096.68, y=27.00, z=-311.59], EntityCreeper['Creeper'/153725, l='MpServer', x=1095.50, y=27.00, z=-314.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 971974912 bytes (926 MB) / 2134114304 bytes (2035 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 31 mods loaded, 31 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJA	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJA	actuallyadditions{1.10.2-r87} [Actually Additions] (ActuallyAdditions-1.10.2-r87.jar) 
	UCHIJA	JEI{3.13.6.387} [Just Enough Items] (jei_1.10.2-3.13.6.387.jar) 
	UCHIJA	mcmultipart{1.3.0} [MCMultiPart] (MCMultiPart-1.3.0-universal.jar) 
	UCHIJA	chiselsandbits{12.7} [Chisels & Bits] (chiselsandbits-12.7.jar) 
	UCHIJA	endercore{1.10.2-0.4.1.60-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.60-beta.jar) 
	UCHIJA	valkyrielib{1.10.2-0.10.5d} [Valkyrie Lib] (valkyrielib-1.10.2-0.10.5e.jar) 
	UCHIJA	environmentaltech{1.10.2-0.10.5h} [Environmental Tech] (environmentaltech-1.10.2-0.10.5h.jar) 
	UCHIJA	FastLeaveDecay{1.2.3} [Fast Leave Decay] (FastLeaveDecay-MC1.10.2-1.2.3.jar) 
	UCHIJA	gravestone{1.5.9} [Gravestone] (GraveStone Mod 1.5.9.jar) 
	UCHIJA	mantle{1.10.2-1.1.2.197} [Mantle] (Mantle-1.10.2-1.1.2.jar) 
	UCHIJA	tconstruct{1.10.2-2.5.6b.jenkins424} [Tinkers' Construct] (TConstruct-1.10.2-2.5.6b.jar) 
	UCHIJA	immersiveengineering{0.10-52} [Immersive Engineering] (ImmersiveEngineering-0.10-52.jar) 
	UCHIJA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJA	journeymap{1.10.2-5.3.1} [JourneyMap] (journeymap-1.10.2-5.3.1.jar) 
	UCHIJA	ModNameTooltip{1.6.0} [Mod Name Tooltip] (modnametooltip_1.10.2-1.6.0.jar) 
	UCHIJA	Morpheus{1.10.2-3.1.12} [Morpheus] (Morpheus-1.10.2-3.1.12.jar) 
	UCHIJA	notenoughwands{1.4.0} [Not Enough Wands] (notenoughwands-1.10-1.4.0.jar) 
	UCHIJA	refinedstorage{1.2.8} [Refined Storage] (refinedstorage-1.2.8.jar) 
	UCHIJA	rftools{5.62} [RFTools] (rftools-1.10-5.62.jar) 
	UCHIJA	rftoolscontrol{1.5.2} [RFTools Control] (rftoolsctrl-1.10-1.5.2.jar) 
	UCHIJA	rftoolsdim{4.45} [RFTools Dimensions] (rftoolsdim-1.10-4.45.jar) 
	UCHIJA	shadowmc{3.5.0} [ShadowMC] (ShadowMC-1.10.2-3.6.0.jar) 
	UCHIJA	SleepingBag{1.4.0} [Sleeping Bag] (SleepingBag-1.10.2-1.4.0.jar) 
	UCHIJA	soundfilters{0.9_for_1.9} [Sound Filters] (SoundFilters-0.9_for_1.9.4.jar) 
	UCHIJA	theoneprobe{1.3.3} [The One Probe] (theoneprobe-1.10-1.3.3.jar) 
	UCHIJA	TinkersAddons{1.0.3} [Tinkers' Addons] (Tinkers' Addons-1.10.x-1.0.3.jar) 
	UCHIJA	tinkertoolleveling{1.10.2-1.0.1.DEV.f5def58} [Tinkers Tool Leveling] (TinkerToolLeveling-1.10.2-1.0.1.jar) 
	Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.10.2-0.4.1.60-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.14008 Compatibility Profile Context 21.19.137.1' Renderer: 'AMD Radeon (TM) R7 360 Series'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	Launched Version: 1.10.2-forge1.10.2-12.18.3.2185
	LWJGL: 2.9.4
	OpenGL: AMD Radeon (TM) R7 360 Series GL version 4.5.14008 Compatibility Profile Context 21.19.137.1, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Fanver_Modded_Universal.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x AMD FX(tm)-9590 Eight-Core Processor

**Comment by mezz** [comment] 2016-12-08 04:45
Thanks for the report!
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/448
I originally reported this to Actually Additions here: Ellpeck/ActuallyAdditions#245
This is caused by a 3rd mod that has a bad version of the RF API.
He recommends removing mods besides ActuallyAdditions until the crash goes away, so that we can find which mod is causing the problem.

**Comment by speedy815** [comment] 2016-12-08 06:12
@mezz Okay so I went through and removed ender IO and that fixed the problem


![screenshot 2](https://cloud.githubusercontent.com/assets/18146618/20999743/6bc80e28-bcdc-11e6-8885-632d42f83b53.png)

**Comment by mezz** [comment] 2016-12-08 06:38
Cool, glad you found the cause.
That EnderIO is for 1.7.10, so that explains the problem :)

**Closed as completed by mezz** 2016-12-08 06:38 UTC
Labels: duplicate
