### ISSUE TITLE
jei does not have a version but only @version@

### ISSUE THREAD

**Issue by CyberFIowey** [mezz/JustEnoughItems#2066] opened 2020-08-23 15:07 UTC
[18:05:23] [Client thread/WARN] [FML]: Mod mdecore-core has been disabled through configuration
[18:05:23] [Client thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod appleskin (AppleSkin) requires [jei@[4.6.0,)]
[18:05:23] [Client thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod blockdrops (Block Drops) requires [jei@[4.8.0,)]
[18:05:23] [Client thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod botania (Botania) requires [jei@[1.12.2-4.13.1.220,)]
[18:05:23] [Client thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod charm (Charm) requires [jei@[4.14.3,)]
[18:05:23] [Client thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod chisel (Chisel) requires [jei@[4.12.0,5)]
[18:05:23] [Client thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod crafttweakerjei (CraftTweaker JEI Support) requires [jei@[4.12.0,)]
[18:05:23] [Client thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod enderio (Ender IO) requires [jei@[4.14.1.234,)]
[18:05:23] [Client thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod enderioconduitsappliedenergistics (Ender IO Applied Energistics Conduits) requires [jei@[4.14.1.234,)]
[18:05:23] [Client thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod enderioconduitsopencomputers (Ender IO Open Computers Conduits) requires [jei@[4.14.1.234,)]
[18:05:23] [Client thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod enderioconduitsrefinedstorage (Ender IO Refined Storage Conduits) requires [jei@[4.14.1.234,)]
[18:05:23] [Client thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod enderiomachines (Ender IO Machines) requires [jei@[4.14.1.234,)]
[18:05:23] [Client thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod forestry (Forestry) requires [jei@[4.12.0.0,)]
[18:05:23] [Client thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod ftblib (FTB Library) requires [jei@[4.6.0,)]
[18:05:23] [Client thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod immersivetech (Immersive Tech) requires [jei@[4.7,)]
[18:05:23] [Client thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod jehc (Just Enough HarvestCraft) requires [jei@[4.15,)]
[18:05:23] [Client thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod jecalculation (Just Enough Calculation) requires [jei@[4.15.0.268,)]
[18:05:23] [Client thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod jee (Just Enough Energistics) requires [jei@[4.14.3.242,)]
[18:05:23] [Client thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod jeresources (Just Enough Resources) requires [jei@[4.7.0,)]
[18:05:23] [Client thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod laggoggles (LagGoggles) requires [tickcentral@[2.4,)]
[18:05:23] [Client thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod moreoverlays (MoreOverlays) requires [jei@[4.15.0.268,)]
[18:05:23] [Client thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod quark (Quark) requires [jei@[4.6.0,)]
[18:05:23] [Client thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod randomthings (Random Things) requires [jei@[4.7.11.100,)]
[18:05:23] [Client thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod tconstruct (Tinkers' Construct) requires [jei@[4.8,)]
[18:05:23] [Client thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod techreborn (Tech Reborn) requires [jei@[4.12,)]
[18:05:23] [Client thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod thaumicjei (ThaumicJEI) requires [jei@[1.12.2-4.15.0.275,)]
[18:05:23] [Client thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod immersiveengineering (Immersive Engineering) requires [jei@[4.8,)]
[18:05:23] [Client thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod thebetweenlands (The Betweenlands) requires [jei@[4.12.0,)]
[18:05:23] [Client thread/ERROR] [FML]: An exception was thrown, the game will display an error screen and halt.
net.minecraftforge.fml.common.MultipleModsErrored: 
Missing Mods:
	unknown : need [4.6.0,): have @VERSION@

Missing Mods:
	unknown : need [4.8.0,): have @VERSION@

Missing Mods:
	unknown : need [1.12.2-4.13.1.220,): have @VERSION@

Missing Mods:
	unknown : need [4.14.3,): have @VERSION@

Missing Mods:
	unknown : need [4.12.0,5): have @VERSION@

Missing Mods:
	unknown : need [4.12.0,): have @VERSION@

Missing Mods:
	unknown : need [4.14.1.234,): have @VERSION@

Missing Mods:
	unknown : need [4.14.1.234,): have @VERSION@

Missing Mods:
	unknown : need [4.14.1.234,): have @VERSION@

Missing Mods:
	unknown : need [4.14.1.234,): have @VERSION@

Missing Mods:
	unknown : need [4.14.1.234,): have @VERSION@

Missing Mods:
	unknown : need [4.12.0.0,): have @VERSION@

Missing Mods:
	unknown : need [4.6.0,): have @VERSION@

Missing Mods:
	unknown : need [4.7,): have @VERSION@

Missing Mods:
	unknown : need [4.15,): have @VERSION@

Missing Mods:
	unknown : need [4.15.0.268,): have @VERSION@

Missing Mods:
	unknown : need [4.14.3.242,): have @VERSION@

Missing Mods:
	unknown : need [4.7.0,): have @VERSION@

Missing Mods:
	unknown : need [2.4,): have missing

Missing Mods:
	unknown : need [4.15.0.268,): have @VERSION@

Missing Mods:
	unknown : need [4.6.0,): have @VERSION@

Missing Mods:
	unknown : need [4.7.11.100,): have @VERSION@

Missing Mods:
	unknown : need [4.8,): have @VERSION@

Missing Mods:
	unknown : need [4.12,): have @VERSION@

Missing Mods:
	unknown : need [1.12.2-4.15.0.275,): have @VERSION@

Missing Mods:
	unknown : need [4.8,): have @VERSION@

Missing Mods:
	unknown : need [4.12.0,): have @VERSION@

**Comment by ProxyPlayerHD** [comment] 2020-08-23 15:23
tip, use [Pastebin](https://pastebin.com/) instead of just throwing the whole thing into a post.
makes it so you don't have to scroll through the whole thing to look at the replies, and also looks much cleaner. :p

Also having the same issue in a custom pack: [LOG](https://pastebin.com/qMuTYdtb)

**Comment by otakup0pe** [comment] 2020-08-23 17:52
Getting the same in a custom pack as well. On 1.12.

**Comment by TheXTrunner** [comment] 2020-08-23 18:02
can confirm this, also in 1.12

**Comment by Valafi** [comment] 2020-08-23 20:48
Duplicate of #2060

**Comment by mezz** [comment] 2020-08-24 01:02
Thanks for the report!
This should be fixed in the next release.

**Closed as completed by mezz** 2020-08-24 01:02 UTC
