### ISSUE TITLE
Unable to select JEI Items

### ISSUE THREAD

**Issue by VampireSultana** [mezz/JustEnoughItems#1607] opened 2019-06-25 02:35 UTC
I don't know whether this was intentional or not, but I can't select items and put them into my inventory on survival mode. I can only do this on Creative mode. Is this a bug?

**Comment by mezz** [comment] 2019-06-30 19:52
Thanks for the report!
I think this is a duplicate of https://github.com/mezz/JustEnoughItems/issues/1603

**Closed as completed by mezz** 2019-06-30 19:52 UTC
Labels: duplicate
