### ISSUE TITLE
Add support for the remove Brewing Stand recipe by Crafttweaker

### ISSUE THREAD

**Issue by Fireztonez** [mezz/JustEnoughItems#1518] opened 2019-03-19 19:58 UTC
With CraftTweaker you can change add and remove Brewing Recipes, JEI show the Brewing recipes you add, but still show all removed recipes... There have a warning on the CraftTweaker Wiki (https://crafttweaker.readthedocs.io/en/latest/#Vanilla/Recipes/Recipes_Brewing_Stand/) about that, and I have try my self with the laster Released Version of JEI, and yes still does't work...

So, I want to know if you can look to add a support for the Crafttweaker Removing Brewing Recipes... This problem is there for long time, for what I know, but I can't find anything about that on the Tracker...

Version: 
Minecraft: 1.12.2
Forge: 14.23.5.2815
JEI: 4.15.0.268
CraftTweaker: 4.1.16
CraftTweaker JEI Support: 2.0.2

Thank's
Fireztonez

**Comment by mezz** [comment] 2019-03-25 01:38
Thanks for the report!
@jaredlll08 is this a JEI issue? I haven't heard of it before.

**Comment by jaredlll08** [comment] 2019-03-25 08:13
I believe the issue is that you either use the Forge registry for brewing recipes, or you don't use it, I'm not sure which one.

**Comment by mezz** [comment] 2019-03-26 04:33
That... that doesn't seem to narrow down things at all haha.
I'll take a look at the CraftTweaker JEI integration for brewing recipes and see if I can hack something together so I can understand what's going on with both sides.

**Comment by mezz** [comment] 2019-03-26 05:38
Hmm looks like CraftTweaker "removes" vanilla brewing recipes by creating a special brewing recipe (`VanillaBrewingPlus`) that matches all the removed inputs, and outputs nothing.
I think if it removed the recipes from the brewing registry instead, it might work with JEI.

**Comment by mezz** [comment] 2019-03-29 05:44
I looked more into this and I see why CraftTweaker works they way it does.
Forge creates the brewing "recipes", with one big recipe supporting all of vanilla.
CraftTweaker replaces that with its own, in order to remove some.
JEI doesn't look at either of these, it uses its own system to find brewing recipes.

I will look into if this can be fixed in JEI or CraftTweaker when I get some more time.

**Comment by Fireztonez** [comment] 2019-04-03 23:23
I just saw all messages! Thank's for working on that issue, I'm curious to know why the message is write into the Crafttweaker Wiki, but no-body take time to report here, but, if it can be fixed, that would be really nice!!

**Comment by mezz** [comment] 2019-04-07 01:22
This has been fixed on JEI's side in the latest version.

**Closed as completed** 2019-04-07 01:22 UTC
Labels: enhancement

**Comment by Fireztonez** [comment] 2019-04-10 00:24
Thank'you very much mezz for your work!

You make a really nice job on JEI, and I saw how much you work hard to fix all little issue! JEI is an awesome mod, and an awesome mod need an awesome dev, so continue like you does!

Fireztonez

**Comment by mezz** [comment] 2019-04-10 04:08
Thanks for reporting! Glad to make it work like it should :)
