### ISSUE TITLE
[Bug] Click to delete not working with Silents tools

### ISSUE THREAD

**Issue by MysticAura** [mezz/JustEnoughItems#624] opened 2016-11-17 15:07 UTC
MC: 1.10.2
Forge: 2121
Mod Version: jei_1.10.2-3.13.3.376
Related mods: CraftTweaker-1.10.2-3.0.15, SilentsGems-1.10.2-2.1.4-83

**Issue:** With cheat mode on Silent's tools refuse to 'click to delete'. They just drop on the ground instead. Other items are deleting as intended.

**Possibly related issue:** I've reported this to CraftTweaker as well, but seeing as Silent's isn't playing nice with JEI in general I thought I should include some info here as well. When I delete the recipes for Silent's tier 1 tools it appears as if they've been properly removed. However the removed recipes can still be crafted. All other recipe alterations are working as intended. Silent's is just being a royal pain.
[Related CraftTweaker Issue](https://github.com/jaredlll08/CraftTweaker/issues/90)

**Added thought:** Maybe I should report it to Silent's as well.

**Comment by mezz** [comment] 2016-11-18 01:10
Thanks for the report!
JEI has a "sanity check" that makes sure the item you're holding on the server matches the one you want to delete on the client.
Maybe the NBT or something does not match between client and server.
I can probably loosen this sanity check because you're in cheat mode anyway, you can just cheat the item back in if something goes  wrong.

**Comment by MysticAura** [comment] 2016-11-18 02:10
In this instance I was singleplayer. So I'm pretty sure they matched. However, if you take a look at Silents tools they're rather different than your typical mod tools. Such as multiple types of pickaxes with the same id. but different nbt data. This alternate way of doing things I believe is what's causing the difficulty in identifying the match.

**Comment by mezz** [comment] 2016-11-19 08:01
I'm pretty sure Silent's tools are doing something they're not supposed to.
Anyway, this should be fixed in JEI 3.13.3.380. Let me know if it still doesn't work for you.

**Comment by P3rf3ctXZer0** [comment] 2016-11-19 09:49
Silents mods in general are not professionally coded. I love Silents Gems mod but its super poorly optimized. Adding just that mod cut my frames from a consistant 60fps to a consistant 25 it was pretty bad :(

**Comment by SilentChaos512** [comment] 2016-11-19 19:54
Thanks, mezz. I think the problem is I'm storing a bit of NBT client-side only, and may not be removing it correctly.

@P3rf3ctXZer0 I'd like to know more about that, please [give me the details here](https://github.com/SilentChaos512/SilentGems/issues/81). I know that tool rendering has a performance hit since Minecraft 1.9, but last I checked Tinkers Construct was even worse.

**Comment by P3rf3ctXZer0** [comment] 2016-11-19 20:16
Oh I agree tcon is not much better. I will work on getting you a sample when I have money to pay for a test server. Players aren't happy if a server keeps changing XD

**Closed as completed** 2017-03-13 02:44 UTC
Labels: minor bug
