### ISSUE TITLE
While trying to get Recipie for item, game crashes [1.12.2]

### ISSUE THREAD

**Issue by ConnorTron110** [mezz/JustEnoughItems#1460] opened 2019-01-12 17:37 UTC
dunno whats going on plz help
[crash-2019-01-12_17.15.57-client.txt](https://github.com/mezz/JustEnoughItems/files/2752326/crash-2019-01-12_17.15.57-client.txt)

**Comment by mezz** [comment] 2019-01-12 19:33
Thanks for the report!
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/1189

**Closed as completed by mezz** 2019-01-12 19:33 UTC
Labels: duplicate
