### ISSUE TITLE
[Crash]: Useful Backpacks, Simple Storage Network

### ISSUE THREAD

**Issue by HalcyonSeas73** [mezz/JustEnoughItems#2754] opened 2022-03-13 23:44 UTC
### Steps to Reproduce the Crash

-Add a Large Backpack to a creative inventory.
-Open backpack with right click.
-Game crashes.

Alternatively,
-Place a Storage Network Root and a Storage Request Table (next to it) in the world
-Right click Network Crafting Table
-Game crashes.

### Extra Notes (Optional)

Minecraft version 1.18.2
Forge version 40.0.12
Useful Backpacks version 1.12.1.93
(UTeamCore version 4.0.0.204)
Simple Storage Network version 1.6.0

Issue was also posted to the Useful Backpacks github, but they've directed me here, saying that it's a JEI issue. The author of SSN has also been made aware of it. 
Crash log is only for the Useful Backpacks crash.

### Crash Report

https://paste.ee/p/CHnIh

**Comment by HalcyonSeas73** [comment] 2022-03-14 16:55
I just realized that it may be an issue with the mods in question not having been built with compatibility for newer JEI, rather than an issue with JEI itself.

**Comment by mezz** [comment] 2022-03-16 19:44
Thanks for the report!
This is actually a duplicate of https://github.com/mezz/JustEnoughItems/issues/2752
This should be fixed in 1.18.2-9.5.0.134

**Comment by HalcyonSeas73** [comment] 2022-03-16 19:51
Just tested with Useful Backpacks, it still produces the same crash; it seems to be a different issue. This problem still persists with 9.5.0.134.
Log: https://paste.ee/p/mKCwj

**Comment by mezz** [comment] 2022-03-16 19:55
Thanks for checking! You're right, this is not the same.
I will submit a new fix for this shortly.

**Comment by mezz** [comment] 2022-03-16 19:57
Please try out 9.5.0.135 and let me know if you still run into any issues.

**Comment by HalcyonSeas73** [comment] 2022-03-16 20:01
> Please try out 9.5.0.135 and let me know if you still run into any issues.

Will do. 

Edit: Seems to work! Thank you!

**Comment by mezz** [comment] 2022-03-16 20:20
Great, thanks for confirming!

**Closed as completed by mezz** 2022-03-16 20:20 UTC
Labels: bug
