### ISSUE TITLE
Request: Add ability to turn off server sync for larger packs

### ISSUE THREAD

**Issue by Zareks** [mezz/JustEnoughItems#546] opened 2016-10-28 14:37 UTC
Please allow for some desync to occur when using a large mod pack on a server as despite the recent fix of allowing JEI to sync after connection you still get timed out when in the server for larger packs.
(Also suggested in discord: "possibly move recipe building to it's own thread so the mainthread is kept alive" )

**Comment by TehNut** [comment] 2016-10-28 16:03
JEI loads it's plug-ins during postInit, now.

**Comment by Gaelan** [comment] 2016-10-28 18:59
JEI still does something time-consuming on world join if whatever-it-is-these-days-Tweaker is installed.

**Comment by TehNut** [comment] 2016-10-28 19:00
That wouldn't be JEI.

**Comment by Gaelan** [comment] 2016-10-28 19:02
I believe it is. On mobile so can't link, but I believe CraftTweaker (I think that's it) calls something along the lines of JeiHelpers.reload() on server join.

**Comment by mezz** [comment] 2016-10-28 19:46
Thanks for the report!

This is a valid concern that I'm working with CraftTweaker to resolve.
https://github.com/jaredlll08/CraftTweaker/issues/69

Unfortunately, it's difficult to make changes to CraftTweaker without disrupting the whole ecosystem, so many things are being considered carefully and change could be slow.

This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/353
See this issue for more on CraftTweaker https://github.com/mezz/JustEnoughItems/issues/537

**Closed as completed by mezz** 2016-10-28 19:46 UTC
Labels: duplicate
