### ISSUE TITLE
JEI - > Recipes use too many items

### ISSUE THREAD

**Issue by Morbidcactus** [mezz/JustEnoughItems#918] opened 2017-06-29 18:24 UTC
This one seems a little odd, noticed it when I was crafting some RFTools items but it has shown up in OpenModularTurrets, EnderIO, Actually Additions and Vanilla Recipes

I had thought it was a visual thing but when crafting with RF Tools storage scanners or autocrafters, the recipe uses these extra items.

I will submit this issue to RfTools as well, as it is what I first noticed the problem with.

![2017-06-29_14 20 07](https://user-images.githubusercontent.com/29522189/27703802-942ba826-5cd6-11e7-8232-814f112b0828.png)
![2017-06-29_14 20 20](https://user-images.githubusercontent.com/29522189/27703806-9439ac1e-5cd6-11e7-8456-93cf616debe5.png)
![2017-06-29_14 20 31](https://user-images.githubusercontent.com/29522189/27703804-943903cc-5cd6-11e7-8e68-24132a4d79be.png)
![2017-06-29_14 20 52](https://user-images.githubusercontent.com/29522189/27703805-94398266-5cd6-11e7-87a2-9b189b4e7db0.png)

**Comment by mezz** [comment] 2017-06-30 03:59
Thanks for the report!
This is normally an issue with a mod accidentally editing the ore dictionary items, which affects lots of recipes. You might track it down by removing some of your mods until it works correctly. 
JEI is displaying the actual recipe, vanilla crafting tables just take 1 item no matter what.

**Comment by Famous5000** [comment] 2017-06-30 21:04
That is a good point.

**Comment by Weldera** [comment] 2017-08-12 21:12
I have the same issue did it get resolved and what was the cause?

**Comment by mezz** [comment] 2017-08-12 21:54
There is no resolution yet, some mod is editing itemstacks in the oredictionary but we do not know which mod is doing it.
If you can, please try copying your pack and then remove mods until the issue goes away. That way you can figure out which mod is causing the issue.

**Comment by Weldera** [comment] 2017-08-12 21:58
ill give it a go of finding what mod it is, is there a way i can look in a config instead of adding mods 1 by 1 and it taking ages.

**Comment by mezz** [comment] 2017-08-12 22:00
I recommend removing mods in batches, like 10 at a time. 
If the bug is still there, you just eliminated 10 mods from suspicion.
If the bug goes away, you know it's caused by just one of those 10.
The hard part is keeping track of library mods and who depends on what.

**Comment by Towdium** [comment] 2017-08-23 14:55
Well, I can put some more information here since I have done something very similar in an old version of JustEnoughCalculation. 

Any mod can break this easily, expecially the ones dealing with recipe or doing item transfer. The reason is the itemStack in the registry is not immutable. If anyone changed the itemStack in the registry by accident, without copying it, this change will affect this recipe everywhere.

By the way, in my case, I made every recipe always produce one item, and added some strange NBT info.

In most of the case, this issue is not related to JEI, the recipe is changed by someone else, JEI is just displaying the result.

**Comment by mezz** [comment] 2017-08-30 03:43
I am closing this because it is not really caused by JEI, and it might be useful to see when recipes are altered incorrectly this way.

**Closed as completed by mezz** 2017-08-30 03:43 UTC
