### ISSUE TITLE
[Feature/Issue][API]  Way dynamicly create a category for blocks with NBT data

### ISSUE THREAD

**Issue by Runesmacher** [mezz/JustEnoughItems#726] opened 2017-02-08 23:28 UTC
I am trying to create recipes for fluidConverters, hereby multiple converters can be created in a config file.
For each converter a new blokck with nbt data will be added.

I would like to be able to create a category for each of these dynamicaly so each converter will have its own category. I have made it now by showing the text of the converter above the conversion but this is not optimal. 
I tried explaining this with the pictures below.

![69vccirp](https://cloud.githubusercontent.com/assets/979451/22761657/0375e1f4-ee5c-11e6-803e-087504bcdaad.jpg)
![ugvyni1p](https://cloud.githubusercontent.com/assets/979451/22761656/03754622-ee5c-11e6-9839-6dd1e23c4d3f.png)

Also my code if anyone wants to have a look and give me a hand if it is already possible: https://github.com/Runesmacher/FluidConverters/tree/AddJEIIntegration

**Comment by mezz** [comment] 2017-02-09 01:26
I think you need an item subtype interpreter for your fluid converters. It will tell JEI to treat them as different items. See here:
https://github.com/mezz/JustEnoughItems/wiki/Item-Subtypes

**Comment by Runesmacher** [comment] 2017-02-09 17:47
The first picture is solved by that solution. Commit: https://github.com/Runesmacher/FluidConverters/commit/cb9815ef7cad7b384f351aef50c47bffd8d78850

But the second one still stands, if i ask for uses of a fluidconverter it will show me all the fluidconverter recepies, not only the one i clicked on, also the image of the item that is being used is shown as one of the converters and not the one i clicked on

**Comment by mezz** [comment] 2017-02-10 00:22
The issue is that you have every fluid converter registered as an item that can craft every recipe in the category.

I can think of two possible solutions:
 * Add a recipe category for each fluid converter
 * Remove the fluid converter from the `addRecipeCategoryCraftingItem` and add it as an ingredient shown on the recipe instead.

**Comment by Runesmacher** [comment] 2017-02-10 22:01
I have tried adding the converter as an ingridient. When clicking on a converter it now only shows the recipies for this converter as i want.
Only issue is that now the tab just says "Fl" and i want it to show the actual converter that i selected. (But i'm not sure how it would go with selecting a fluid that can be created in multiple converters)

I think the better option would be to make a category for each converter, but since they are dynamicly ccreated on load with a config file i'm not sure how to do this. (some assistance on this could be helpfull since i'm quite new with modding/Java in general)

**Comment by sp-guip** [comment] 2017-02-11 09:35
it is one item?
if so you can just add a function that point to a category and register all categories of the subitems.
https://gist.github.com/sp-guip/685a1124b01199d3059192a4bf138d79
hope it will help.

**Comment by Runesmacher** [comment] 2017-02-12 11:07
It is one item, i have tried musltiple thing to get it to work.
The issue is that i have only one recipe class (FluidConverterRecipeJEI) and for eachc category i want i need a handler, which points to the class of the recipe. How would i do this?

Updated commit: https://github.com/Runesmacher/FluidConverters/commit/2784dd31da229a463378dbe9334d08e18687cda2

What EJI says:
A Recipe Handler has already been registered for this recipe class: org.cyclops.fluidconverters.modcompat.jei.fluidconverter.FluidConverterRecipeJEI

**Comment by sp-guip** [comment] 2017-02-12 15:46
you can't reuse a RecipeHandler the way you did,
you can implement IRecipeHandler#getRecipeCategoryUid(yourRecipeWrapper wrapper)
and switch the category in the wrapper that's what I do.

**Comment by sp-guip** [comment] 2017-02-12 15:47
make a field in the recipe wrapper that point to the categoryName it belongs to.

**Comment by Runesmacher** [comment] 2017-02-12 16:24
You, Sir (@sp-guip) are awesome 👍 thanks for the help! it is working how i want it now :D 
I looked at how you did it in Thermal expansion and applied it to my code.
Only thing left is cleanup...

https://github.com/Runesmacher/FluidConverters/commit/d3f262c80140944e6c2d1ca2c32fb0437528fce2

**Comment by sp-guip** [comment] 2017-02-12 18:21
always happy to help.

**Comment by sp-guip** [comment] 2017-02-12 18:27
It's probably a good idea to close this issue down since you found a solution.

**Closed as completed** 2017-02-12 19:02 UTC
Labels: question
