### ISSUE TITLE
Search bar; loss of focus / hang

### ISSUE THREAD

**Issue by CMCarlsen** [mezz/JustEnoughItems#649] opened 2016-12-02 21:03 UTC
This event is kind of frustrating as I'm having difficulty reproducing it in a reliable manner. However, it affects both myself and others using the mod-pack. Here goes:

After having typed something into JEI and wishing to erase it, some unknown event triggers (presumably a bad mod interaction?), and the search bar stops responding. The search box no longer takes input from the keyboard or mouse, and I have to close and re-open my inventory before it will take inputs again. If I right-click the search bar before triggering the event, it clears the entire bar, but then the event triggers and it stops taking input, requiring inventory window refresh.

Things I know about the issue:
- It stops deleting text at the last, or second to last, character. (e.g. "banana" stops at "ba" or "b")
- I have to refresh my inventory window before I can finish deleting the text, and type my new query.
- Right-click to clear will delete the entire bar, but it still won't allow input until after inventory refresh.
- Once the issue occurs, text cannot be added either. It is stuck.
- The error can occur in both single and multiplayer!

Things I'm presuming:
- Is caused by bad mod interaction with JEI, ~though I'm currently unsure which mod~ [SignPicture](https://minecraft.curseforge.com/projects/sign-picture).
- The issue seems to trigger after a set amount of time? Or possibly when exploring item recipes in JEI?

Things I've tried / am trying:
- ~Right-click to clear; causes error to trigger.~
- ~If I quickly type and delete text, the issue doesn't seem to occur (at least not yet)~.
- Seems to occur when hitting certain keys while searching in JEI.

General Info:
- MC version: 1.10.2
- Forge version: forge-12.18.3.2185
- Has occurred in two different mod packs I've modified. One is the Direwolf pack, the other is the "All The Mods" pack. (However, I feel it important to note that I have **_heavily_** edited both mod packs. At the point the error occurred, they were more or less home-brew packs.)

Will update this as I gain a better understanding.

**Comment by Drakma** [comment] 2016-12-03 18:33
This appears to have occurred sometime between .383 and .384  from my experimenting

**Comment by mezz** [comment] 2016-12-03 18:41
The only change to .384 was exposing something that already existed to the API. 
Nothing to do with the search bar unfortunately.

**Comment by Drakma** [comment] 2016-12-03 22:39
The only way I can duplicate this is when AE2 is installed using JEI .380 and above.  If you're using AE2 alpha6 or newer you may want to revert.

**Comment by CMCarlsen** [comment] 2016-12-03 23:14
I'll check it out, thanks!

**Comment by CMCarlsen** [comment] 2016-12-04 03:28
@Drakma , Unfortunately  I tried uninstalling AE2 completely, and the issue was still present.

edit: Did you mean roll back JEI to .380?

**Comment by tacogerbil** [comment] 2016-12-06 21:34
I don't have AE2 at all.  Mine happened when I typed a lower case "o" followed by a tilde.  I am now unable to interact with the gui buttons for JEI.  I've restarted, deleted configs for JEI.. nothing seems to work.  There is now a permanent "o`" on the JEI search bar which I  cannot delete or overwrite.  I'm using a custom modpack..   

Is it possible it's not necessarily another mod but the characters in the search bar are causing some search function to never complete?

**Comment by mezz** [comment] 2016-12-06 21:38
With just JEI and no other mods, 
```
o`
```
in the search does not cause any issues.

Please make a backup and try removing mods from your pack to see which mod is interfering.

**Comment by CMCarlsen** [comment] 2016-12-06 22:00
@mezz , I just want to point out that although there are some similarities in our issues, unless I'm misunderstanding something, his issue is "permanent". Mine only requires that I open/close my inventory.

That being said, @tacogerbil , is there a chance you could submit a list of the mods you are using on pastebin.com or something? I could use it to cross reference against my own modpack, and possibly expedite this whole process.

Thanks guys!

(P.S. My school term just ended, so I'll hopefully be able to sit down in the next day or so and actually work on figuring this out. Whoooo!)

**Comment by dmb1881** [comment] 2016-12-06 22:02
Could it possibly be an addon for jei such as jei hider, or jei bee's? Something that works alongside jei that could possibly messing it up?

**Comment by CMCarlsen** [comment] 2016-12-06 22:08
@dmb1881 , I had thought that as well, but unfortunately, as far as I can tell that is not the case. I have tried loading up JEIbees, as well as JER, and no issue seemed to occur. That's not necessarily ruling anything out though. This issue has been extremely difficult to reproduce on command. I imagine if I could figure out how to trigger it, it would aid a lot in figuring out why it's happening/what's causing it.

 My biggest fear now is that it's not actually a _single_ mod causing the issue to occur, but rather a combination of two or more mods causing the problem. I don't understand the inner workings of Forge nor mod-interaction stuff very clearly, but if there is something firing between a combination of mods that causes this issue then the diagnosis of this problem just became significantly more difficult. =/

**Comment by dmb1881** [comment] 2016-12-06 22:12
@CelticChristoph There has to be a singular mod we all have installed that must be producing the bug then. Its just a matter of what mod and why.

**Comment by tacogerbil** [comment] 2016-12-06 22:14
Here they are ;)
http://pastebin.com/NtMtN6uk

**Comment by CMCarlsen** [comment] 2016-12-06 22:18
@tacogerbil , Yo! Do you mind if I ask how you produced that list so quickly?

I've actually been looking for a way to pump out a list of installed mods like that. I'm assuming there's some kind of log or list kept somewhere, that I just haven't found yet? Sorry, I've been **super** busy with finals and really haven't been able to commit time.

@dmb1881 , Could you also submit a list of your installed mods? If you don't know how, hopefully tacogerbil can share his method and we can both learn something. ;P

I can then use all three to cross-reference everything later tonight and _hopefully_ we can chase out this stupid issue.

Thanks guys!

(I'm heading out for the evening now. So I'll get back to you guys in say... about 6-7 hours if I can?)

**Comment by dmb1881** [comment] 2016-12-06 22:19
@CelticChristoph I am disabling 1 by 1 the mods we both had installed and testing to see which one might be causing it.

**Comment by CMCarlsen** [comment] 2016-12-06 22:21
Ah, alright. Well, good luck!

Let us know what your findings are. :+1:

**Comment by dmb1881** [comment] 2016-12-06 22:21
Just as I thought, its actually inventory tweaks thats causing the bug. Im not sure why it'd be that but it is.

Edit: It still happens but with inventory tweaks, it makes it more bearable
Edit #2: I actually am not sure anymore. everytime I type something now it still seems to happen. But I did notice it only happens after I press the letter "O"

**Comment by CMCarlsen** [comment] 2016-12-06 22:22
Wait holy crap, really? That actually makes a lot of sense. I've been noticing some other really weird inventory bugs, but for whatever reason, my mind just didn't connect the two. One moment and I'll go ahead and boot up my stuff.

If this solves the issue that'll be amazeballs!

edit: Ah, I just went to check and I have InventoryTweaks-1.62-dev-66 in my current build of the pack. I couldn't reproduce it last night, but I don't have all of the usual mods installed. Did you ONLY have InventoryTweaks installed, or all of your other mods as well? (Also, I really do have to go now. Thanks for helping out with this guys!)

**Comment by tacogerbil** [comment] 2016-12-06 22:25
@CelticChristoph I'm using a Mac, when you drag and drop files onto an open text edit document in plain text mode (not rich text) it will list the filenames (including paths), I just drag ALL my mods onto the document then find and replace the text I don't want (the path to the files) and it's done ;)
Might be able to with windows using a text editor... 
![image](https://cloud.githubusercontent.com/assets/12961907/20946449/8c151a68-bbbf-11e6-8453-cb81cb5a89a2.png)

**Comment by CMCarlsen** [comment] 2016-12-06 22:27
Unfortunately I wasn't able to use that method with either Notepad or Notepad++. :stuck_out_tongue_winking_eye: 

![image](https://cloud.githubusercontent.com/assets/3077339/20946563/0dbce0d2-bbc0-11e6-90c9-2d641aac9c29.png)

(Okay, I'm _**really**_ going now. Hahaha)

**Comment by dmb1881** [comment] 2016-12-06 22:29
@tacogerbil I just noticed, you have both jei and nei installed?

**Comment by tacogerbil** [comment] 2016-12-06 22:34
Do this @CelticChristoph , If you're using windows 7 (maybe newer?) you should be able to go to the folder with your mods... Right click on the folder while holding the "shift" key, and select "open command window here".
Now type 
dir /b > dir.txt
this will create a file named dir.txt with the names of all the files in that folder.
You can also open the command prompt and cd to the folder..
cd "C:\Documents and Settings\name\folder\folder"
THEN do the "dir /b" step..
;)

**Comment by tacogerbil** [comment] 2016-12-06 22:39
@dmb1881 you can't use NEI without JEI anymore (far as I know)... Some functionality like while you're at a crafting table with a recipe open... you can't click the + button to have NEI place all the items from your inventory (if available) into the crafting table for you.. 

Or at least at the time I placed it there that's the way it was.. Never looked into it again. ;D jejeje

**Comment by dmb1881** [comment] 2016-12-06 23:20
So i've been doing quite a bit a testing and haven't been able to reproduce the bug. I'm not sure what the issue is... try updating all the mods maybe it will fix it?

**Comment by CMCarlsen** [comment] 2016-12-07 07:12
@tacogerbil , I went ahead and did a list comparison, here's the results I got. I removed extraneous mods that were exclusive to one pack or the other. Mods that are highlighted in yellow are matching mods with different version numbers.

As our original issues appear to _possibly_ be different issues all together, I don't know that this means another mods outside of this list could be causing our issues, but it seems like a decent place to start. I'm going to make a pack with just these mods and see if I get the issue though. If so, we might be on to something!

@dmb1881 , Yo, if you could possibly submit a list of the mods you're using when you ran into the issue, it could potentially narrow this down even more. The methods for making a list of your mods are listed above, if you didn't catch it before!

![image](https://cloud.githubusercontent.com/assets/3077339/20958255/7434deb6-bc09-11e6-8425-a2638d89f622.png)

**Comment by mezz** [comment] 2016-12-07 07:13
You can just make a copy of your pack and remove some mods, you're close now so it's not difficult.

**Comment by CMCarlsen** [comment] 2016-12-07 07:39
Oh, I've been doing that. But again, because of the inability to reproduce this mod reliably, and the general lack of information or ways to test it, I'm trying to narrow this down as much as I can.

One other thought struck me though mezz. Is there any chance that the sheer size of a pack could in some way cause an issue? I doubt it's this, as packs like "All The Mods" don't seem to be having the issue, else there would likely be more people bringing it up. But it seemed worth asking.

 I made one further inspection and compared against an older mod-pack that I was having the same issue with; the red marks denote mods that aren't in the older pack. mezz , do any of these mods stand out to you that could potentially be the issue? (of the ones on the right):
![image](https://cloud.githubusercontent.com/assets/3077339/20958909/0ad16206-bc0d-11e6-9bcc-afbb6b59113b.png)

**Comment by mezz** [comment] 2016-12-07 07:51
Based on your list, I would suspect Inventory Tweaks first because it uses keyboard input when guis are open.

**Comment by mezz** [comment] 2016-12-07 07:53
I don't think the size of a pack would have any effect.

**Comment by CMCarlsen** [comment] 2016-12-07 08:50
Whoo!

So I've been able to reproduce the mod with just the above list on the left. I'm going to start by removing InvTweaks. If that doesn't do it, I'll start with the mods in red, as they weren't not in the original pack I was using and as such should theoretically not be apart of the issue.

If not that, I suppose it'll be back to just removing individual mods until I get this pinned down.

Oh boooooy!

Edit:
~~As an added note, it seems that the error occurs when I open a recipe of something, and then while looking at the recipe press "R", which is a major button of InvTweaks? I could definitely be biased and trying to _make_ it InvTweaks, but it definitely seems this might be the case!~~

Edit2:
It seems (again, hard to prove) that when the error occurs, if a string modifier like the @ symbol is used, it causes the "two-character" version to occur. While if I type a simple string with no modifier, it freezes at only a single character remaining.

I have to add the additional possibility however that this could be caused by string-length, as the strings I type without an @ symbol tend to be shorter so that JEI can actually find items (e.g. "stone"). With the @ symbol I tend to type the majority of a mods name (e.g. "@actuallyadd"). Thus it's possible string length may be the actual issue here?

Edit 3:
Not InventoryTweaks. After having removed the mods in red as I listed I would do earlier, this leaves my next two guesses either with BetterFPS or this mod called SignPicture. -shrug-

**Comment by CMCarlsen** [comment] 2016-12-07 11:52
Got it figured! It's this cutesy little mod called [SignPicture](https://minecraft.curseforge.com/projects/sign-picture). Funny enough, upon going to SignPic's GitHub page and looking at their issue tracker, someone else seems to have reported a similar issue!

I'll go ahead make a post over on their issue tracker, see what happens. I'm aware there isn't much you can do in this case anymore, but if they're interested in trying to fix it, would you be willing to try and help? I'd like to be able to let them know if so.

Thanks for your help everyone involved! :cake:

**Comment by Drakma** [comment] 2016-12-07 19:42
Just came here to confirm @CelticChristoph Just removed it after going through my pack 1 by 1 and this was the culprit.

**Comment by tacogerbil** [comment] 2016-12-07 22:42
I'll confirm that it was NEI that was causing further issues.. although I believe it's related to this (it's being affected the same way as JEI).. it was causing the interface to become frozen and editable.  Otherwise without NEI, JEI is acting just like it is for the rest..  UGH.....

**Comment by dmb1881** [comment] 2016-12-07 23:07
Remove nei, at this point nei is just dull and worn out. I honestly enjoy jei better.

**Comment by tacogerbil** [comment] 2016-12-08 00:41
I just did.  For better or worse, it still had some functionality... Still,
now I can play again jejejeje

**Comment by tacogerbil** [comment] 2016-12-10 17:34
A little update..... I renamed SignPicture to ZZzzzzSignPicture-1.10.2-2.5.1-universal so it would load last... So far no conflict with JEI.... Still playing with it... but normally JEI starts to act up almost immediately in the crafting table, refined storage or ez storage......

**Comment by tacogerbil** [comment] 2016-12-10 18:05
Is it just me.. or does the issue also subside when you change the screen size?  When I am unable to type, IF I resize the screen instead of exiting the JEI screen.. If I resize (I'm on a mac, by clicking the maximize minimize buttons on the minecraft gui) I am able to regain focus on the search bar, scroll buttons AND crafting recipes.

**Comment by CMCarlsen** [comment] 2016-12-10 21:30
@tacogerbil , Yo!

At this point, I think anything that we discover on this issue should be addressed over here:
https://github.com/Team-Fruit/SignPicture/issues/9

The mod author, Kamesuta, appears to be willing to help but cannot reproduce the error themselves.

**Comment by mezz** [comment] 2016-12-10 21:33
I will close this issue, so that discussion happens here instead: Team-Fruit/SignPicture#9

**Closed as completed by mezz** 2016-12-10 21:33 UTC
Labels: other mod
