### ISSUE TITLE
Crash when using JEI to lookup Tinkers recipes

### ISSUE THREAD

**Issue by Yarden-zamir** [mezz/JustEnoughItems#881] opened 2017-06-03 11:31 UTC
`	Reported exception thrown!
net.minecraft.util.ReportedException: Rendering screen
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1121)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
	at net.minecraft.item.crafting.FurnaceRecipes.func_151397_a(FurnaceRecipes.java:98)
	at net.minecraft.item.crafting.FurnaceRecipes.func_151398_b(FurnaceRecipes.java:113)
	at mezz.jei.plugins.vanilla.furnace.SmeltingRecipe.drawInfo(SmeltingRecipe.java:41)
	at mezz.jei.gui.recipes.RecipeLayout.draw(RecipeLayout.java:122)
	at mezz.jei.gui.recipes.RecipesGui.func_73863_a(RecipesGui.java:202)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	... 9 more` 
i believe it crashes on other recipes from other mods too.
Edit : i don't think it crashes with other mods.
[crash-2017-06-03_16.03.29-client.txt](https://github.com/mezz/JustEnoughItems/files/1049826/crash-2017-06-03_16.03.29-client.txt) <-- crash report
[2017-06-03-7.txt](https://github.com/mezz/JustEnoughItems/files/1049828/2017-06-03-7.txt) <-- log

**Comment by mezz** [comment] 2017-06-03 18:11
Thanks for the report!
This does not appear to be the same issue as #863.
Please paste the full `fml-client-latest.log` to https://gist.github.com and link it here.

**Comment by Yarden-zamir** [comment] 2017-06-03 18:37
added the crash report

**Comment by mezz** [comment] 2017-06-03 18:50
This is caused by another mod adding a bad smelting recipe, but I can protect against the crash.

**Comment by mezz** [comment] 2017-06-03 18:51
Fixed in the next JEI version for 1.10.

**Closed as completed by mezz** 2017-06-03 18:51 UTC
Labels: minor bug
