### ISSUE TITLE
latest 1.12.2 version is picked up as "@VERSION@" or something not a version number causing forge to list incompatibilities

### ISSUE THREAD

**Issue by Nathan22211** [mezz/JustEnoughItems#2063] opened 2020-08-23 12:04 UTC
version 4.16.1.300 is what's causing this

**Comment by Valafi** [comment] 2020-08-23 20:46
Duplicate of #2060

**Comment by mezz** [comment] 2020-08-24 01:02
Thanks for the report!
This should be fixed in the next release.

**Closed as completed by mezz** 2020-08-24 01:02 UTC
