### ISSUE TITLE
Suggestion - Item Usage (U key) Exclusivity/Unique search filter

### ISSUE THREAD

**Issue by ariosos** [mezz/JustEnoughItems#2076] opened 2020-08-31 02:36 UTC
Might be hard to describe, and I don't know how feasible it is, but I would like to see some option to show that items can be crafted ONLY using using the recipe item searched for.

For example -

I hover over a pink slime from Industrial Foregoing and press "U" to view the uses. In the pack I'm playing, it has 60 uses.
I hover over a vanilla green slimeball, and it shows 59 uses, thus there is 1 item (the Material Stonework Factory) that the pink slime ball is exclusive to (other ore-dictionaried slime balls don't count).

I would like some toggle option, if possible, to show items have no alternate (ore-dictionary) recipes.

**Comment by Ommina** [comment] 2020-08-31 04:38
Just for the sake of clarity, is this similar to #1894 ?

**Comment by mezz** [comment] 2020-09-27 00:28
Thanks for the suggestion!
I think this is a dupe of the other so I'll close this one.

**Closed as completed by mezz** 2020-09-27 00:28 UTC
Labels: duplicate
