### ISSUE TITLE
Crash when using shortcuts for inventory crafting

### ISSUE THREAD

**Issue by hypernova132** [mezz/JustEnoughItems#2656] opened 2022-01-05 20:17 UTC
[crash-2022-01-05_14.11.12-client.txt](https://github.com/mezz/JustEnoughItems/files/7817551/crash-2022-01-05_14.11.12-client.txt)

**Comment by mezz** [comment] 2022-01-06 13:48
Thanks for the report!
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/2638
Please try the latest version of JEI, it should be fixed already.

**Closed as completed by mezz** 2022-01-06 13:48 UTC
