### ISSUE TITLE
Crash on writing "pu" - Vertex Buffer (Caused by Optifine)

### ISSUE THREAD

**Issue by InsideBSI** [mezz/JustEnoughItems#724] opened 2017-02-07 16:42 UTC
Hello and thank you for your great mod !
I just have a minor issue: (i have serveral mods installed), and i'm crashing if i write "pu" in the search box.
I need to see the list of available pumps, so it's a bit problematic :p
I use the last version, there is the crash report: https://gist.github.com/InsideBSI/c145e6b1e6764e626ba44ae176137701
And here the logs: https://gist.github.com/InsideBSI/237368072f26be27dd601e172c8693f9
If you have any ideas =)
I removing now all the mods one by one, and i hope to discover something

Have a nice day !
InsideBSI

**Comment by InsideBSI** [comment] 2017-02-07 16:45
Obviously that is Optifine

**Comment by mezz** [comment] 2017-02-08 02:58
Thanks for the report!
This seems to be a duplicate of #714
It is an Optifine bug, fixed in Optifine preview B7 for 1.11.2

**Closed as completed by mezz** 2017-02-08 02:58 UTC
Labels: other mod
