### ISSUE TITLE
Suggestion: Tagless uses lookup

### ISSUE THREAD

**Issue by Rodg88** [mezz/JustEnoughItems#2628] opened 2021-12-28 12:25 UTC
When modpacks make extensive use of tags, it can be really hard to tell if an item has a use specific to it, and not be able to be substituted for other tagged items.

For example, if you look up the uses for andesite, you'll get shown all the recipes that call for forge:stone, amongst all the uses for everything else in the tags
![image](https://user-images.githubusercontent.com/2611674/147565770-fa160390-254c-49e8-91cc-23908fc6eacd.png)
But if there was an extra option for a tagless lookup, you could see just the recipes that call for andesite only, and filter out anything that wants just any stone.

**Comment by KoloXD** [comment] 2022-01-20 16:35
Been searching for a while for any information on this. It is quite sad that it is not a feature yet seeing the label.

Seeing the uses of specific items would be extremely useful in even medium sized modpacks so implementing this feature would be highly appreciated.

**Comment by jursamaj** [comment] 2023-07-22 03:30
I concur: I would love this feature.

**Comment by roboboredom** [comment] 2024-02-25 01:04
This would be amazing. I would love this so much

**Comment by mezz** [comment] 2024-07-19 04:51
Thanks for the request!
I think this is a duplicate of 
* https://github.com/mezz/JustEnoughItems/issues/1467

**Closed as not planned by mezz** 2024-07-19 04:51 UTC
Labels: enhancement
