### ISSUE TITLE
[Bug]: JEI Problems with LAN worlds

### ISSUE THREAD

**Issue by MrPiggy37** [mezz/JustEnoughItems#2773] opened 2022-03-23 23:23 UTC
### Steps to Reproduce the Bug

Try to view a recipe

### Expected Behavior

Shows recipe

### Actual Behavior

I press the keybind to view the crafting recipe in this case R or LMB and nothing happens or it just shows how to smelt it

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/enigmatica6

### Mod Pack Version (Optional)

1.16.5

**Comment by mezz** [comment] 2022-03-24 00:07
Thanks for the report!
I don't see any issues with this pack. Please improve your bug report so that I can reproduce the issue.

**Comment by MrPiggy37** [comment] 2022-03-24 16:41
Every time I go to view a recipe using the keybind or lmb it either shows me nothing or nothing happens or it displays enchantments/how to smelt it for said item but it only happens on multiplayer and is very irritating cause I cannot view recipes I don't have the keybind set on anything else and I've tried reinstalling the mod pack to see if it will fix it but it did not

**Comment by mezz** [comment] 2022-03-24 18:28
To help me understand better:
Does this happen for every recipe, or just recipes from specific mods? 
Does this happen if you just have JEI installed, or is it fixed when you remove some mods?
Have you modified the pack? It’s a big pack and nobody else has reported this.

**Comment by MrPiggy37** [comment] 2022-03-24 18:46
> Does this happen for every recipe or just recipes from specific mods?

It does happen to every recipe and JEI works with all the mods and on its own when I'm in single player just not when I join the world and we haven't modified the pack idk if this is useful but the world is a LAN world

**Comment by mezz** [comment] 2022-03-24 20:31
Ok, I think that is probably an important detail because it makes your setup different from most other people.
This may be a duplicate of the bug reported here: https://github.com/mezz/JustEnoughItems/issues/2742
Can you confirm if this looks like the same bug?

**Comment by MrPiggy37** [comment] 2022-03-24 20:47
I believe so

**Comment by mezz** [comment] 2022-03-24 21:54
I will close this issue as a duplicate so that we can keep all the discussion in one place.
Can you join the other issue (https://github.com/mezz/JustEnoughItems/issues/2742) and try removing JustEnoughResources and Optifine, and see if it helps?

**Closed as completed by mezz** 2022-03-24 21:54 UTC
Labels: duplicate
