### ISSUE TITLE
[1.12.2] Give Mode Iinventory setting not working

### ISSUE THREAD

**Issue by Andronomos** [mezz/JustEnoughItems#1079] opened 2017-12-18 12:48 UTC
After changing the give mode setting to inventory, items can no longer be grabbed. Clicking an item does nothing.

**Comment by lag42** [comment] 2017-12-18 21:58
i have this issue too and it is really frustrating

**Comment by lag42** [comment] 2017-12-18 22:28
fixed in alpha, but not release version

**Comment by mezz** [comment] 2017-12-19 04:59
Thanks for the report!
This is fixed, and a duplicate of https://github.com/mezz/JustEnoughItems/issues/1077
I will mark the latest version as a release.

**Closed as completed by mezz** 2017-12-19 04:59 UTC
Labels: duplicate
