### ISSUE TITLE
(1.18.1) "show recipes/show uses" not working as they should.

### ISSUE THREAD

**Issue by opticGT** [mezz/JustEnoughItems#2599] opened 2021-12-12 21:22 UTC
![image_2021-12-12_142114](https://user-images.githubusercontent.com/19476801/145729968-206a5b50-9b97-4062-a51b-d192c21ed789.png)
when using default the "R" and "U" keys work for looking for recipes/uses. but mouse "LEFT/RIGHT" do nothing...

**Comment by RetroWave1736** [comment] 2021-12-12 21:30
Im not seeing the JEI options in the settings and the R and U keys dont work

**Comment by mezz** [comment] 2021-12-13 01:49
Thanks for the report!
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/2590
We can keep discussion there and hopefully I'll get a fix out soon.

**Closed as completed by mezz** 2021-12-13 01:49 UTC
Labels: duplicate
