### ISSUE TITLE
Mismatching Enchantment Names in recipe and the JEI item list

### ISSUE THREAD

**Issue by nizhuan-jjr** [mezz/JustEnoughItems#1343] opened 2018-08-26 13:20 UTC
JEI version：1.12.2-4.11.0.212

This issue occurred when adding/removing a mod that contained enchantments into an existing world, in other words, creating a new world won't have this issue.

After adding a new mod that contained enchantments to the existing world I was playing, the enchantment names in the item list won't be the same as the names in the usage GUI, despite having a correct recipe(if ignore the names).

For example, when I left-click the enchantment Gills（an enchantment for helmets only） in JEI item list,
![2018-08-26_20 37 59](https://user-images.githubusercontent.com/3255986/44628432-3aa41d80-a972-11e8-8408-ba85bd84424a.png)
the GUI will show a correct recipe but the enchantment name is not Gills but bloodlust(an enchantment for swords only). Continually, if I left-click the bloodlust here,
![2018-08-26_20 38 05](https://user-images.githubusercontent.com/3255986/44628465-af775780-a972-11e8-8207-de52b8bd8f01.png)
I will arrive at bloodlust's recipe correctly but again, the name of the enchanted book in the recipe is another enchantment Arrowstorm( which is an enchantment for bows only).
![2018-08-26_20 38 27](https://user-images.githubusercontent.com/3255986/44628508-6a075a00-a973-11e8-8035-33cf59d74c89.png)

It seems that adding/removing a mod involved enchantments into an existing world would mess up the enchantment IDs or names somehow. 
Is it possible to rebuild the enchantment IDs based on neutral section(for example, the main menu section) when entering an existing world? Or maybe use the enchantment IDs from the main menu section to override the messed up existing world IDs? Or maybe use the IDs from an new world with same modlist to update the IDs in the existing world? 
I don't know much about coding for MC, these are just brainstorming.
Hope you guys could come up with solution for this issue.

**Comment by TehNut** [comment] 2018-08-26 17:01
#1202

**Comment by mezz** [comment] 2018-09-06 05:40
Thanks for the report!
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/1202

**Closed as completed by mezz** 2018-09-06 05:40 UTC
Labels: duplicate
